### PR TITLE
Fix: Retries of batch downloads may never succeed (#2352)

### PR DESCRIPTION
**Pull request by danielsotirhos**
Author

- [x] PR title references issue
- [x] Title of main commit references issue
- [x] PR is linked to Zenhub issue

Author (reindex)

- [x] Added `r` tag to commit title                         <sub>or this PR does not require reindexing</sub>
- [x] Added `reindex` label to PR                           <sub>or this PR does not require reindexing</sub>

Author (freebies & chains)

- [x] Freebies are blocked on this PR                       <sub>or there are no freebies in this PR</sub>
- [x] Freebies are referenced in commit titles              <sub>or there are no freebies in this PR</sub>
- [x] This PR is blocked by previous PR in chain            <sub>or this PR is not chained to another PR</sub>
- [x] Added `chain` label to the blocking PR                <sub>or this PR is not chained to another PR</sub>

Author (upgrading)

- [x] Documented upgrading of deployments in UPGRADING.rst  <sub>or this PR does not require upgrading</sub>
- [x] Added `u` tag to commit title                         <sub>or this PR does not require upgrading</sub>
- [x] Added `upgrade` label to PR                           <sub>or this PR does not require upgrading</sub>

Author (requirements, before every review)

- [x] Ran `make requirements_update`                        <sub>or this PR leaves requirements*.txt, common.mk and Makefile untouched</sub>
- [x] Added `R` tag to commit title                         <sub>or this PR leaves requirements*.txt untouched</sub>
- [x] Added `reqs` label to PR                              <sub>or this PR leaves requirements*.txt untouched</sub>

Author (before every review)

- [x] `make integration_test` passes in personal deployment <sub>or this PR does not touch functionality that could break the IT</sub>
- [x] Rebased branch on `develop`, squashed old fixups

Primary reviewer (before pushing merge commit)

- [x] Checked `reindex` label and `r` commit title tag
- [x] Rebased and squashed branch
- [x] Sanity-checked history
- [x] Build passes in `sandbox`                             <sub>or added `no sandbox` label</sub>
- [x] Reindexed `sandbox`                                   <sub>or this PR does not require reindexing `sandbox`</sub>
- [x] Added PR reference to merge commit
- [x] Moved linked issue to Merged
- [ ] Pushed merge commit to Github

Primary reviewer (after pushing merge commit)

- [ ] Moved freebies to Merged column                       <sub>or there are no freebies in this PR</sub> 
- [ ] Shortened chain                                       <sub>or this PR is not the base of another PR</sub>
- [ ] Verified that `N reviews` labelling is accurate
- [x] Commented on demo expectations                        <sub>or labeled as `no demo`</sub>
- [ ] Pushed merge commit to Gitlab                         <sub>or this changes can be pushed later, together with another PR</sub>
- [ ] Deleted PR branch from Github and Gitlab

Primary reviewer (reindex) 

- [ ] Started reindex in `dev`                              <sub>or this PR does not require reindexing `dev`</sub>
- [ ] Deleted BQ slot committment in `dev`                  <sub>or this PR does not require reindexing `dev`</sub>
- [ ] Checked for failures in `dev`                         <sub>or this PR does not require reindexing `dev`</sub>
- [ ] Started reindex in `prod`                             <sub>or this PR does not require reindexing `prod`</sub>
- [ ] Deleted BQ slot committment in `prod`                 <sub>or this PR does not require reindexing `prod`</sub>
- [ ] Checked for failures in `prod`                        <sub>or this PR does not require reindexing `prod`</sub>

Primary reviewer

- [ ] Unassign PR from reviewer and assign to PM

### CODE REVIEW

**Comment by danielsotirhos** [comment]
Showing curl config file with `--continue-at -` option and 2 large files (~700mb each)

```
daniel@Crispin ~/Downloads/temp $ ls -l
total 8
-rw-r--r--  1 daniel  staff  535 Dec 18 10:24 test.curlrc

daniel@Crispin ~/Downloads/temp $ cat test.curlrc 
--create-dirs

--compressed

--location

--continue-at -

url="https://service.azul.data.humancellatlas.org/repository/files/117d733e-0782-53c8-ab23-a0589061295c?version=2020-11-20T09%3A03%3A11.285229Z&catalog=dcp2"
output="005d611a-14d5-4fbf-846e-571a1f874f70.human_cell_counts_GRCh38.mtx.gz"

url="https://service.azul.data.humancellatlas.org/repository/files/df6e5678-1fe0-5242-8e9c-0f1c1a5ee7b0?version=2020-11-20T09%3A03%3A11.285229Z&catalog=dcp2"
output="005d611a-14d5-4fbf-846e-571a1f874f70.human_cell_counts_consensus.mtx.gz"
```

Curl download started and quit (Ctrl+C) in the middle of the 1st file download:

```
daniel@Crispin ~/Downloads/temp $ curl --config test.curlrc 
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:--  0:00:02 --:--:--     0
 46  703M   46  325M    0     0  11.7M      0  0:00:59  0:00:27  0:00:32 13.4M^C

daniel@Crispin ~/Downloads/temp $ ls -l
total 689920
-rw-r--r--  1 daniel  staff  344272896 Dec 18 10:25 005d611a-14d5-4fbf-846e-571a1f874f70.human_cell_counts_GRCh38.mtx.gz
-rw-r--r--  1 daniel  staff        535 Dec 18 10:24 test.curlrc
```

Re-starting curl to resume downloads. Quit (Ctrl+C) in the middle of the 2nd file download:

```
daniel@Crispin ~/Downloads/temp $ curl --config test.curlrc 
** Resuming transfer from byte position 344272896
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100  375M  100  375M    0     0  12.7M      0  0:00:29  0:00:29 --:--:-- 13.2M
  0     0    0     0    0     0      0      0 --:--:--  0:00:02 --:--:--     0
 34  670M   34  233M    0     0  11.3M      0  0:00:58  0:00:20  0:00:38 13.3M^C

daniel@Crispin ~/Downloads/temp $ ls -l
total 1969464
-rw-r--r--  1 daniel  staff  737711607 Dec 18 10:26 005d611a-14d5-4fbf-846e-571a1f874f70.human_cell_counts_GRCh38.mtx.gz
-rw-r--r--  1 daniel  staff  254144512 Dec 18 10:27 005d611a-14d5-4fbf-846e-571a1f874f70.human_cell_counts_consensus.mtx.gz
-rw-r--r--  1 daniel  staff        535 Dec 18 10:24 test.curlrc
```

Re-starting curl to resume and finish downloads.

```
daniel@Crispin ~/Downloads/temp $ curl --config test.curlrc 
** Resuming transfer from byte position 737711607
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:--  0:00:01 --:--:--     0
100   172  100   172    0     0    115      0  0:00:01  0:00:01 --:--:--   115
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100  428M  100  428M    0     0  12.7M      0  0:00:33  0:00:33 --:--:-- 13.2M

daniel@Crispin ~/Downloads/temp $ ls -l
total 2821432
-rw-r--r--  1 daniel  staff  737711607 Dec 18 10:26 005d611a-14d5-4fbf-846e-571a1f874f70.human_cell_counts_GRCh38.mtx.gz
-rw-r--r--  1 daniel  staff  703109346 Dec 18 10:27 005d611a-14d5-4fbf-846e-571a1f874f70.human_cell_counts_consensus.mtx.gz
-rw-r--r--  1 daniel  staff        535 Dec 18 10:24 test.curlrc
```

Re-starting curl after downloads already completed to show idempotence:

```
daniel@Crispin ~/Downloads/temp $ date
Fri Dec 18 10:28:03 PST 2020

daniel@Crispin ~/Downloads/temp $ curl --config test.curlrc 
** Resuming transfer from byte position 737711607
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:--  0:00:01 --:--:--     0
100   172  100   172    0     0    116      0  0:00:01  0:00:01 --:--:--   116
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100   172  100   172    0     0    178      0 --:--:-- --:--:-- --:--:--   178

daniel@Crispin ~/Downloads/temp $ ls -l
total 2821432
-rw-r--r--  1 daniel  staff  737711607 Dec 18 10:26 005d611a-14d5-4fbf-846e-571a1f874f70.human_cell_counts_GRCh38.mtx.gz
-rw-r--r--  1 daniel  staff  703109346 Dec 18 10:27 005d611a-14d5-4fbf-846e-571a1f874f70.human_cell_counts_consensus.mtx.gz
-rw-r--r--  1 daniel  staff        535 Dec 18 10:24 test.curlrc
```

**Review by hannes-ucsc — CHANGES_REQUESTED** [review]
Checklist incomplete.

**Review by hannes-ucsc — APPROVED** [review]

**Comment by hannes-ucsc** [comment]
For demo, show resumption of interrupted download.

**Review by amarjandu — APPROVED** [review]
pro-forma approval in order to merge into `develop`

**Pull request merged**
