### PR TITLE
Backport: Paging broken when sorting fields with Null values (#1607)

### PR DESCRIPTION
**Pull request by danielsotirhos**

### CODE REVIEW

**Comment by hannes-ucsc** [comment]
Wait with review request before the other PR is approved.

**Comment by danielsotirhos** [comment]
Backport of the following commits from develop to hca/develop:
015c3558f2c3cce58eb6b05218812797161778ab
67c39361183d384b6b65db4669ea0afd98b03310
8803d9b774776ea5adcf79c2db3a267eefc195ca
23b41460e864f8ffa72cb8a458c8d5a0be86ce40
1a9dcd183b832dd851295398d12b8657697b56cf

**Comment by danielsotirhos** [comment]
Brached of latest `hca/develop`:
a5777ace1b4c53d23a24ac06ca914607a05f6751
Cherry picked from `develop`:
015c3558f2c3cce58eb6b05218812797161778ab Verify labCount in summary aggregation (#1188)
67c39361183d384b6b65db4669ea0afd98b03310 Always sort multi-valued fields (#1446)
8803d9b774776ea5adcf79c2db3a267eefc195ca Fix: TypeError aggregating multi-valued fields with None (#1571)
23b41460e864f8ffa72cb8a458c8d5a0be86ce40 Sorting by multi-valued fields (#1445)
b9b8df5012eecc1b46508a5327c55939d46b0812 Fix next/prev link value when sorted field value is None (#1575)
e2f5cc30e3203dc0bb75e3ee7d49346c548269eb Fix paging when sorting on fields with Null values (#1575)
5bc491df3ee153c75b2145ab742cdb36a230abd3 Improve assertion messages for `translate_fields`

Confirmed IT passed with local deployment: 
[backport-integration-test-results.txt](https://github.com/DataBiosphere/azul/files/4357482/backport-integration-test-results.txt)

**Comment by hannes-ucsc** [comment]
Sandbox build failed because I forgot to run `make delete`. Did that now and kicked off build again.

**Comment by hannes-ucsc** [comment]
After retry, sandbox build still fails in IT stage, but for a different, more benign looking reason:

https://gitlab.dev.explore.data.humancellatlas.org/azul/azul/-/jobs/5688

**Comment by danielsotirhos** [comment]
The traceback in the IT failure message mentions receiving a 404 on a request to the `/repository/files` endpoint:

```
 Traceback (most recent call last):
   File "/builds/azul/azul/test/azul_test_case.py", line 41, in wrapped
     return method(*args, **kwargs)
   File "/builds/azul/azul/test/integration_test.py", line 140, in test
     self._test_indexing()
   File "/builds/azul/azul/test/integration_test.py", line 160, in _test_indexing
     self._check_bundles_are_indexed(self.test_name, 'files')
   File "/builds/azul/azul/test/integration_test.py", line 342, in _check_bundles_are_indexed
     hits = self._get_entities_by_project(entity_type, test_name)
   File "/builds/azul/azul/test/integration_test.py", line 390, in _get_entities_by_project
     response.raise_for_status()
   File "/build/.venv/lib/python3.6/site-packages/requests/models.py", line 940, in raise_for_status
     raise HTTPError(http_error_msg, response=self)
 requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://service.sandbox.dev.explore.data.humancellatlas.org/repository/files?filters=%7B%22project%22%3A+%7B%22is%22%3A+%5B%22integration-test_16cbe588-3f8d-426f-a00d-fa6f1c167027_a0%22%5D%7D%7D&size=100
```

However from the corresponding lambda logs it appears that the request was received and successful 200 response was sent back.

[logs-insights-results.csv.txt](https://github.com/DataBiosphere/azul/files/4371873/logs-insights-results.csv.txt)

Unsure yet why this 200 response was not received.

**Comment by danielsotirhos** [comment]
A re-run of the Integration Test on `sandbox` successfully completed. https://gitlab.dev.explore.data.humancellatlas.org/azul/azul/-/jobs/5689

Current working theory for the previous failure of IT is due to a race condition caused when the following sequence of events was performed:
- IT run on sandbox https://gitlab.dev.explore.data.humancellatlas.org/azul/azul/-/jobs/5684 and failed due to the indexes not being purged
- `make delete` was run for the sandbox indexes
- IT run on sandbox again https://gitlab.dev.explore.data.humancellatlas.org/azul/azul/-/jobs/5688 and failed due to 404 response from https://service.sandbox.dev.explore.data.humancellatlas.org/repository/files

Completing the timeline of events:
- Investigation into failure, request and response tracked down in Cloudwatch
- IT run locally against personal deployment and completed successfully.
- IT re-run on sandbox and completed successfully.

**Pull request merged**
