### PR TITLE
Promotion 2023-01-25 (#4928)

### LINKED ISSUE #4928: Promotion 2023-01-25
- [ ] Security design review completed; the Resolution of this issue does **not** …
  - [ ] … affect authentication; for example:
    - OAuth 2.0 with the application (API or Swagger UI)
    - Authentication of developers with Google Cloud APIs
    - Authentication of developers with AWS APIs
    - Authentication with a GitLab instance in the system
    - Password and 2FA authentication with GitHub
    - API access token authentication with GitHub
    - Authentication with 
  - [ ] … affect the permissions of internal users like access to
    - Cloud resources on AWS and GCP
    - GitLab repositories, projects and groups, administration
    - an EC2 instance via SSH
    - GitHub issues, pull requests, commits, commit statuses, wikis, repositories, organizations
  - [ ] … affect the permissions of external users like access to
    - TDR snapshots
  - [ ] … affect permissions of service or bot accounts
    - Cloud resources on AWS and GCP
  - [ ] … affect audit logging in the system, like
    - adding, removing or changing a log message that represents an auditable event
    - changing the routing of log messages through the system
  - [ ] … affect monitoring of the system
  - [ ] … introduce a new software dependency like
    - Python packages on PYPI
    - Command-line utilities
    - Docker images
    - Terraform providers
  - [ ] … add an interface that exposes sensitive or confidential data at the security boundary
  - [ ] … affect the encryption of data at rest
  - [ ] … require persistence of sensitive or confidential data that might require encryption at rest
  - [ ] … require unencrypted transmission of data within the security boundary
  - [ ] … affect the network security layer; for example by 
    - modifying, adding or removing firewall rules
    - modifying, adding or removing security groups
    - changing or adding a port a service, proxy or load balancer listens on
- [ ] Documentation on any unchecked boxes is provided in comments below

### PR DESCRIPTION
**Pull request by dsotirho-ucsc**
Connected issue: #4928

### Author

- [x] Target branch is `prod`
- [x] Name of PR branch matches `promotions/yyyy-mm-dd`
- [x] Title of connected issue matches `Promotion yyyy-mm-dd`
- [x] PR title references the connected issue
- [x] PR title starts with title of connected issue
- [x] PR is connected to issue via ZenHub
- [x] PR description links to connected issue

### Author (reindex, API changes)

- [x] Added `reindex` label to PR <sub>or this PR does not require reindexing</sub> 
- [x] Added `API` label to connected issue <sub>or this PR does not modify the Azul service API</sub> (See [comment](https://github.com/DataBiosphere/azul/pull/4929#issuecomment-1404271621))

### Author (upgrading)

- [x] Added `upgrade` label to PR <sub>or this PR does not require upgrading</sub> (See [comment](https://github.com/DataBiosphere/azul/pull/4929#issuecomment-1404311290))

### Primary reviewer (after approval)

- [x] Actually approved the PR
- [x] Labeled PR as `no sandbox`
- [x] Moved ticket to *Approved* column
- [x] Assigned PR to current operator

### Operator (before pushing merge the commit)

- [x] Pushed PR branch to GitHub
- [x] Added PR reference to merge commit title
- [x] Collected commit title tags in merge commit title
- [x] Pushed merge commit to GitHub

### Operator (after pushing the merge commit)

- [x] Pushed merge commit to GitLab `prod`
- [x] Build passes on GitLab `prod` (See [comment](https://github.com/DataBiosphere/azul/pull/4929#issuecomment-1406927560))
- [x] Reviewed build logs for anomalies on GitLab `prod`
- [x] Deleted PR branch from GitHub
- [x] Deleted PR branch from GitLab `prod`
- [x] Moved connected issue to *Merged prod* column on ZenHub
- [x] Moved promoted issues from *Merged* to *Merged prod* column on ZenHub
- [x] Moved promoted issues from *dev* to *prod* column on ZenHub

### Operator (reindex)

- [x] Deleted unreferenced indices in `prod` <sub>or this PR does not remove catalogs or otherwise causes unreferenced indices </sub>
- [x] Started reindex in `prod` <sub>or this PR does not require reindexing</sub> (See [comment](https://github.com/DataBiosphere/azul/pull/4929#pullrequestreview-1270305059))
- [x] Checked for and triaged indexing failures in `prod` <sub>or this PR does not require reindexing</sub>
- [x] Emptied fail queues in `prod` deployment <sub>or this PR does not require reindexing</sub>

### Operator

- [x] Unassigned PR

## Shorthand for review comments

- `L` line is too long
- `W` line wrapping is wrong
- `Q` bad quotes
- `F` other formatting problem

### CODE REVIEW

**Comment by dsotirho-ucsc** [comment]
This promotion contains one PR that modifies the API, however the changes are specific only to `anvildev` so the `API` label is not needed for this `prod` promotion PR.

**Comment by dsotirho-ucsc** [comment]
There is one PR in this promotion that requires an `upgrade` step, however it is specific to `dev.shared` so there is no `upgrade` label needed for this promotion to `prod`.

**Review by hannes-ucsc — COMMENTED** [review]
Note blocked vs connected above. Hence the bump.

This should wait until #4921 lands, after which it should get the `reindex` label but only the lm3 catalog needs to be reindexed.

**Review by hannes-ucsc — CHANGES_REQUESTED** [review]
I had to back out #4921 due to https://github.com/DataBiosphere/azul/issues/4921#issuecomment-1404496080. Please adjust this PR accordingly.

**Comment by dsotirho-ucsc** [comment]
> Please adjust this PR accordingly.

I have reset this branch back to original commit chosen for this release, commit c8e6a9f8, just prior to `lm3` being merged into `develop`.

**Review by hannes-ucsc — APPROVED** [review]

**Comment by dsotirho-ucsc** [comment]
Updated PR branch to e93cc9dd4147fa3a85db606f474353ab502dc9b3 to include the (corrected) lm3 catalog.

**Review by hannes-ucsc — APPROVED** [review]

**Comment by dsotirho-ucsc** [comment]
The build for this PR failed during IT due to https://github.com/DataBiosphere/azul/issues/4934. Hotfix https://github.com/DataBiosphere/azul/pull/4935 addresses the issue.

**Comment by hannes-ucsc** [comment]
Yet another CL mistake.

**Pull request merged**
