### PR TITLE
Upgrade dependencies 2024-01-08 (#5831)

### LINKED ISSUE #5831: Upgrade dependencies 2024-01-08
- [x] Update [PyCharm image](https://github.com/DataBiosphere/azul-docker-pycharm)
  - [x] Bump [base image](https://hub.docker.com/_/debian/tags?name=bullseye) tag (only same Debian release), if possible
  - [x] Bump upstream version, if possible
  - [x] Bump internal version
  - [x] Build and test new image locally with Azul's `make format`
  - [x] Remove unused dependencies with high or critical CVEs
  - [x] Push commit to GitHub (directly to master branch, no PR needed)
  - [x] GH Action workflow succeeded
  - [x] Image is available on [DockerHub](https://hub.docker.com/repository/docker/ucscgi/azul-pycharm) 
- [x] Update [Elasticsearch image](https://github.com/DataBiosphere/azul-docker-elasticsearch)
  - [x] Bump [base image](https://hub.docker.com/_/elasticsearch/tags) tag (only minor and patch versions), if possible
  - [x] Bump internal version 
  - [x] Build and test new image locally with Azul's `make test`
  - [x] Remove unused dependencies with high or critical CVEs
  - [x] Push commit to GitHub (directly to master branch, no PR needed)
  - [x] GH Action workflow succeeded
  - [x] Image is available on [DockerHub](https://hub.docker.com/repository/docker/ucscgi/azul-elasticsearch) 
- [x] Create Azul PR, connected to this issue, with … 
  - [x] … changes to `requirements*.txt` from open Dependabot PRs, one commit per PR
  - [x] … update to [Python](https://hub.docker.com/_/python/tags) (only patch versions) <sub>or no update available</sub>
  - [x] … update to [Terraform](https://hub.docker.com/r/hashicorp/terraform/tags) (only patch versions) <sub>or no update available</sub>
  - [x] … new [PyCharm image](https://hub.docker.com/repository/docker/ucscgi/azul-pycharm)
  - [x] … new [Elasticsearch image](https://hub.docker.com/repository/docker/ucscgi/azul-elasticsearch)
  - [x] … update to [Docker images](https://hub.docker.com/_/docker/tags) (only minor and patch versions) <sub>or no update available</sub>
  - [x] … update to [GitLab](https://hub.docker.com/r/gitlab/gitlab-ce/tags) & [GitLab runner images](https://hub.docker.com/r/gitlab/gitlab-runner/tags) <sub>or no update available</sub>
  - [x] … update to [ClamAV image](https://hub.docker.com/r/clamav/clamav/tags) <sub>or no update available</sub>
  - [x] … update to [GitLab AMI](https://github.com/DataBiosphere/azul/blob/develop/OPERATOR.rst#updating-the-ami-for-gitlab-instances) <sub>or no update available</sub>
- [ ] Delete obsolete image tags from DockerHub (but consider that `prod` may not use the latest image) … 
  - [ ] … for [PyCharm image](https://hub.docker.com/repository/docker/ucscgi/azul-pycharm)
  - [ ] … for [Elasticsearch image](https://hub.docker.com/repository/docker/ucscgi/azul-elasticsearch)
- [x] Created tickets for any deferred updates to …
  - [x] … to next major or minor Python version <sub>or such ticket already exists</sub>
  - [x] … to next major Docker version <sub>or such ticket already exists</sub>
  - [x] … to next major or minor Terraform version <sub>or such ticket already exists</sub>

### PR DESCRIPTION
**Pull request by achave11-ucsc**
Connected issue: #5831 

### Author

- [x] Target branch is `develop`
- [x] Name of PR branch matches `upgrades/yyyy-mm-dd`
- [x] On ZenHub, PR is connected to the upgrade issue it resolves
- [x] PR title matches `Upgrade dependencies yyyy-mm-dd`
- [x] PR title references the connected issue

### Author (upgrading deployments)

- [x] Added `upgrade` label to PR <sub>or this PR does not require upgrading deployments</sub>

### Author (before every review)

- [x] Rebased PR branch on `develop`, squashed old fixups
- [x] Ran `make requirements_update` <sub>or this PR does not touch requirements*.txt, common.mk, Makefile and Dockerfile</sub>
- [x] Added `R` tag to commit title <sub>or this PR does not touch requirements*.txt</sub>
- [x] Added `reqs` label to PR <sub>or this PR does not touch requirements*.txt</sub>
- [x] Selected `dev.shared` and ran `CI_COMMIT_REF_NAME=develop make -C terraform/shared apply_keep_unused` <sub>or this PR does not change any Docker image versions</sub>
- [x] Selected `anvildev.shared` and ran `CI_COMMIT_REF_NAME=develop make -C terraform/shared apply_keep_unused` <sub>or this PR does not change any Docker image versions</sub>
- [x] Selected `anvilprod.shared` and ran `CI_COMMIT_REF_NAME=develop make -C terraform/shared apply_keep_unused` <sub>or this PR does not change any Docker image versions</sub>
- [x] `make integration_test` passes in personal deployment <sub>or this PR does not touch functionality that could break the IT</sub>

### System administrator (after approval)

- [x] Actually approved the PR
- [x] Labeled connected issue as `no demo`
- [x] PR title is appropriate as title of merge commit
- [x] Moved ticket to *Approved* column
- [x] PR is assigned to current operator

### Operator (before pushing merge the commit)

- [x] Squashed PR branch and rebased onto `develop`
- [x] Sanity-checked history
- [x] Pushed PR branch to GitHub
- [x] Selected `dev.gitlab` and ran `CI_COMMIT_REF_NAME=develop make -C terraform/gitlab apply` <sub>or this PR does not include any changes to files in terraform/gitlab</sub>
- [x] Selected `anvildev.gitlab` and ran `CI_COMMIT_REF_NAME=develop make -C terraform/gitlab apply` <sub>or this PR does not include any changes to files in terraform/gitlab</sub>
- [x] Selected `anvilprod.gitlab` and ran `CI_COMMIT_REF_NAME=develop make -C terraform/gitlab apply` <sub>or this PR does not include any changes to files in terraform/gitlab</sub>
- [x] Assigned system administrator <sub>or this PR does not include any changes to files in terraform/gitlab</sub>
- [x] Checked the items in the next section <sub>or this PR includes changes to files in terraform/gitlab</sub>

### System administrator

- [x] Background migrations for `dev.gitlab` are complete <sub>or this PR does not include any changes to files in terraform/gitlab</sub>
- [x] Background migrations for `anvildev.gitlab` are complete <sub>or this PR does not include any changes to files in terraform/gitlab</sub>
- [x] Background migrations for `anvilprod.gitlab` are complete <sub>or this PR does not include any changes to files in terraform/gitlab</sub>
- [x] PR is assigned to operator

### Operator (before pushing merge the commit)

- [x] Selected `dev.gitlab` and ran `make -C terraform/gitlab/runner` <sub>or this PR does not change `azul_docker_version`</sub>
- [x] Selected `anvildev.gitlab` and ran `make -C terraform/gitlab/runner` <sub>or this PR does not change `azul_docker_version`</sub>
- [x] Selected `anvilprod.gitlab` and ran `make -C terraform/gitlab/runner` <sub>or this PR does not change `azul_docker_version`</sub>
- [x] Added `sandbox` label
- [x] Pushed PR branch to GitLab `dev`
- [x] Pushed PR branch to GitLab `anvildev`
- [x] Pushed PR branch to GitLab `anvilprod`
- [x] Build passes in `sandbox` deployment
- [x] Build passes in `anvilbox` deployment
- [x] Build passes in `hammerbox` deployment
- [x] Reviewed build logs for anomalies in `sandbox` deployment
- [x] Reviewed build logs for anomalies in `anvilbox` deployment
- [x] Reviewed build logs for anomalies in `hammerbox` deployment
- [x] Title of merge commit starts with title from this PR
- [x] Added PR reference to merge commit title
- [x] Collected commit title tags in merge commit title <sub>but exclude any `p` tags</sub>
- [x] Moved connected issue to Merged column in ZenHub
- [x] Pushed merge commit to GitHub

### Operator (after pushing the merge commit)

- [x] Pushed merge commit to GitLab `dev`
- [x] Pushed merge commit to GitLab `anvildev`
- [x] Pushed merge commit to GitLab `anvilprod`
- [x] Build passes on GitLab `dev`
- [x] Reviewed build logs for anomalies on GitLab `dev`
- [x] Build passes on GitLab `anvildev`
- [x] Reviewed build logs for anomalies on GitLab `anvildev`
- [x] Build passes on GitLab `anvilprod`
- [x] Reviewed build logs for anomalies on GitLab `anvilprod`
- [x] Selected `dev.shared` and ran `make -C terraform/shared apply` <sub>or this PR does not change any Docker image versions</sub>
- [x] Selected `anvildev.shared` and ran `make -C terraform/shared apply` <sub>or this PR does not change any Docker image versions</sub>
- [x] Selected `anvilprod.shared` and ran `make -C terraform/shared apply` <sub>or this PR does not change any Docker image versions</sub>
- [x] Deleted PR branch from GitHub
- [x] Deleted PR branch from GitLab `dev`
- [x] Deleted PR branch from GitLab `anvildev`
- [x] Deleted PR branch from GitLab `anvilprod`

### Operator

- [x] Ran `script/export_inspector_findings.py` against `anvilprod`, imported results to [Google Sheet](https://docs.google.com/spreadsheets/d/1RWF7g5wRKWPGovLw4jpJGX_XMi8aWLXLOvvE5rxqgH8) and posted screenshot of relevant<sup>1</sup> findings as a comment on the connected issue.
- [x] PR is assigned to system administrator

<sup>1</sup>A relevant finding is a high or critical vulnerability in an image
that is used within the security boundary. Images not used within the boundary
are tracked in `azul.docker_images` under a key starting with `_`.

### System administrator

- [x] No currently reported vulnerability requires immediate attention
- [x] PR is assigned to no one

## Shorthand for review comments

- `L` line is too long
- `W` line wrapping is wrong
- `Q` bad quotes
- `F` other formatting problem

### CODE REVIEW

**Comment by achave11-ucsc** [comment]
@hannes-ucsc, note that I've slightly parted from convention and I've added a commit like `… (PR fix #5838)` using "fix" as a keyword with the intend of not having Dependabot deactivate due to Bot inactivity, more info available in https://github.blog/changelog/2023-01-12-dependabot-pull-requests-pause-for-inactivity/. Let me know if this keyword should be dropped.

**Review by hannes-ucsc — CHANGES_REQUESTED** [review]
See issue CL

**Comment by hannes-ucsc** [comment]
> Let me know if this keyword should be dropped.

Yes, please. I don't think the comment will prevent the pause and I don't think we should proactively try to prevent it. We'll fix when/if it happens.

**Review by hannes-ucsc — DISMISSED** [review]

**Comment by hannes-ucsc** [comment]
Note that since you already did the first phase of the `shared` deployment on this PR, you can't do any other PRs that require redeploying `shared`, be it single- or dual-phase, until the second phase of this PR is done. If you already did another PR of that sort, you will have to repeat the first phase for this PR, after rebasing it.

**Review by hannes-ucsc — APPROVED** [review]

**Comment by achave11-ucsc** [comment]
Inspector exported report has been added to issue, https://github.com/DataBiosphere/azul/issues/5831#issuecomment-1899069169.

**Pull request merged**
