### PR TITLE
Split polymorphic 'protocols' inner entity (#2043)

### PR DESCRIPTION
**Pull request by danielsotirhos**

### CODE REVIEW

**Comment by danielsotirhos** [comment]
Note that although `protocols` inner entities are indexed separately based on their type (analysis_protocols, imaging_protocols, library_preparation_protocols, sequencing_protocols), for the response all the protocol entities are put  into the `protocols` inner entity primarily for backwards compatibility.

**Comment by danielsotirhos** [comment]
This PR for `develop` was mistakenly created before #2080 for `hca/develop`.

**Comment by danielsotirhos** [comment]
Moving PR from #2043 to #2082

**Comment by hannes-ucsc** [comment]
The above diff was from the HCA branch. No bump.

**Comment by danielsotirhos** [comment]
This PR and branch incorrectly references ticket #2043 (for `hca/develop`) instead of #2082 (for `develop`).
Closing PR and will open a new one to connect to #2082.

**Pull request closed without merging**
