### PR TITLE
Describe change management and deployment (#4501)

### LINKED ISSUE #4501: Describe change management and deployment

### PR DESCRIPTION
**Pull request by dsotirho-ucsc**
Connected issues: #4501

### Author

- [x] PR is a draft
- [x] Target branch is `develop`
- [x] Name of PR branch matches `issues/<GitHub handle of author>/<issue#>-<slug>`
- [x] PR title references all connected issues
- [x] PR title matches<sup>1</sup> that of a connected issue <sub>or comment in PR explains why they're different</sub>
- [x] For each connected issue, there is at least one commit whose title references that issue
- [x] PR is connected to all connected issues via ZenHub
- [x] PR description links to connected issues
- [x] Added `partial` label to PR <sub>or this PR completely resolves all connected issues</sub>

<sup>1</sup> when the issue title describes a problem, the corresponding PR
title is `Fix: ` followed by the issue title

### Author (reindex, API changes)

- [x] Added `r` tag to commit title <sub>or this PR does not require reindexing</sub>
- [x] Added `reindex` label to PR <sub>or this PR does not require reindexing</sub>
- [x] Added `a` (compatible changes) or `A` (incompatible ones) tag to commit title <sub>or this PR does not modify the Azul service API</sub>
- [x] Added `API` label to connected issues <sub>or this PR does not modify the Azul service API</sub>

### Author (chains)

- [x] This PR is blocked by previous PR in the chain <sub>or this PR is not chained to another PR</sub>
- [x] Added `base` label to the blocking PR <sub>or this PR is not chained to another PR</sub>
- [x] Added `chained` label to this PR <sub>or this PR is not chained to another PR</sub>

### Author (upgrading)

- [x] Documented upgrading of deployments in UPGRADING.rst <sub>or this PR does not require upgrading</sub>
- [x] Added `u` tag to commit title <sub>or this PR does not require upgrading</sub>
- [x] Added `upgrade` label to PR <sub>or this PR does not require upgrading</sub>

### Author (operator tasks)

- [x] Added checklist items for additional operator tasks <sub>or this PR does not require additional tasks</sub>

### Author (hotfixes)

- [x] Added `F` tag to main commit title <sub>or this PR does not include permanent fix for a temporary hotfix</sub>
- [x] Reverted the temporary hotfixes for any connected issues <sub>or the `prod` branch has no temporary hotfixes for any connected issues</sub>

### Author (before every review)

- [x] Rebased PR branch on `develop`, squashed old fixups
- [x] Ran `make requirements_update` <sub>or this PR does not touch requirements*.txt, common.mk, Makefile and Dockerfile</sub>
- [x] Added `R` tag to commit title <sub>or this PR does not touch requirements*.txt</sub>
- [x] Added `reqs` label to PR <sub>or this PR does not touch requirements*.txt</sub>
- [x] `make integration_test` passes in personal deployment <sub>or this PR does not touch functionality that could break the IT</sub>

### Peer reviewer (after requesting changes)

Uncheck the *Author (before every review)* checklists.

### Peer reviewer (after approval)

- [x] PR is not a draft
- [x] Ticket is in *Review requested* column
- [x] Requested review from primary reviewer
- [x] Assigned PR to primary reviewer

### Primary reviewer (after requesting changes)

Uncheck the *before every review* checklists. Update the `N reviews` label.

### Primary reviewer (after approval)

- [x] Actually approved the PR
- [x] Labeled connected issues as `demo` or `no demo`
- [x] Commented on connected issues about demo expectations <sub>or all connected issues are labeled `no demo`</sub>
- [x] Decided if PR can be labeled `no sandbox`
- [x] PR title is appropriate as title of merge commit
- [x] `N reviews` label is accurate
- [x] Moved ticket to *Approved* column
- [x] Assigned PR to current operator

### Operator (before pushing merge the commit)

- [x] Checked `reindex` label and `r` commit title tag
- [x] Checked that demo expectations are clear <sub>or all connected issues are labeled `no demo`</sub>
- [x] Squashed PR branch and rebased onto `develop`
- [x] Sanity-checked history
- [x] Pushed PR branch to GitHub
- [x] Pushed PR branch to GitLab `dev` and added `sandbox` label <sub>or PR is labeled `no sandbox`</sub>
- [x] Pushed PR branch to GitLab `anvildev` <sub>or PR is labeled `no sandbox`</sub>
- [x] Build passes in `sandbox` deployment <sub>or PR is labeled `no sandbox`</sub>
- [x] Build passes in `anvilbox` deployment <sub>or PR is labeled `no sandbox`</sub>
- [x] Reviewed build logs for anomalies in `sandbox` deployment <sub>or PR is labeled `no sandbox`</sub>
- [x] Reviewed build logs for anomalies in `anvilbox` deployment <sub>or PR is labeled `no sandbox`</sub>
- [x] Deleted unreferenced indices in `sandbox` <sub>or this PR does not remove catalogs or otherwise causes unreferenced indices </sub>
- [x] Deleted unreferenced indices in `anvilbox` <sub>or this PR does not remove catalogs or otherwise causes unreferenced indices </sub>
- [x] Started reindex in `sandbox` <sub>or this PR does not require reindexing `sandbox`</sub>
- [x] Started reindex in `anvilbox` <sub>or this PR does not require reindexing `sandbox`</sub>
- [x] Checked for failures in `sandbox` <sub>or this PR does not require reindexing `sandbox`</sub>
- [x] Checked for failures in `anvilbox` <sub>or this PR does not require reindexing `sandbox`</sub>
- [x] Added PR reference to merge commit title
- [x] Collected commit title tags in merge commit title
- [x] Moved connected issues to Merged column in ZenHub
- [x] Pushed merge commit to GitHub

### Operator (after pushing the merge commit)

- [x] Shortened the PR chain <sub>or this PR is not labeled `base`</sub>
- [x] Pushed merge commit to GitLab `dev` <sub>or PR is labeled `no sandbox`</sub>
- [x] Pushed merge commit to GitLab `anvildev` <sub>or PR is labeled `no sandbox`</sub>
- [x] Build passes on GitLab `dev`<sup>1</sup>
- [x] Reviewed build logs for anomalies on GitLab `dev`<sup>1</sup>
- [x] Build passes on GitLab `anvildev`<sup>1</sup>
- [x] Reviewed build logs for anomalies on GitLab `anvildev`<sup>1</sup>
- [x] Deleted PR branch from GitHub
- [x] Deleted PR branch from GitLab `dev`
- [x] Deleted PR branch from GitLab `anvildev`

<sup>1</sup> When pushing the merge commit is skipped due to the PR being
labelled `no sandbox`, the next build triggered by a PR whose merge commit *is*
pushed determines this checklist item.

### Operator (reindex)

- [x] Deleted unreferenced indices in `dev` <sub>or this PR does not remove catalogs or otherwise causes unreferenced indices </sub>
- [x] Deleted unreferenced indices in `anvildev` <sub>or this PR does not remove catalogs or otherwise causes unreferenced indices </sub>
- [x] Started reindex in `dev` <sub>or this PR does not require reindexing</sub>
- [x] Started reindex in `anvildev` <sub>or this PR does not require reindexing</sub>
- [x] Checked for and triaged indexing failures in `dev` <sub>or this PR does not require reindexing</sub>
- [x] Checked for and triaged indexing failures in `anvildev` <sub>or this PR does not require reindexing</sub>
- [x] Emptied fail queues in `dev` deployment <sub>or this PR does not require reindexing</sub>
- [x] Emptied fail queues in `anvildev` deployment <sub>or this PR does not require reindexing</sub>

### Operator

- [x] Unassigned PR

## Shorthand for review comments

- `L` line is too long
- `W` line wrapping is wrong
- `Q` bad quotes
- `F` other formatting problem

### CODE REVIEW

**Comment by dsotirho-ucsc** [comment]
This PR adds a reStructuredText version of the `UCSC Azul Data Browser 
Software development policy & procedures` [Google doc](https://docs.google.com/document/d/1pT-3QVY1_NARfIHVLQHFlc3x42QCy92CIJJM1uvuy4U/edit?usp=sharing).

**Review by nadove-ucsc — DISMISSED** [review]

**Review by hannes-ucsc — CHANGES_REQUESTED** [review]
Always two line breaks before a heading, one after. Are you using an editor that wraps lines automatically you are you wrapping by hand?

```diff
Subject: [PATCH] WIP
---
Index: docs/compliance/change_management.rst
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/docs/compliance/change_management.rst b/docs/compliance/change_management.rst
--- a/docs/compliance/change_management.rst	(revision 0d7cf6075f8b2687e7e0f6a88549ebe5e3a066d8)
+++ b/docs/compliance/change_management.rst	(date 1682372039968)
@@ -1,9 +1,7 @@
-UCSC Azul Data Browser
-######################
-
 Software development policy & procedures
 ****************************************
 
+
 Introduction
 ============
 
@@ -12,10 +10,10 @@
 conceptualization, prioritization, implementation, testing, deployment, and
 verification of changes on the production environment. Multiple software
 products and services are utilized during this process including `git`_ for
-version control, `GitHub`_ for issue tracking, pull request (PR) management and
-continuous integration (CI), `Terraform`_ for deployment of infrastructure as
-code (IaC), `GitLab`_ for CI/CD, and the cloud providers `AWS`_ and
-`Google Cloud`_ for cloud resources.
+version control, `GitHub`_ for issue tracking, pull request (PR) management
+and continuous integration (CI), `Terraform`_ for deployment of
+infrastructure as code (IaC), `GitLab`_ for CI/CD, and the cloud providers
+`AWS`_ and `Google Cloud`_ for cloud resources.
 
 .. _git: https://git-scm.com/
 .. _GitHub: https://github.com/
@@ -25,29 +23,30 @@
 .. _Google Cloud: https://cloud.google.com/
 
 During this process of managing changes, several separate `deployments`_ are
-used. The `dev` deployment receives changes that were merged into the `develop`
-branch, and allows verification in a scaled down production-like environment
-prior to changes being merged into the `prod` branch and deployed to the `prod`
-deployment. For the `AnVIL project`_, this setup is duplicated with both an
-`anvildev` and `anvilprod` deployment. The two dev deployments `dev` and
-`anvildev` are updated together from the same `develop` branch, however they
-differ from each other in their deployment configuration which specifies the set
-of TDR snapshots the deployment will index, and which metadata and repository
-plugins the deployment will use. Similar to the dev deployments, the two prod
-deployments `prod` and `anvilprod` are kept in sync with updates from the `prod`
-branch.
+used. The `dev` deployment receives changes that were merged into the
+`develop` branch, and allows verification in a scaled down production-like
+environment prior to changes being merged into the `prod` branch and deployed
+to the `prod` deployment. For the `AnVIL project`_, this setup is duplicated
+with both an `anvildev` and `anvilprod` deployment. The two dev deployments
+`dev` and `anvildev` are updated together from the same `develop` branch,
+however they differ from each other in their deployment configuration which
+specifies the set of TDR snapshots the deployment will index, and which
+metadata and repository plugins the deployment will use. Similar to the dev
+deployments, the two prod deployments `prod` and `anvilprod` are kept in sync
+with updates from the `prod` branch.
 
 .. _deployments: https://docs.google.com/document/d/1Kg0dMZmCw6gtkvabD2jYWPZO2Mx_wsC8BJPKdeKTfg0/edit#bookmark=id.3zefi1arki7p
 .. _AnVIL project: https://anvilproject.org/
 
+
 Issue Management
 ================
 
 All change requests, including requests for new features, changes to existing
-features, or changes that address defects, start as GitHub issues in one of the
-GitHub repositories used by the system. The GitHub issue includes a description
-of the desired change and, if the issue constitutes a defect, the steps needed
-to reproduce it.
+features, or changes that address defects, start as GitHub issues in one of
+the GitHub repositories used by the system. The GitHub issue includes a
+description of the desired change and, if the issue constitutes a defect, the
+steps needed to reproduce it.
 
 The `project manager`_ and `system administrator`_ triage the GitHub issue,
 determine its priority relative to existing issues, and assign it to a developer
@@ -56,6 +55,7 @@
 .. _project manager: https://docs.google.com/document/d/1Kg0dMZmCw6gtkvabD2jYWPZO2Mx_wsC8BJPKdeKTfg0/edit#heading=h.jk936f4i59y8
 .. _system administrator: https://docs.google.com/document/d/1Kg0dMZmCw6gtkvabD2jYWPZO2Mx_wsC8BJPKdeKTfg0/edit#heading=h.o3qbvwbucpqo
 
+
 Code Development & Peer Review
 ==============================
 
@@ -67,191 +67,204 @@
 
 .. _operator: https://docs.google.com/document/d/1Kg0dMZmCw6gtkvabD2jYWPZO2Mx_wsC8BJPKdeKTfg0/edit#heading=h.1rxjx57g24fq
 
-Following the guidance provided in the contribution guide (`CONTRIBUTING.rst`_)
-and project README (`README.md`_), the developer implements the requested change
-in the feature branch and deploys the branch to their personal deployment for
-testing. A developer's personal deployment is similar in configuration to the
-`dev` deployment, with the main difference being the scale of the infrastructure
-(such as the size of the ElasticSearch domain) and the set of snapshots (frozen
-sets of metadata documents) configured to be indexed on each deployment.
+Following the guidance provided in the contribution guide
+(`CONTRIBUTING.rst`_) and project README (`README.md`_), the developer
+implements the requested change in the feature branch and deploys the branch
+to their personal deployment for testing. A developer's personal deployment
+is similar in configuration to the `dev` deployment, with the main difference
+being the scale of the infrastructure(such as the size of the ElasticSearch
+domain) and the set of snapshots (frozen sets of metadata documents)
+configured to be indexed on each deployment.
 
 .. _CONTRIBUTING.rst: https://github.com/DataBiosphere/azul/blob/develop/CONTRIBUTING.rst
 .. _README.md: https://github.com/DataBiosphere/azul/blob/develop/README.md
 
-When the developer’s feature branch is ready, it is pushed to GitHub where a PR
-is created and connected to the respective GitHub issue. GitHub performs CI
-checks against the branch including running unit tests, checking for
+When the developer’s feature branch is ready, it is pushed to GitHub where a
+PR is created and connected to the respective GitHub issue. GitHub performs
+CI checks against the branch including running unit tests, checking for
 vulnerabilities with `CodeQL`_, checking test coverage with `CodeCov`_ &
 `Coveralls`_, and security scanning with `Snyk`_. The unit tests have no
-dependencies on the cloud infrastructure in any deployments within the system.
-If a unit test covers code that relies on a cloud resource, that resource is
-mocked by the test. Only PRs from developers (team members) kick off unit tests.
-This is because running unit tests consumes resources and requires credentials
-for uploading test coverage results to CodeCov & Coveralls.
+dependencies on the cloud infrastructure in any deployments within the
+system. If a unit test covers code that relies on a cloud resource, that
+resource is mocked by the test. Only PRs from developers (team members) kick
+off unit tests. This is because running unit tests consumes resources and
+requires credentials for uploading test coverage results to CodeCov &
+Coveralls.
 
 .. _CodeQL: https://codeql.github.com/
 .. _CodeCov: https://about.codecov.io/
 .. _Coveralls: https://github.com/marketplace/coveralls
 .. _Snyk: https://snyk.io/
 
-The developer then follows the `checklist`_ included in every PR to ensure that
-the PR has been properly set up and is ready for review. When ready, the
-developer requests a review from a peer. If the peer has review feedback and/or
-requests changes, ownership of the PR goes back to the developer for updates and
-the review process repeats.
+The developer then follows the `checklist`_ included in every PR to ensure
+that the PR has been properly set up and is ready for review. When ready, the
+developer requests a review from a peer. If the peer has review feedback
+and/or requests changes, ownership of the PR goes back to the developer for
+updates and the review process repeats.
 
 .. _checklist: https://github.com/DataBiosphere/azul/blob/develop/.github/pull_request_template.md
 
+
 Change Approval
 ===============
 
 Once the PR is approved by the peer, a review is requested from the system
-administrator. If the system administrator has review feedback and/or requests
-changes, ownership of the PR goes back to the developer for updates. After
-completing the updates, the developer requests another review from the system
-administrator and the review process is repeated until the PR is approved. When
-approving a PR, the system administrator decides what procedures (if any) are
-needed to demonstrate the resolution of the issue, adds these demo expectations
-to the GitHub issue (or marks the issue “no demo”), approves the PR, and assigns
-the PR to the operator for further validation and merging the PR's feature
-branch into the `develop` branch.
+administrator. If the system administrator has review feedback and/or
+requests changes, ownership of the PR goes back to the developer for updates.
+After completing the updates, the developer requests another review from the
+system administrator and the review process is repeated until the PR is
+approved. When approving a PR, the system administrator decides what
+procedures (if any) are needed to demonstrate the resolution of the issue,
+adds these demo expectations to the GitHub issue (or marks the issue “no
+demo”), approves the PR, and assigns the PR to the operator for further
+validation and merging the PR's feature branch into the `develop` branch.
+
 
 Deployment to dev environment
 =============================
 
 To facilitate CI/CD to the various deployments, multiple separate GitLab
 instances are used. One GitLab instance is used to manage both the `dev` and
-`sandbox` deployments, and another GitLab instance is used solely for the `prod`
-deployment. This setup is mirrored for the AnVIL project, with one GitLab
-instance to manage both the `anvildev` and `anvilbox` deployments, and another
-GitLab instance for the `anvilprod` deployment.
+`sandbox` deployments, and another GitLab instance is used solely for the
+`prod` deployment. This setup is mirrored for the AnVIL project, with one
+GitLab instance to manage both the `anvildev` and `anvilbox` deployments, and
+another GitLab instance for the `anvilprod` deployment.
 
 The `sandbox` deployment is similar in configuration to the `dev` deployment,
 the main difference being the scale of the infrastructure. The `sandbox` and
 `dev` deployments share the same set of snapshots, although `sandbox` only
 indexes a subset of each snapshot. The operator follows the PR checklist to
-validate the feature branch in the `sandbox` and `anvilbox` deployments prior to
-merging into the `develop` branch. The exception to this is when a PR is labeled
-`no sandbox`, which indicates that the system administrator has deemed it not
-necessary to test the PR in the sandbox, for instance when the change is
-specific only to the `dev` deployment.
+validate the feature branch in the `sandbox` and `anvilbox` deployments prior
+to merging into the `develop` branch. The exception to this is when a PR is
+labeled `no sandbox`, which indicates that the system administrator has
+deemed it not necessary to test the PR in the sandbox, for instance when the
+change is specific only to the `dev` deployment.
 
-This process of testing a PR in the `sandbox` deployment starts with the feature
-branch being rebased on the latest commit in `develop` and the squashing of any
-fixup commits. The operator then pushes the feature branch to GitHub, followed
-by `GitLab dev`_ and `GitLab anvildev`_. On GitLab, the branch is run through a
-CI/CD pipeline to build, test, deploy the branch to the `sandbox` and `anvilbox`
-deployments, and run integration tests against the deployments. The difference
-between unit and integration tests is that unit tests are specific to individual
-components of the system and will mock components that are outside the focus of
-the test, while integration tests follow a holistic approach to verify the
-interconnection between the components of the system as a whole.
+This process of testing a PR in the `sandbox` deployment starts with the
+feature branch being rebased on the latest commit in `develop` and the
+squashing of any fixup commits. The operator then pushes the feature branch
+to GitHub, followed by `GitLab dev`_ and `GitLab anvildev`_. On GitLab, the
+branch is run through a CI/CD pipeline to build, test, deploy the branch to
+the `sandbox` and `anvilbox` deployments, and run integration tests against
+the deployments. The difference between unit and integration tests is that
+unit tests are specific to individual components of the system and will mock
+components that are outside the focus of the test, while integration tests
+follow a holistic approach to verify the interconnection between the
+components of the system as a whole.
 
 .. _GitLab dev: https://gitlab.dev.singlecell.gi.ucsc.edu/
 .. _GitLab anvildev: https://gitlab.anvil.gi.ucsc.edu/
 
 A reindex is performed on the `sandbox` deployment if the feature branch
-includes an update to the set of snapshots indexed by the deployment or changes
-the behavior of the indexer in a way that affects the shape of documents in the
-ElasticSearch index.
+includes an update to the set of snapshots indexed by the deployment or
+changes the behavior of the indexer in a way that affects the shape of
+documents in the ElasticSearch index.
 
-Some PRs require the operator to perform special procedures beyond the standard
-deploy/test/reindex cycle. Common examples of this include deploying to the
-`shared` components (which manage infrastructure shared between deployments in
-the same AWS account, e.g., `dev.shared` and `prod.shared`) and updating the
-GitLab instances. These special procedures are referred to as upgrading
-instructions and are cumulatively documented in `UPGRADING.rst`_.
+Some PRs require the operator to perform special procedures beyond the
+standard deploy/test/reindex cycle. Common examples of this include deploying
+to the `shared` components (which manage infrastructure shared between
+deployments in the same AWS account, e.g., `dev.shared` and `prod.shared`)
+and updating the GitLab instances. These special procedures are referred to
+as upgrading instructions and are cumulatively documented in
+`UPGRADING.rst`_.
 
 .. _UPGRADING.rst: https://github.com/DataBiosphere/azul/blob/develop/UPGRADING.rst
 
-After the CI/CD pipeline in GitLab completes without error, the operator merges
-the feature branch into `develop`. The operator then pushes the updated
-`develop` branch to GitHub, followed by GitLab `dev` and `anvildev`. On GitLab,
-the `develop` branch is run through a CI/CD pipeline again to build, test,
-deploy the merged changes, but this time to the `dev` (or `anvildev`)
-deployment, and run integration tests against that deployment. A reindex is
-performed on the deployment if the feature branch includes an update to the set
-of snapshots indexed by the deployment or changes the behavior of the indexer.
+After the CI/CD pipeline in GitLab completes without error, the operator
+merges the feature branch into `develop`. The operator then pushes the
+updated `develop` branch to GitHub, followed by GitLab `dev` and `anvildev`.
+On GitLab, the `develop` branch is run through a CI/CD pipeline again to
+build, test, deploy the merged changes, but this time to the `dev`
+(or `anvildev`) deployment, and run integration tests against that
+deployment. A reindex is performed on the deployment if the feature branch
+includes an update to the set of snapshots indexed by the deployment or
+changes the behavior of the indexer.
+
 
 Deployment to production environment
 ====================================
 
-Once a week, the system administrator and operator review the recent changes to
-the `develop` branch and decide which changes are ready to be promoted to the
-`prod` and `anvilprod` deployments. The decision as to what changes to include
-in a promotion considers a number of factors: For one, changes should usually
-mature on the develop branch for one week, before they are promoted to `prod`,
-so that they can be validated interactively, and more subtle defects like memory
-leaks have time to emerge. If the changes affect a REST API in a way that
-requires changes to the UI code, a second PR must add those changes to the UI
-component. Only after both PRs have been deployed to `dev`, can they be promoted
-to `prod`. The operator creates a GitHub issue for the promotion, creates a
-branch from the agreed commit in the `develop` branch, pushes the branch to
-GitHub, and creates a promotion PR. The promotion PR contains a `checklist`__ of
-tasks for the operator to complete to ensure the PR is properly set up and
-ready for review. The operator requests a review from the system administrator,
-and after approval the PR is assigned back to the operator.
+Once a week, the system administrator and operator review the recent changes
+to the `develop` branch and decide which changes are ready to be promoted to
+the `prod` and `anvilprod` deployments. The decision as to what changes to
+include in a promotion considers a number of factors: For one, changes should
+usually mature on the develop branch for one week, before they are promoted
+to `prod`, so that they can be validated interactively, and more subtle
+defects like memory leaks have time to emerge. If the changes affect a REST
+API in a way that requires changes to the UI code, a second PR must add those
+changes to the UI component. Only after both PRs have been deployed to `dev`,
+can they be promoted to `prod`. The operator creates a GitHub issue for the
+promotion, creates a branch from the agreed commit in the `develop` branch,
+pushes the branch to GitHub, and creates a promotion PR. The promotion PR
+contains a `checklist`__ of tasks for the operator to complete to ensure the
+PR is properly set up and ready for review. The operator requests a review
+from the system administrator, and after approval the PR is assigned back to
+the operator.
 
 .. __: https://github.com/DataBiosphere/azul/blob/develop/.github/PULL_REQUEST_TEMPLATE/promotion.md
 
 At this time the operator announces the promotion via Slack. The promotion
 branch is merged into the `prod` branch, then the updated `prod` branch is
-pushed to GitHub, followed by `GitLab prod`_ and `GitLab anvilprod`_. On GitLab,
-the `prod` branch is run through a CI/CD pipeline to build, test, deploy to the
-`prod` deployment, and run integration tests. A reindex is performed on the
-`prod` deployment if the promotion PR includes an update to the set of snapshots
-indexed by the deployment or changes to the indexer. The operator also performs
-all accumulated upgrading instructions from the changes included in the
-promotion. When the operator finishes with the updates, the promoted GitHub
-issues are marked as merged, and the promotion PR checklist is completed with
-the operator unassigning themself from the promotion PR.
+pushed to GitHub, followed by `GitLab prod`_ and `GitLab anvilprod`_. On
+GitLab, the `prod` branch is run through a CI/CD pipeline to build, test,
+deploy to the `prod` deployment, and run integration tests. A reindex is
+performed on the `prod` deployment if the promotion PR includes an update to
+the set of snapshots indexed by the deployment or changes to the indexer. The
+operator also performs all accumulated upgrading instructions from the
+changes included in the promotion. When the operator finishes with the
+updates, the promoted GitHub issues are marked as merged, and the promotion
+PR checklist is completed with the operator unassigning themself from the
+promotion PR.
 
 .. _GitLab prod: https://gitlab.azul.data.humancellatlas.org/ucsc/azul
 .. _GitLab anvilprod: https://foo
 
-As a final step in the process, a meeting is held once a week for developers to
-demonstrate to the team the changes they’ve implemented. Following the demo
-expectations provided by the system administrator at the time of approval, a
-developer demonstrates the resolution of the GitHub issue to the team, and if
-successful the issue is then closed. Issues marked “no demo” are also closed at
-this time. In the event that a demonstration shows that the issue has not been
-successfully resolved, the original issue will be put back in the developer’s
-sprint for additional work, or a new follow-up issue will be created.
+As a final step in the process, a meeting is held once a week for developers
+to demonstrate to the team the changes they’ve implemented. Following the
+demo expectations provided by the system administrator at the time of
+approval, a developer demonstrates the resolution of the GitHub issue to the
+team, and if successful the issue is then closed. Issues marked “no demo” are
+also closed at this time. In the event that a demonstration shows that the
+issue has not been successfully resolved, the original issue will be put back
+in the developer’s sprint for additional work, or a new follow-up issue will
+be created.
+
 
 Hotfixes and backports
 ======================
 
-An exception to the procedure of change management and deployment detailed above
-is in the case of a `hotfix`_. A hotfix is a change made directly to, or that is
-merged into, the `prod` branch without first being merged into the `develop`
-branch. The system administrator may determine that a hotfix is necessary when a
-defect is discovered following an update to the production environment and there
-is need for urgent remediation. Using the checklist included in the
-`hotfix PR`_, the change is created, reviewed, and deployed to the production
-environment. After a hotfix has been deployed, a `backport PR`_ is created to
-backport the change from the `prod` branch to `develop`.
+An exception to the procedure of change management and deployment detailed
+above is in the case of a `hotfix`_. A hotfix is a change made directly to,
+or that is merged into, the `prod` branch without first being merged into the
+`develop` branch. The system administrator may determine that a hotfix is
+necessary when a defect is discovered following an update to the production
+environment and there is need for urgent remediation. Using the checklist
+included in the `hotfix PR`_, the change is created, reviewed, and deployed
+to the production environment. After a hotfix has been deployed, a `backport
+PR`_ is created to backport the change from the `prod` branch to `develop`.
 
 .. _hotfix: https://github.com/DataBiosphere/azul/blob/develop/CONTRIBUTING.rst#hotfixes
 .. _hotfix PR: https://github.com/DataBiosphere/azul/blob/develop/.github/PULL_REQUEST_TEMPLATE/hotfix.md
 .. _backport PR: https://github.com/DataBiosphere/azul/blob/develop/.github/PULL_REQUEST_TEMPLATE/backport.md
 
+
 GitLab updates
 ==============
 
-The GitLab instances used by the system for CI/CD are self-managed, created from
-`GitLab Docker images`_, and are routinely updated by the operator as security
-release updates and new versions of GitLab become available. When an update to
-GitLab is available, the operator reviews the list of changes in the update with
-the system administrator. If the update is approved, the operator will first
-create a backup of the storage volumes attached to the `dev` and `anvildev`
-GitLab instances. The operator then creates a feature branch to update the
-version of the `GitLab Docker image`_ and/or `GitLab runner image`_ used by the
-system, and deploys this change to the `dev` and `anvildev` deployments. Once
-the new GitLab instances have been created and are active, the same change is
-deployed to update the GitLab instances used by the production (`prod` and
-`anvilprod`) deployments. Once GitLab has been updated on all deployments, a PR
-is created from the feature branch, and the PR checklist is followed to get the
-PR reviewed, approved, and merged.
+The GitLab instances used by the system for CI/CD are self-managed, created
+from `GitLab Docker images`_, and are routinely updated by the operator as
+security release updates and new versions of GitLab become available. When an
+update to GitLab is available, the operator reviews the list of changes in
+the update with the system administrator. If the update is approved, the
+operator will first create a backup of the storage volumes attached to the
+`dev` and `anvildev` GitLab instances. The operator then creates a feature
+branch to update the version of the `GitLab Docker image`_ and/or `GitLab
+runner image`_ used by the system, and deploys this change to the `dev` and
+`anvildev` deployments. Once the new GitLab instances have been created and
+are active, the same change is deployed to update the GitLab instances used
+by the production (`prod` and `anvilprod`) deployments. Once GitLab has been
+updated on all deployments, a PR is created from the feature branch, and the
+PR checklist is followed to get the PR reviewed, approved, and merged.
 
 .. _GitLab Docker images: https://docs.gitlab.com/ee/install/docker.html
 .. _GitLab Docker image: https://hub.docker.com/r/gitlab/gitlab-ce/tags
```

**Comment by dsotirho-ucsc** [comment]
> Are you using an editor that wraps lines automatically you are you wrapping by hand?

Was wrapped by hand using the visual guide at column 80.

**Review by hannes-ucsc — DISMISSED** [review]
You shouldn't wrap manually. I use an editor (SublimeText with the WrapPlus package installed) to automate this. I'm sure TextMate can also wrap automatically. The diff in my previous review was wrapped with the wrong settings but you still had only one line before headings and I found a couple more bugs just now, so I'll leave the review count where it is.

**Review by hannes-ucsc — APPROVED** [review]

**Pull request merged**
