### PR TITLE
Use ESClientFactory.get in ElasticsearchTestCase

### PR DESCRIPTION
**Pull request by hannes-ucsc**
Continued from #254.

@shiroyuki, I had originally merged your PR but then realized that it created considerable conflicts for one of @achave11's PRs. His PR included an older reverted commit by @mpanik and fix for a regression bug introduced by that older commit. Since it was @achave11 who fixed someone else's bug, I didn't want to further penalize him with the conflict resolution. The bad new is that the conflict resolution is now back in your court.

### CODE REVIEW

**Comment by hannes-ucsc** [comment]
Also, could you please rebase onto latest develop?

**Comment by shiroyuki** [comment]
Understood. I will take care of that.

**Comment by shiroyuki** [comment]
@hannes-ucsc I have rebased `gh176` with `origin/develop`. However, I notice that there is a failed test.

```
======================================================================
ERROR: test_index_correctness (indexer.test_hca_indexer.TestHCAIndexer)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/jnopporn/Projects/dnastack/azul/test/indexer/test_hca_indexer.py", line 75, in test_index_correctness
    self._get_es_results(check_bundle_correctness)
  File "/Users/jnopporn/Projects/dnastack/azul/src/azul/__init__.py", line 219, in call
    return func(*args, **kwargs)
  File "/Users/jnopporn/Projects/dnastack/azul/test/indexer/test_hca_indexer.py", line 50, in _get_es_results
    assert_func(es_results)
  File "/Users/jnopporn/Projects/dnastack/azul/test/indexer/test_hca_indexer.py", line 69, in check_bundle_correctness
    with open(os.path.join(data_prefix, f'aee55415-d128-4b30-9644-e6b2742fa32b.{index_name}.results.json'), 'r') as fp:
FileNotFoundError: [Errno 2] No such file or directory: '/Users/jnopporn/Projects/dnastack/azul/test/indexer/data/aee55415-d128-4b30-9644-e6b2742fa32b.azul_files_jyo.results.json'

----------------------------------------------------------------------
```

Should I investigate this failed test with @achave11?

**Comment by achave11** [comment]
Hey @shiroyuki it is interesting that I am also getting the same issue locally when I ran `make test`,
nonetheless they pass on travis. @hannes-ucsc it might be something worth investigating. Does it have to do with the new deployment?

**Comment by hannes-ucsc** [comment]
The test issue raised first by @shiroyuki here, and then @achave11 here was fixed by @alex-hancock here: https://github.com/DataBiosphere/azul/pull/275

**Pull request merged**
