### PR TITLE
Allow null values in PFBs (#2462)

### LINKED ISSUE #2462: Allow null values in PFBs
Remove the work around for #2370 when https://broadworkbench.atlassian.net/browse/AS-521 is fixed.

### LINKED ISSUE #5469: PFB Handover fails in LungMap catalog
image

- [ ] Security design review completed; the Resolution of this issue does **not** …
  - [ ] … affect authentication; for example:
    - OAuth 2.0 with the application (API or Swagger UI)
    - Authentication of developers with Google Cloud APIs
    - Authentication of developers with AWS APIs
    - Authentication with a GitLab instance in the system
    - Password and 2FA authentication with GitHub
    - API access token authentication with GitHub
    - Authentication with 
  - [ ] … affect the permissions of internal users like access to
    - Cloud resources on AWS and GCP
    - GitLab repositories, projects and groups, administration
    - an EC2 instance via SSH
    - GitHub issues, pull requests, commits, commit statuses, wikis, repositories, organizations
  - [ ] … affect the permissions of external users like access to
    - TDR snapshots
  - [ ] … affect permissions of service or bot accounts
    - Cloud resources on AWS and GCP
  - [ ] … affect audit logging in the system, like
    - adding, removing or changing a log message that represents an auditable event
    - changing the routing of log messages through the system
  - [ ] … affect monitoring of the system
  - [ ] … introduce a new software dependency like
    - Python packages on PYPI
    - Command-line utilities
    - Docker images
    - Terraform providers
  - [ ] … add an interface that exposes sensitive or confidential data at the security boundary
  - [ ] … affect the encryption of data at rest
  - [ ] … require persistence of sensitive or confidential data that might require encryption at rest
  - [ ] … require unencrypted transmission of data within the security boundary
  - [ ] … affect the network security layer; for example by 
    - modifying, adding or removing firewall rules
    - modifying, adding or removing security groups
    - changing or adding a port a service, proxy or load balancer listens on
- [ ] Documentation on any unchecked boxes is provided in comments below

### PR DESCRIPTION
**Pull request by nadove-ucsc**
Connected issues: #2462 

### Author

- [x] PR is a draft
- [x] Target branch is `develop`
- [x] Name of PR branch matches `issues/<GitHub handle of author>/<issue#>-<slug>`
- [x] PR title references all connected issues
- [x] PR title matches<sup>1</sup> that of a connected issue <sub>or comment in PR explains why they're different</sub>
- [x] For each connected issue, there is at least one commit whose title references that issue
- [x] PR is connected to all connected issues via ZenHub
- [x] PR description links to connected issues
- [x] Added `partial` label to PR <sub>or this PR completely resolves all connected issues</sub>

<sup>1</sup> when the issue title describes a problem, the corresponding PR
title is `Fix: ` followed by the issue title

### Author (reindex, API changes)

- [x] Added `r` tag to commit title <sub>or this PR does not require reindexing</sub>
- [x] Added `reindex` label to PR <sub>or this PR does not require reindexing</sub>
- [x] PR and connected issue are labeled `API` <sub>or this PR does not modify a REST API</sub>
- [x] Added `a` (`A`) tag to commit title for backwards (in)compatible changes <sub>or this PR does not modify a REST API</sub>
- [x] Updated REST API version number in `app.py` <sub>or this PR does not modify a REST API</sub>

### Author (chains)

- [x] This PR is blocked by previous PR in the chain <sub>or this PR is not chained to another PR</sub>
- [x] Added `base` label to the blocking PR <sub>or this PR is not chained to another PR</sub>
- [x] Added `chained` label to this PR <sub>or this PR is not chained to another PR</sub>

### Author (upgrading)

- [x] Documented upgrading of deployments in UPGRADING.rst <sub>or this PR does not require upgrading</sub>
- [x] Added `u` tag to commit title <sub>or this PR does not require upgrading</sub>
- [x] Added `upgrade` label to PR <sub>or this PR does not require upgrading</sub>

### Author (operator tasks)

- [x] Added checklist items for additional operator tasks <sub>or this PR does not require additional tasks</sub>

### Author (hotfixes)

- [x] Added `F` tag to main commit title <sub>or this PR does not include permanent fix for a temporary hotfix</sub>
- [x] Reverted the temporary hotfixes for any connected issues <sub>or the `prod` branch has no temporary hotfixes for any connected issues</sub>

### Author (before every review)

- [x] Rebased PR branch on `develop`, squashed old fixups
- [x] Ran `make requirements_update` <sub>or this PR does not touch requirements*.txt, common.mk, Makefile and Dockerfile</sub>
- [x] Added `R` tag to commit title <sub>or this PR does not touch requirements*.txt</sub>
- [x] Added `reqs` label to PR <sub>or this PR does not touch requirements*.txt</sub>
- [x] `make integration_test` passes in personal deployment <sub>or this PR does not touch functionality that could break the IT</sub>

### Peer reviewer (after requesting changes)

Uncheck the *Author (before every review)* checklists.

### Peer reviewer (after approval)

- [x] PR is not a draft
- [x] Ticket is in *Review requested* column
- [x] Requested review from primary reviewer
- [x] Assigned PR to primary reviewer

### Primary reviewer (after requesting changes)

Uncheck the *before every review* checklists. Update the `N reviews` label.

### Primary reviewer (after approval)

- [x] Actually approved the PR
- [x] Labeled connected issues as `demo` or `no demo`
- [x] Commented on connected issues about demo expectations <sub>or all connected issues are labeled `no demo`</sub>
- [x] Decided if PR can be labeled `no sandbox`
- [x] PR title is appropriate as title of merge commit
- [x] `N reviews` label is accurate
- [x] Moved ticket to *Approved* column
- [x] Assigned PR to current operator

### Operator (before pushing merge the commit)

- [x] Checked `reindex` label and `r` commit title tag
- [x] Checked that demo expectations are clear <sub>or all connected issues are labeled `no demo`</sub>
- [x] PR has checklist items for upgrading instructions <sub>or PR is not labeled `upgrade`</sub>
- [x] Squashed PR branch and rebased onto `develop`
- [x] Sanity-checked history
- [x] Pushed PR branch to GitHub
- [x] Pushed PR branch to GitLab `dev` and added `sandbox` label <sub>or PR is labeled `no sandbox`</sub>
- [x] Pushed PR branch to GitLab `anvildev` <sub>or PR is labeled `no sandbox`</sub>
- [x] Pushed PR branch to GitLab `anvilprod` <sub>or PR is labeled `no sandbox`</sub>
- [x] Build passes in `sandbox` deployment <sub>or PR is labeled `no sandbox`</sub>
- [x] Build passes in `anvilbox` deployment <sub>or PR is labeled `no sandbox`</sub>
- [x] Build passes in `hammerbox` deployment <sub>or PR is labeled `no sandbox`</sub>
- [x] Reviewed build logs for anomalies in `sandbox` deployment <sub>or PR is labeled `no sandbox`</sub>
- [x] Reviewed build logs for anomalies in `anvilbox` deployment <sub>or PR is labeled `no sandbox`</sub>
- [x] Reviewed build logs for anomalies in `hammerbox` deployment <sub>or PR is labeled `no sandbox`</sub>
- [x] Deleted unreferenced indices in `sandbox` <sub>or this PR does not remove catalogs or otherwise causes unreferenced indices </sub>
- [x] Deleted unreferenced indices in `anvilbox` <sub>or this PR does not remove catalogs or otherwise causes unreferenced indices </sub>
- [x] Deleted unreferenced indices in `hammerbox` <sub>or this PR does not remove catalogs or otherwise causes unreferenced indices </sub>
- [x] Started reindex in `sandbox` <sub>or this PR does not require reindexing `sandbox`</sub>
- [x] Started reindex in `anvilbox` <sub>or this PR does not require reindexing `sandbox`</sub>
- [x] Started reindex in `hammerbox` <sub>or this PR does not require reindexing `sandbox`</sub>
- [x] Checked for failures in `sandbox` <sub>or this PR does not require reindexing `sandbox`</sub>
- [x] Checked for failures in `anvilbox` <sub>or this PR does not require reindexing `sandbox`</sub>
- [x] Checked for failures in `hammerbox` <sub>or this PR does not require reindexing `sandbox`</sub>
- [x] Title of merge commit starts with title from this PR
- [x] Added PR reference to merge commit title
- [x] Added commit title tags to merge commit title
- [x] Moved connected issues to Merged column in ZenHub
- [x] Pushed merge commit to GitHub

### Operator (chain shortening)

- [x] Changed the target branch of the blocked PR to `develop` <sub>or this PR is not labeled `base`</sub>
- [x] Removed the `chained` label from the blocked PR <sub>or this PR is not labeled `base`</sub>
- [x] Removed the blocking relationship from the blocked PR <sub>or this PR is not labeled `base`</sub>
- [x] Removed the `base` label from this PR <sub>or this PR is not labeled `base`</sub>

### Operator (after pushing the merge commit)

- [x] Pushed merge commit to GitLab `dev` <sub>or PR is labeled `no sandbox`</sub>
- [x] Pushed merge commit to GitLab `anvildev` <sub>or PR is labeled `no sandbox`</sub>
- [x] Pushed merge commit to GitLab `anvilprod` <sub>or PR is labeled `no sandbox`</sub>
- [x] Build passes on GitLab `dev`<sup>1</sup>
- [x] Reviewed build logs for anomalies on GitLab `dev`<sup>1</sup>
- [x] Build passes on GitLab `anvildev`<sup>1</sup>
- [x] Reviewed build logs for anomalies on GitLab `anvildev`<sup>1</sup>
- [x] Build passes on GitLab `anvilprod`<sup>1</sup>
- [x] Reviewed build logs for anomalies on GitLab `anvilprod`<sup>1</sup>
- [x] Deleted PR branch from GitHub
- [x] Deleted PR branch from GitLab `dev`
- [x] Deleted PR branch from GitLab `anvildev`
- [x] Deleted PR branch from GitLab `anvilprod`

<sup>1</sup> When pushing the merge commit is skipped due to the PR being
labelled `no sandbox`, the next build triggered by a PR whose merge commit *is*
pushed determines this checklist item.

### Operator (reindex)

- [x] Deleted unreferenced indices in `dev` <sub>or this PR does not remove catalogs or otherwise causes unreferenced indices </sub>
- [x] Deleted unreferenced indices in `anvildev` <sub>or this PR does not remove catalogs or otherwise causes unreferenced indices </sub>
- [x] Deleted unreferenced indices in `anvilprod` <sub>or this PR does not remove catalogs or otherwise causes unreferenced indices </sub>
- [x] Started reindex in `dev` <sub>or this PR does not require reindexing</sub>
- [x] Started reindex in `anvildev` <sub>or this PR does not require reindexing</sub>
- [x] Started reindex in `anvilprod` <sub>or this PR does not require reindexing</sub>
- [x] Checked for and triaged indexing failures in `dev` <sub>or this PR does not require reindexing</sub>
- [x] Checked for and triaged indexing failures in `anvildev` <sub>or this PR does not require reindexing</sub>
- [x] Checked for and triaged indexing failures in `anvilprod` <sub>or this PR does not require reindexing</sub>
- [x] Emptied fail queues in `dev` deployment <sub>or this PR does not require reindexing</sub>
- [x] Emptied fail queues in `anvildev` deployment <sub>or this PR does not require reindexing</sub>
- [x] Emptied fail queues in `anvilprod` deployment <sub>or this PR does not require reindexing</sub>

### Operator

- [x] Unassigned PR

## Shorthand for review comments

- `L` line is too long
- `W` line wrapping is wrong
- `Q` bad quotes
- `F` other formatting problem

### CODE REVIEW

**Review by dsotirho-ucsc — APPROVED** [review]
Approved.

**Comment by nadove-ucsc** [comment]
To confirm the successful generation of PFB manifests containing null values, I compared the contents of PFB manifests generated with and without these changes.

https://service.sandbox.dev.singlecell.gi.ucsc.edu/fetch/manifest/files?catalog=dcp3&filters=%7B%0A%20%20%22donorDisease%22%3A%20%7B%0A%20%20%20%20%22is%22%3A%20%5B%0A%20%20%20%20%20%20%22plasma%20cell%20myeloma%22%0A%20%20%20%20%5D%0A%20%20%7D%0A%7D&format=terra.pfb

```
$ diff <(pfb show -i ~/Desktop/dev.avro | jq .) <(pfb show -i ~/Desktop/pr.avro | jq .)
12c12
<       ""
---
>       null
58c58
<       ""
---
>       null
61c61
<       ""
---
>       null
96c96
<       ""
---
>       null
169c169
<       ""
---
>       null
229c229
<       ""
---
>       null
243c243
<       ""
---
>       null
258c258
<     "estimated_cell_count": ""
---
>     "estimated_cell_count": null
281,282c281,282
<     "is_intermediate": "",
<     "file_source": "",
---
>     "is_intermediate": null,
>     "file_source": null,
285,286c285,286
<     "lane_index": "",
<     "matrix_cell_count": ""
---
>     "lane_index": null,
>     "matrix_cell_count": null
342c342
<       ""
---
>       null
388c388
<       ""
---
>       null
391c391
<       ""
---
>       null
426c426
<       ""
---
>       null
505,506c505,506
<     "is_intermediate": "",
<     "file_source": "",
---
>     "is_intermediate": null,
>     "file_source": null,
509,510c509,510
<     "lane_index": "",
<     "matrix_cell_count": ""
---
>     "lane_index": null,
>     "matrix_cell_count": null
624,625c624,625
<     "is_intermediate": "",
<     "file_source": "",
---
>     "is_intermediate": null,
>     "file_source": null,
628,629c628,629
<     "lane_index": "",
<     "matrix_cell_count": ""
---
>     "lane_index": null,
>     "matrix_cell_count": null
685c685
<       ""
---
>       null
731c731
<       ""
---
>       null
734c734
<       ""
---
>       null
769c769
<       ""
---
>       null
842c842
<       ""
---
>       null
878,879c878,879
<     "is_intermediate": "",
<     "file_source": "",
---
>     "is_intermediate": null,
>     "file_source": null,
882,883c882,883
<     "lane_index": "",
<     "matrix_cell_count": ""
---
>     "lane_index": null,
>     "matrix_cell_count": null
997,998c997,998
<     "is_intermediate": "",
<     "file_source": "",
---
>     "is_intermediate": null,
>     "file_source": null,
1001,1002c1001,1002
<     "lane_index": "",
<     "matrix_cell_count": ""
---
>     "lane_index": null,
>     "matrix_cell_count": null
1116,1117c1116,1117
<     "is_intermediate": "",
<     "file_source": "",
---
>     "is_intermediate": null,
>     "file_source": null,
1120,1121c1120,1121
<     "lane_index": "",
<     "matrix_cell_count": ""
---
>     "lane_index": null,
>     "matrix_cell_count": null
1185,1186c1185,1186
<     "is_intermediate": "",
<     "file_source": "",
---
>     "is_intermediate": null,
>     "file_source": null,
1189,1190c1189,1190
<     "lane_index": "",
<     "matrix_cell_count": ""
---
>     "lane_index": null,
>     "matrix_cell_count": null
1304,1305c1304,1305
<     "is_intermediate": "",
<     "file_source": "",
---
>     "is_intermediate": null,
>     "file_source": null,
1308,1309c1308,1309
<     "lane_index": "",
<     "matrix_cell_count": ""
---
>     "lane_index": null,
>     "matrix_cell_count": null
1373,1374c1373,1374
<     "is_intermediate": "",
<     "file_source": "",
---
>     "is_intermediate": null,
>     "file_source": null,
1377,1378c1377,1378
<     "lane_index": "",
<     "matrix_cell_count": ""
---
>     "lane_index": null,
>     "matrix_cell_count": null
1492,1493c1492,1493
<     "is_intermediate": "",
<     "file_source": "",
---
>     "is_intermediate": null,
>     "file_source": null,
1496,1497c1496,1497
<     "lane_index": "",
<     "matrix_cell_count": ""
---
>     "lane_index": null,
>     "matrix_cell_count": null
1561,1562c1561,1562
<     "is_intermediate": "",
<     "file_source": "",
---
>     "is_intermediate": null,
>     "file_source": null,
1565,1566c1565,1566
<     "lane_index": "",
<     "matrix_cell_count": ""
---
>     "lane_index": null,
>     "matrix_cell_count": null
1630,1631c1630,1631
<     "is_intermediate": "",
<     "file_source": "",
---
>     "is_intermediate": null,
>     "file_source": null,
1634,1635c1634,1635
<     "lane_index": "",
<     "matrix_cell_count": ""
---
>     "lane_index": null,
>     "matrix_cell_count": null
1699,1700c1699,1700
<     "is_intermediate": "",
<     "file_source": "",
---
>     "is_intermediate": null,
>     "file_source": null,
1703,1704c1703,1704
<     "lane_index": "",
<     "matrix_cell_count": ""
---
>     "lane_index": null,
>     "matrix_cell_count": null
1818,1819c1818,1819
<     "is_intermediate": "",
<     "file_source": "",
---
>     "is_intermediate": null,
>     "file_source": null,
1822,1823c1822,1823
<     "lane_index": "",
<     "matrix_cell_count": ""
---
>     "lane_index": null,
>     "matrix_cell_count": null
1879c1879
<       ""
---
>       null
1925c1925
<       ""
---
>       null
1928c1928
<       ""
---
>       null
1963c1963
<       ""
---
>       null
2042,2043c2042,2043
<     "is_intermediate": "",
<     "file_source": "",
---
>     "is_intermediate": null,
>     "file_source": null,
2046,2047c2046,2047
<     "lane_index": "",
<     "matrix_cell_count": ""
---
>     "lane_index": null,
>     "matrix_cell_count": null
2111,2112c2111,2112
<     "is_intermediate": "",
<     "file_source": "",
---
>     "is_intermediate": null,
>     "file_source": null,
2115,2116c2115,2116
<     "lane_index": "",
<     "matrix_cell_count": ""
---
>     "lane_index": null,
>     "matrix_cell_count": null
2230,2231c2230,2231
<     "is_intermediate": "",
<     "file_source": "",
---
>     "is_intermediate": null,
>     "file_source": null,
2234,2235c2234,2235
<     "lane_index": "",
<     "matrix_cell_count": ""
---
>     "lane_index": null,
>     "matrix_cell_count": null
2349,2350c2349,2350
<     "is_intermediate": "",
<     "file_source": "",
---
>     "is_intermediate": null,
>     "file_source": null,
2353,2354c2353,2354
<     "lane_index": "",
<     "matrix_cell_count": ""
---
>     "lane_index": null,
>     "matrix_cell_count": null
2468,2469c2468,2469
<     "is_intermediate": "",
<     "file_source": "",
---
>     "is_intermediate": null,
>     "file_source": null,
2472,2473c2472,2473
<     "lane_index": "",
<     "matrix_cell_count": ""
---
>     "lane_index": null,
>     "matrix_cell_count": null
2537,2538c2537,2538
<     "is_intermediate": "",
<     "file_source": "",
---
>     "is_intermediate": null,
>     "file_source": null,
2541,2542c2541,2542
<     "lane_index": "",
<     "matrix_cell_count": ""
---
>     "lane_index": null,
>     "matrix_cell_count": null
2606,2607c2606,2607
<     "is_intermediate": "",
<     "file_source": "",
---
>     "is_intermediate": null,
>     "file_source": null,
2610,2611c2610,2611
<     "lane_index": "",
<     "matrix_cell_count": ""
---
>     "lane_index": null,
>     "matrix_cell_count": null
2675,2676c2675,2676
<     "is_intermediate": "",
<     "file_source": "",
---
>     "is_intermediate": null,
>     "file_source": null,
2679,2680c2679,2680
<     "lane_index": "",
<     "matrix_cell_count": ""
---
>     "lane_index": null,
>     "matrix_cell_count": null
2744,2745c2744,2745
<     "is_intermediate": "",
<     "file_source": "",
---
>     "is_intermediate": null,
>     "file_source": null,
2748,2749c2748,2749
<     "lane_index": "",
<     "matrix_cell_count": ""
---
>     "lane_index": null,
>     "matrix_cell_count": null
2813,2814c2813,2814
<     "is_intermediate": "",
<     "file_source": "",
---
>     "is_intermediate": null,
>     "file_source": null,
2817,2818c2817,2818
<     "lane_index": "",
<     "matrix_cell_count": ""
---
>     "lane_index": null,
>     "matrix_cell_count": null
2882,2883c2882,2883
<     "is_intermediate": "",
<     "file_source": "",
---
>     "is_intermediate": null,
>     "file_source": null,
2886,2887c2886,2887
<     "lane_index": "",
<     "matrix_cell_count": ""
---
>     "lane_index": null,
>     "matrix_cell_count": null
2951,2952c2951,2952
<     "is_intermediate": "",
<     "file_source": "",
---
>     "is_intermediate": null,
>     "file_source": null,
2955,2956c2955,2956
<     "lane_index": "",
<     "matrix_cell_count": ""
---
>     "lane_index": null,
>     "matrix_cell_count": null
```

**Comment by nadove-ucsc** [comment]
To confirm successful handover to Terra using manifests that contain null values, I imported the null-containing manifest generated in the previous step by editing the URL generated by the Data Browser to point to my personal deployment instead of `dev`:
https://bvdp-saturn-dev.appspot.com/#import-data?format=PFB&url=https%3A%2F%2Fservice.nadove.dev.singlecell.gi.ucsc.edu%2Fmanifest%2Ffiles%3Fcatalog%3Ddcp3%26format%3Dterra.pfb%26filters%3D%257B%2522donorDisease%2522%253A%2B%257B%2522is%2522%253A%2B%255B%2522plasma%2Bcell%2Bmyeloma%2522%255D%257D%257D%26objectKey%3Dmanifests%252Fbb25db3a-3cc9-5120-b6df-686e75096b62.c951adc1-60cc-52e3-8fc8-7294e9cf5741.avro

Data import was successful. Null values are displayed as "(0 items)"

image

**Comment by nadove-ucsc** [comment]
Given that the data import was successful, I'm confident that these changes can be merged with minimal risk of disrupting the `dev` deployment.

**Pull request merged**
