### PR TITLE
Split polymorphic 'protocols' inner entity (#2082)

### PR DESCRIPTION
**Pull request by danielsotirhos**
Forward port of #2043 (PR #2080) from `hca/develop` to `develop`

### CODE REVIEW

**Comment by danielsotirhos** [comment]
Investigation appears to be indicating issue #2147 as the cause of the reindex failure.

Reindex job [5397](https://gitlab.dev.singlecell.gi.ucsc.edu/ucsc/azul/-/jobs/5397) started at 12:27pm PDT.

No errors found in queues:
```
(.venv) daniel@Crispin ~/azul.sc $ _select
lrwxr-xr-x  1 daniel  staff  10 Aug 17 13:58 .active -> dev.gitlab

(.venv) daniel@Crispin ~/azul.sc $ python scripts/manage_queues.py list
2020-08-17 13:58:52,136 INFO    MainThread: Listing queues

Queue Name                          Messages Available  Messages In Flight  Messages Delayed 

2020-08-17 13:58:52,162 INFO    MainThread: Found credentials in shared credentials file: ~/.aws/credentials
azul-notifications-dev                      0                   0                  0         
azul-tallies-dev.fifo                       0                   0                  0         
azul-tallies_retry-dev.fifo                 0                   0                  0         
azul-tallies_fail-dev.fifo                  0                   0                  0         
azul-notifications_fail-dev                 0                   0                  0         
```

Cloudwatch Logs show 137 errors between 12:00 and 1:00pm PDT:
- 2 x `[ERROR] ConnectionError: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))`
- 135 x `[ERROR] Forbidden: 403 Exceeded rate limits: too many concurrent queries for this project_and_region.`

cloudwatch-error-logs

**Comment by hannes-ucsc** [comment]
You list the queues from the `dev` deployment, not `sandbox`.

Since then other builds were run in the sandbox but if the ``sandbox` still has no failed messages, it would still support the hypothesis that the failure was benign, just a timeout.

Then again, the 403s from Google have me worried. Could you dig a little deeper? What service produces them, BigQuery or Google Storage? Do we need another ticket? How prevalent are they i.e. what percentage of requests is affected? Are they eventually being retried.

**Comment by danielsotirhos** [comment]
> What service produces [the 403s], BigQuery or Google Storage?

BigQuery. Example:

```
[ERROR] Forbidden: 403 Exceeded rate limits: too many concurrent queries for this project_and_region. For more information, see https://cloud.google.com/bigquery/troubleshooting-errors
(job ID: 09dbfceb-330a-4ae4-9f80-316fb58437b8)
-----Query Job SQL Follows-----
1:
2: SELECT content, version, project_id, BYTE_LENGTH(content) AS content_size, JSON_EXTRACT_SCALAR(content, "$.schema_type") AS content_type
3: FROM dcp1_metadata_no_files.project
4: WHERE project_id = "f83165c5-e2ea-4d15-a5cf-33f3550bffde"
5:
Traceback (most recent call last):
  File "/var/task/app.py", line 112, in new_handler
    return old_handler(self, event, context)
  File "/var/task/chalice/app.py", line 1430, in __call__
    return self.func(event_obj)
  File "/var/task/app.py", line 121, in contribute
    app.index_controller.contribute(event)
  File "/var/task/azul/indexer/index_controller.py", line 145, in contribute
    contributions = self.transform(catalog, notification, delete)
  File "/var/task/azul/indexer/index_controller.py", line 172, in transform
    bundle = self.repository_plugin(catalog).fetch_bundle(bundle_fqid)
  File "/var/task/azul/plugins/repository/tdr/__init__.py", line 101, in fetch_bundle
    bundle = self.emulate_bundle(bundle_fqid)
  File "/var/task/azul/plugins/repository/tdr/__init__.py", line 215, in emulate_bundle
    rows = future.result()
...
  File "/opt/python/google/cloud/bigquery/job.py", line 3196, in result
    super(QueryJob, self).result(retry=retry, timeout=timeout)
  File "/opt/python/google/cloud/bigquery/job.py", line 818, in result
    return super(_AsyncJob, self).result(timeout=timeout)
  File "/opt/python/google/api_core/future/polling.py", line 130, in result
    raise self._exception
```

> Do we need another ticket?

I recommend discussion to see if we could implement a rate limit to keep the number of queries/request under Google's limit.

From https://cloud.google.com/bigquery/troubleshooting-errors:

    rateLimitExceeded: 403

    This error returns if your project exceeds a short-term rate limit by sending too many requests too quickly. For example, see the rate limits for query jobs and rate limits for API requests.

    https://cloud.google.com/bigquery/quotas#query_jobs

    Concurrent rate limit for interactive queries — 100 concurrent queries
    Concurrent rate limit for interactive queries against Bigtable external data sources — 4 concurrent queries

    https://cloud.google.com/bigquery/quotas#api_requests

    API requests per second, per user — 100
    Concurrent API requests, per user: 300


> How prevalent are they i.e. what percentage of requests is affected? Are they eventually being retried?

I am unsure how to determine this with the current logs. I can see this same error occurring quite often in peaks of about 140 times throughout the last two weeks.

cloudwatch-403-errors

**Comment by danielsotirhos** [comment]
Ticket #2189 created to address occurrences of "403 Exceeded rate limits" errors

**Review by hannes-ucsc — APPROVED** [review]

**Comment by hannes-ucsc** [comment]
Need to reindex `dev` still.

**Pull request merged**
