### PR TITLE
Add exception handling to tally aggregation (#1890, #1845)

### PR DESCRIPTION
**Pull request by amarjandu**

### CODE REVIEW

**Comment by hannes-ucsc** [comment]
`Add exception handling to tally aggregattion (#1890) (#1845)`

should be 

`Add exception handling to tally aggregation (#1890, #1845)`

**Comment by amarjandu** [comment]
@hannes-ucsc we can thank Apple and their keyboard issues for that one. >.>

**Comment by hannes-ucsc** [comment]
For demonstration show evidence of the new log message in CloudWatch logs in the `dev` deployment.

**Comment by hannes-ucsc** [comment]
Reindex in progress: https://gitlab.dev.singlecell.gi.ucsc.edu/ucsc/azul/-/jobs/3865

**Pull request merged**
