### PR TITLE
Fix: Non-route lambda handlers in service log hardcoded requestId (#4418)

### PR DESCRIPTION
**Pull request by achave11**
Connected issue: #4418 

### Author

- [x] Target branch is `develop`
- [x] Name of source branch matches `issues/<GitHub handle of author>/<issue#>-<slug>`
- [x] PR title references the connected issue
- [x] PR title matches<sup>1</sup> title of connected issue         <sub>or comment in PR explains why they're different</sub>
- [x] Title of at least one commit references connected issue
- [x] PR is connected to issue via Zenhub 
- [x] PR description links to connected issue
- [x] Added `partial` label to PR                                    <sub>or this PR completely resolves the connected issue</sub>

<sup>1</sup> when the issue title describes a problem, the PR title is `Fix: ` followed by the issue title   

### Author (reindex)

- [x] Added `r` tag to commit title                                 <sub>or this PR does not require reindexing</sub>
- [x] Added `reindex` label to PR                                   <sub>or this PR does not require reindexing</sub>

### Author (chains)

- [x] This PR is blocked by previous PR in the chain               <sub>or this PR is not chained to another PR</sub>
- [x] Added `base` label to the blocking PR                        <sub>or this PR is not chained to another PR</sub>
- [x] Added `chained` label to this PR                             <sub>or this PR is not chained to another PR</sub>

### Author (upgrading)

- [x] Documented upgrading of deployments in UPGRADING.rst          <sub>or this PR does not require upgrading</sub>
- [x] Added `u` tag to commit title                                 <sub>or this PR does not require upgrading</sub>
- [x] Added `upgrade` label to PR                                   <sub>or this PR does not require upgrading</sub>

### Author (operator tasks)

- [x] Added checklist items for additional operator tasks           <sub>or this PR does not require additional tasks</sub>

### Author (hotfixes)

- [x] Added `F` tag to main commit title                            <sub>or this PR does not include permanent fix for a temporary hotfix</sub>
- [x] Reverted the temporary hotfix connected to the issue          <sub>or there is no temporary hotfix for the connected issue on the `prod` branch</sub>

### Author (requirements)

- [x] Ran `make requirements_update`                                <sub>or this PR does not touch requirements*.txt, common.mk, Makefile and Dockerfile</sub>
- [x] Added `R` tag to commit title                                 <sub>or this PR does not touch requirements*.txt</sub>
- [x] Added `reqs` label to PR                                      <sub>or this PR does not touch requirements*.txt</sub>

### Author (rebasing, integration test)

- [x] `make integration_test` passes in personal deployment         <sub>or this PR does not touch functionality that could break the IT</sub>
- [x] Rebased branch on `develop`, squashed old fixups

### Peer reviewer (after requesting changes)

Uncheck the *Author (requirements)* and *Author (rebasing, integration test)* 
checklists.

### Peer reviewer (after approval)

- [x] Ticket is in *Review requested* column
- [x] Requested review from primary reviewer
- [x] Assigned PR to primary reviewer

### Primary reviewer (after requesting changes)

Uncheck the *Author (requirements)* and *Author (rebasing, integration test)* 
checklists. Update the `N reviews` label. 

### Primary reviewer (after approval)

- [x] Actually approved the PR
- [x] Labeled connected issue as `demo` or `no demo`
- [x] Commented on connected issue about demo expectations          <sub>or labelled connected issue as `no demo`</sub>
- [x] Decided if PR can be labeled `no sandbox`
- [x] PR title is appropriate as title of merge commit
- [x] `N reviews` label is accurate
- [x] Moved ticket to *Approved* column
- [x] Assigned PR to current operator

### Operator (before pushing merge the commit)

- [x] Checked `reindex` label and `r` commit title tag
- [x] Checked that demo expectations are clear                      <sub>or connected issue is labeled as `no demo`</sub>
- [x] Rebased and squashed branch
- [x] Sanity-checked history
- [x] Pushed PR branch to GitHub
- [x] Branch pushed to GitLab and added `sandbox` label             <sub>or PR is labeled `no sandbox`</sub>
- [x] Build passed in sandbox                                       <sub>or PR is labeled `no sandbox`</sub>
- [x] Deleted unreferenced indices in `sandbox`                     <sub>or this PR does not remove catalogs or otherwise causes unreferenced indices</sub> 
- [x] Started reindex in `sandbox`                                  <sub>or this PR does not require reindexing `sandbox`</sub>
- [x] Checked for failures in `sandbox`                             <sub>or this PR does not require reindexing `sandbox`</sub>
- [x] Added PR reference to merge commit title
- [x] Collected commit title tags in merge commit title
- [x] Moved connected issue to Merged column
- [x] Pushed merge commit to GitHub

### Operator (after pushing the merge commit)

- [ ] Shortened the PR chain                                        <sub>or this PR is not labeled `base`</sub>
- [ ] Pushed merge commit to GitLab                                 <sub>or PR is labeled `no sandbox`</sub>
- [ ] Deleted PR branch from GitHub and GitLab
- [ ] Build passes on GitLab<sup>1</sup>

<sup>1</sup> When pushing the merge commit is skipped due to the PR being
labelled `no sandbox`, the next build triggered by a PR whose merge commit *is* 
pushed determines this checklist item.

### Operator (reindex) 

- [ ] Deleted unreferenced indices in `dev`                         <sub>or this PR does not remove catalogs or otherwise causes unreferenced indices</sub> 
- [ ] Started reindex in `dev`                                      <sub>or this PR does not require reindexing</sub>
- [ ] Checked for and triaged indexing failures                     <sub>or this PR does not require reindexing</sub>
- [ ] Emptied fail queues in target deployment                      <sub>or this PR does not require reindexing</sub>

### Operator

- [ ] Unassigned PR

## Shorthand for review comments

- `L` line is too long
- `W` line wrapping is wrong
- `Q` bad quotes
- `F` other formatting problem

### CODE REVIEW

**Review by danielsotirhos — APPROVED** [review]
It'd be nice to have a little more context (pun not intended) in the comment, however as is this matches the same work around in `indexer/app.py`.

Approved.

**Review by hannes-ucsc — COMMENTED** [review]
In stand-up yesterday we agreed that you would put in writing your concerns as to why this solution might be inferior, and to request a WIP review. I don't see either.

**Comment by achave11** [comment]
The concern brought up during PL on 01/09 were a non-issue. This were in regard to …
https://github.com/DataBiosphere/azul/blob/696290dec7e0d66368af538c67e65a0cf1399b92/src/azul/logging.py#L22
… specifically for when self.app.lambda_context is None, but the changes in this PR disallows that scenario from happening.

**Review by hannes-ucsc — CHANGES_REQUESTED** [review]
Let's try this instead. The intend is to avoid having to patch in every app.py:

```diff
Index: lambdas/indexer/app.py
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/lambdas/indexer/app.py b/lambdas/indexer/app.py
--- a/lambdas/indexer/app.py	(revision 007a179f817cf01056cc13594475a99f15903e68)
+++ b/lambdas/indexer/app.py	(date 1662160233239)
@@ -110,17 +110,6 @@
     return app.index_controller.handle_notification(catalog, action)
 
 
-# Work around https://github.com/aws/chalice/issues/856
-
-def new_handler(self, event, context):
-    app.lambda_context = context
-    return old_handler(self, event, context)
-
-
-old_handler = chalice.app.EventSourceHandler.__call__
-chalice.app.EventSourceHandler.__call__ = new_handler
-
-
 @app.on_sqs_message(queue=config.notifications_queue_name(), batch_size=1)
 def contribute(event: chalice.app.SQSEvent):
     app.index_controller.contribute(event)
Index: src/azul/chalice.py
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/src/azul/chalice.py b/src/azul/chalice.py
--- a/src/azul/chalice.py	(revision 007a179f817cf01056cc13594475a99f15903e68)
+++ b/src/azul/chalice.py	(date 1662160330119)
@@ -78,6 +78,7 @@
                  app_module_path: str,
                  unit_test: bool = False,
                  spec: Optional[JSON] = None):
+        self._patch_event_source_handler()
         assert app_module_path.endswith('/app.py'), app_module_path
         self.app_module_path = app_module_path
         self.unit_test = unit_test
@@ -94,6 +95,23 @@
         self.register_middleware(self._lambda_context_middleware, 'all')
         self.register_middleware(self._authentication_middleware, 'http')
 
+    def _patch_event_source_handler(self):
+        """
+        Work around https://github.com/aws/chalice/issues/856. That issue has
+        been fixed for a while now but in a way that doesn't help us: it makes
+        the context available in each event object whereas we need the context
+        in the application object.
+        """
+        import chalice.app
+
+        def patched_event_source_handler(self_, event, context):
+            self.lambda_context = context
+            return old_handler(self_, event, context)
+
+        old_handler = chalice.app.EventSourceHandler.__call__
+        if old_handler.__code__ != patched_event_source_handler.__code__:
+            chalice.app.EventSourceHandler.__call__ = patched_event_source_handler
+
     def _logging_middleware(self, event, get_response):
         self._log_request()
         response = get_response(event)
Index: lambdas/service/app.py
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/lambdas/service/app.py b/lambdas/service/app.py
--- a/lambdas/service/app.py	(revision 007a179f817cf01056cc13594475a99f15903e68)
+++ b/lambdas/service/app.py	(date 1662159151677)
@@ -417,19 +417,6 @@
 configure_app_logging(app, log)
 
 
-# Work around https://github.com/aws/chalice/issues/856
-# Some lambda handlers lack convenient access to context,
-# new_handler facilitates usage of lambda context in the app.
-
-def new_handler(self, event, context):
-    app.lambda_context = context
-    return old_handler(self, event, context)
-
-
-old_handler = chalice.app.EventSourceHandler.__call__
-chalice.app.EventSourceHandler.__call__ = new_handler
-
-
 @app.route('/', cors=True)
 def swagger_ui():
     swagger_ui_template = app.load_static_resource('swagger-ui.html.template.mustache')
```

**Review by hannes-ucsc — CHANGES_REQUESTED** [review]
https://github.com/DataBiosphere/azul/pull/4432#pullrequestreview-1095415788 wasn't addressed at all.

**Comment by achave11** [comment]
That was an oversight on my behalf, I accidentally pushed the copy of the branch that didn't have the changes.

**Review by hannes-ucsc — APPROVED** [review]

**Pull request merged**
