### PR TITLE
Return gs url with DRS endpoint (#920)

### PR DESCRIPTION
**Pull request by jessebrennan**
This PR should not be merged until HumanCellAtlas/data-store#2138 has made it to at least staging.

### CODE REVIEW

**Comment by hannes-ucsc** [comment]
@theathorn this is labelled `hold warm` so it should remain assigned to the submitter of the PR.

**Comment by hannes-ucsc** [comment]
@amarjandu could you notify us when `GET /files?directurl=…` lands on DSS staging?

**Comment by amarjandu** [comment]
@hannes-ucsc its merged.

**Comment by hannes-ucsc** [comment]
Thank you, @amarjandu!

**Pull request merged**
