### PR TITLE
Correctly identify dangling supplementary files (#2540)

### PR DESCRIPTION
**Pull request by noah-aviel-dove**
Author (check before every review)

- [x] PR title references issue
- [x] Title of main commit references issue
- [x] PR is linked to Zenhub issue
- [x] Added `DCP/1` label                                   <sub>or this PR does not target an `hca/*` branch</sub>
- [x] Created issue to track porting these changes          <sub>or this PR does not need porting</sub> 
- [x] Added `r` tag to commit title                         <sub>or this PR does not require reindexing</sub>
- [x] Added `reindex` label to PR                           <sub>or this PR does not require reindexing</sub>
- [x] Freebies are blocked on this PR                       <sub>or there are no freebies in this PR</sub>
- [x] Freebies are referenced in commit titles              <sub>or there are no freebies in this PR</sub>
- [x] This PR is blocked by previous PR in chain            <sub>or this PR is not chained to another PR</sub>
- [x] Added `chain` label to the blocking PR                <sub>or this PR is not chained to another PR</sub>
- [x] Ran `make requirements_update`                        <sub>or this PR leaves requirements*.txt, common.mk and Makefile untouched</sub>
- [x] Added `R` tag to commit title                         <sub>or this PR leaves requirements*.txt untouched</sub>
- [x] Added `reqs` label to PR                              <sub>or this PR leaves requirements*.txt untouched</sub>
- [x] Documented upgrading of deployments in UPGRADING.rst  <sub>or this PR does not require upgrading</sub>
- [x] Added `u` tag to commit title                         <sub>or this PR does not require upgrading</sub>
- [x] Added `upgrade` label to PR                           <sub>or this PR does not require upgrading</sub>
- [x] `make integration_test` passes in personal deployment <sub>or this PR does not touch functionality that could break the IT</sub>
- [x] Rebased branch on `develop`

Primary reviewer (before pushing merge commit)

- [x] Checked `reindex` label and `r` commit title tag
- [x] Rebased and squashed branch
- [x] Sanity-checked history
- [x] Build passes in `sandbox`                             <sub>or added `no sandbox` label</sub>
- [x] Reindexed `sandbox`                                   <sub>or this PR does not require reindexing</sub>
- [x] Added PR reference to merge commit
- [x] Moved linked issue to Merged
- [ ] Pushed merge commit to Github

Primary reviewer (after pushing merge commit)

- [ ] Moved freebies to Merged column                       <sub>or there are no freebies in this PR</sub> 
- [ ] Shortened chain                                       <sub>or this PR is not the base of another PR</sub>
- [ ] Verified that `N reviews` labelling is accurate
- [ ] Commented on demo expectations                        <sub>or labeled as `no demo`</sub>
- [ ] Pushed merge commit to Gitlab                         <sub>or this changes can be pushed later, together with another PR</sub>
- [ ] Reindexed `dev`                                       <sub>or this PR does not require reindexing</sub>
- [ ] Deleted PR branch from Github and Gitlab
- [ ] Unassign reviewer from PR

### CODE REVIEW

**Comment by noah-aviel-dove** [comment]
Integration test timed out but the queues DID reach zero moments before the time ran out. Reindex on `hca_dev_20200817_dssPrimaryOnly`, which contains the offending bundle referenced in the ticket (`fac35727-22d4-429e-abc1-b4635767ab90`), was successful. CloudWatch insights is down so I can't 100% verify that no errors occured.

**Review by hannes-ucsc — COMMENTED** [review]
> but reindex completed without timing out

That doesn't mean it succeeded. Did you check for messages in the fail queues?

> Reindex on hca_dev_20200817_dssPrimaryOnly, which contains the offending bundle referenced in the ticket (fac35727-22d4-429e-abc1-b4635767ab90

Were you able to reproduce the issue on a vanilla `develop` against that snapshot?

**Review by hannes-ucsc — CHANGES_REQUESTED** [review]
This is not the time for refactorings. Please remove LinkedEntities, save that for later and open an issue. Undo any unnecessary renames like the one from `category` to `context`. 

Resubmit as a minimal fix that simply addresses the issue at hand, even if that means that certain function signatures get unwieldy.

Also see the questions in my previous comment.

**Comment by noah-aviel-dove** [comment]
> That doesn't mean it succeeded. Did you check for messages in the fail queues?

This was during the CloudWatch blackout so no logs were present.

> > Reindex on hca_dev_20200817_dssPrimaryOnly, which contains the offending bundle referenced in the ticket (fac35727-22d4-429e-abc1-b4635767ab90
> 
> Were you able to reproduce the issue on a vanilla `develop` against that snapshot?

I did not try to do so.

**Comment by noah-aviel-dove** [comment]
New PR: https://github.com/DataBiosphere/azul/pull/2558

**Comment by noah-aviel-dove** [comment]
https://github.com/DataBiosphere/azul/issues/2560

**Comment by hannes-ucsc** [comment]
> > That doesn't mean it succeeded. Did you check for messages in the fail queues?
> 
> This was during the CloudWatch blackout so no logs were present.

That's not an answer to my question.

> New PR: #2558

AFAICT, there is no reason to open yet another PR, Please continue your work on this PR and this branch. I will close the other one. Any evidence you posted on that PR should be posted here.

**Comment by hannes-ucsc** [comment]
> > > That doesn't mean it succeeded. Did you check for messages in the fail queues?
> > 
> > 
> > This was during the CloudWatch blackout so no logs were present.
> 
> That's not an answer to my question.

You may be conflating the fail queues in SQS with the CloudWatch logs.

**Comment by noah-aviel-dove** [comment]
> You may be conflating the fail queues in SQS with the CloudWatch logs.

I was. Unfortunately the queues have been purged since then. But the integration test is no longer timing out so it's not relevent to further progress on the ticket.

**Comment by noah-aviel-dove** [comment]
Copied from closed PR:

Issue reproduced on latest develop for snapshot `hca_dev_20200817_dssPrimaryOnly`:

```
@ingestionTime | 1606853760942
-- | --
@log | 122796619775:/aws/lambda/azul-indexer-nadove-contribute
@logStream | 2020/12/01/[$LATEST]209c19faaeff41e887e394c6255822a4
@message | [ERROR] RequirementError: Dangling inputs not found in any bundle: {'b7f4cbdc-c9f8-40bb-be77-02ccc3d3e387', '8de3f6ef-1b63-4084-b27d-70a1e80aff6f', 'fbd6509b-95b5-4594-93ef-29fa66527315', '8ae0a257-7af4-4ef8-a776-46ccda096633', '38c52a53-4913-463a-8177-0dbee9f138b6', '4f6229a4-198e-4850-88d4-f0dcca0230b1', 'bbe04194-16a5-40ef-875a-148e49a029ec', '429cb13b-e4d8-4bea-9c02-6121c7c050c3'}Traceback (most recent call last):  File "/var/task/app.py", line 112, in new_handler    return old_handler(self, event, context)  File "/var/task/chalice/app.py", line 1459, in __call__    return self.func(event_obj)  File "/var/task/app.py", line 121, in contribute    app.index_controller.contribute(event)  File "/var/task/azul/indexer/index_controller.py", line 145, in contribute    contributions = self.transform(catalog, notification, delete)  File "/var/task/azul/indexer/index_controller.py", line 172, in transform    bundle = self.repository_plugin(catalog).fetch_bundle(bundle_fqid)  File "/var/task/azul/plugins/repository/tdr/__init__.py", line 119, in fetch_bundle    bundle = self.emulate_bundle(bundle_fqid)  File "/var/task/azul/plugins/repository/tdr/__init__.py", line 182, in emulate_bundle    entities, links_jsons = self._load_input_subgraphs(bundle_fqid)  File "/var/task/azul/plugins/repository/tdr/__init__.py", line 233, in _load_input_subgraphs    unprocessed \|= self._find_upstream_bundles(dangling_inputs) - processed  File "/var/task/azul/plugins/repository/tdr/__init__.py", line 362, in _find_upstream_bundles    require(not missing,  File "/var/task/azul/__init__.py", line 1062, in require    reject(not condition, *args, exception=exception)  File "/var/task/azul/__init__.py", line 1077, in reject    raise exception(*args)
```

Integration test fails on hca_dev_20200817_dssPrimaryOnly due to null values in the file_id column. Reindexing subtests all pass.

**Review by hannes-ucsc — APPROVED** [review]

**Comment by hannes-ucsc** [comment]
Counted the creation of a redundant PR as half a bump. There were some minor cosmetic issues in what I just approved. I'll address those and counted that as another half bump.

**Comment by hannes-ucsc** [comment]
IT failure is a repro of #2330. Gonna retry the IT.

**Comment by hannes-ucsc** [comment]
No demo, the effectiveness of the fix will be evident by the absence of failed notifications from the next reindex on prod.

**Comment by hannes-ucsc** [comment]
Won't need to reindex `dev` since dev doesn't have old analysis bundles in any catalog.

**Comment by hannes-ucsc** [comment]
Will need to reindex `prod` once this is promoted there.

**Pull request merged**
