### PR TITLE
Add organ cell count summary (fixes #47)

### LINKED ISSUE #47: Web service API to support per-organ cell counts on Home Page
Portal Home page provides hover-over cell counts for each type of organ represented:

Blood
Bone Marrow
Brain
Esophagus
Heart
Immune
Kidney
Liver
Pancreas
Spleen

┆Issue is synchronized with this [JIRA Story](https://ucsc-cgl.atlassian.net/browse/AZUL-56)
┆Project Name: azul
┆Issue Number: AZUL-56
┆Epic: Data Portal Home Page integration with Browser

### PR DESCRIPTION
**Pull request by jyotheeshwar**

### CODE REVIEW

**Comment by jyotheeshwar** [comment]
Sample output on the `/repository/files/summary` end-point

```
{
fileCount: 14054,
specimenCount: 183,
projectCount: 0,
totalFileSize: 1720374942650,
organCount: 6,
donorCount: 50,
labCount: 6,
totalCellCount: 572209566,
fileTypeSummaries: [ ],
organSummaries: [
{
organType: "lymph node",
countOfDocsWithOrganType: 6548,
totalCellCountByOrgan: 6548
},
{
organType: "tumor",
countOfDocsWithOrganType: 6370,
totalCellCountByOrgan: 6370
},
{
organType: "hematopoietic system",
countOfDocsWithOrganType: 762,
totalCellCountByOrgan: 100596288
},
{
organType: "skin",
countOfDocsWithOrganType: 360,
totalCellCountByOrgan: 360
},
{
organType: "spleen",
countOfDocsWithOrganType: 12,
totalCellCountByOrgan: 471600000
},
{
organType: "brain",
countOfDocsWithOrganType: 2,
totalCellCountByOrgan: 0
}
]
}
```

**Comment by hannes-ucsc** [comment]
And could you also change the commit title to mirror the PR title edit I just did?

**Comment by jyotheeshwar** [comment]
@hannes-ucsc so should the test be checking the summary end-point when it has (bad) filters enabled? And should the tests always test for the error (I can't find a test-case with 2xx status codes under that class)?

**Comment by hannes-ucsc** [comment]
Sorry, that wasn't clear. The test I requested should cover the functionality added by you, i.e. the expected summary response with correct use of the summary endpoint. You probably can't assert the numeric values in the summary, but at least the presence of the summary keys should be asserted.

It's ok if the test uses the ES instance of the currently active deployment.

**Comment by hannes-ucsc** [comment]
test_summary_end_point_bad_filter fails for me. Does `/summary` even take filters?

**Comment by jyotheeshwar** [comment]
@hannes-ucsc I removed the test for the following reason.

`/summary` does take in filters, but it does not fail when you pass it bad values. 

For eg. https://service.dev.explore.data.humancellatlas.org/repository/files/summary?filters%3D%7B%27file%27%3A%7B%27organPart%27%3A%7B%27is%27%3A%5B%27fake-val%27%5D%7D%2C%27bad-facet%27%3A%7B%27is%27%3A%5B%27fake-val%27%5D%7D%7D%7D returns a JSON with 200. Since we're already testing a 200 response in the passing test, the test with incorrect filters seems redundant in light of the above fact. 

We should create a separate ticket to make the `/summary` end-point error out when supplied with bad filter values.

**Comment by hannes-ucsc** [comment]
That makes sense, @jyotheeshwar. Personally, I wouldn't have added a test that I know is going to fail. Or I would have decorated it with `@unittest.expectedFailure` with an explanation if I knew the test was going to be fixed soon.

Please resolve conflicts and request another review here on GH by de- and then reselecting me.

**Comment by jyotheeshwar** [comment]
@hannes-ucsc just adding a comment here too, as Zenhub seems to be a bit confused (it shows up both the previous review, and the newly requested one)

**Comment by hannes-ucsc** [comment]
We really have to stop submitting PRs with tests that don't pass.

**Comment by jyotheeshwar** [comment]
@hannes-ucsc test updated, and verified passing locally on Milan's machine. Requested a re-review

**Pull request merged**
