### PR TITLE
Fix: curl manifest download trashes file on response error (#2833)

### PR DESCRIPTION
**Pull request by danielsotirhos**
Author

- [x] PR title references issue
- [x] Title of main commit references issue
- [x] PR is linked to Zenhub issue

Author (reindex)

- [x] Added `r` tag to commit title                         <sub>or this PR does not require reindexing</sub>
- [x] Added `reindex` label to PR                           <sub>or this PR does not require reindexing</sub>

Author (freebies & chains)

- [x] Freebies are blocked on this PR                       <sub>or there are no freebies in this PR</sub>
- [x] Freebies are referenced in commit titles              <sub>or there are no freebies in this PR</sub>
- [x] This PR is blocked by previous PR in the chain        <sub>or this PR is not chained to another PR</sub>
- [x] Added `chain` label to the blocking PR                <sub>or this PR is not chained to another PR</sub>

Author (upgrading)

- [x] Documented upgrading of deployments in UPGRADING.rst  <sub>or this PR does not require upgrading</sub>
- [x] Added `u` tag to commit title                         <sub>or this PR does not require upgrading</sub>
- [x] Added `upgrade` label to PR                           <sub>or this PR does not require upgrading</sub>

Author (requirements, before every review)

- [x] Ran `make requirements_update`                        <sub>or this PR leaves requirements*.txt, common.mk and Makefile untouched</sub>
- [x] Added `R` tag to commit title                         <sub>or this PR leaves requirements*.txt untouched</sub>
- [x] Added `reqs` label to PR                              <sub>or this PR leaves requirements*.txt untouched</sub>

Author (before every review)

- [x] `make integration_test` passes in personal deployment <sub>or this PR does not touch functionality that could break the IT</sub>
- [x] Rebased branch on `develop`, squashed old fixups

Primary reviewer (after approval)

- [x] Commented on demo expectations                        <sub>or labelled PR as `no demo`</sub>
- [x] Decided if PR can be labeled `no sandbox`
- [x] PR title is appropriate as title of merge commit
- [x] Moved ticket to Approved column
- [x] Assigned PR to an operator

Operator (before pushing merge the commit)

- [x] Checked `reindex` label and `r` commit title tag
- [x] Checked that Demo expectations are clear              <sub>or PR is labeled as `no demo`</sub>
- [x] Rebased and squashed branch
- [x] Sanity-checked history
- [x] Pushed PR branch to Github
- [x] Branch pushed to Gitlab and build passes in `sandbox` <sub>or added `no sandbox` label</sub>
- [x] Started reindex in `sandbox`                          <sub>or this PR does not require reindexing `sandbox`</sub>
- [x] Checked for failures in `sandbox`                     <sub>or this PR does not require reindexing `sandbox`</sub>
- [x] Added PR reference to merge commit title
- [x] Collected commit title tags in merge commit title
- [x] Moved linked issue to Merged column
- [ ] Pushed merge commit to Github

Operator (after pushing the merge commit)

- [ ] Moved freebies to Merged column                       <sub>or there are no freebies in this PR</sub> 
- [ ] Shortened the PR chain                                <sub>or this PR is not the base of another PR</sub>
- [ ] Verified that `N reviews` labelling is accurate
- [ ] Pushed merge commit to Gitlab                         <sub>or this changes can be pushed later, together with another PR</sub>
- [ ] Deleted PR branch from Github and Gitlab

Operator (reindex) 

- [ ] Purchased BQ slot committment in `dev`                <sub>or this PR does not require reindexing `dev`</sub>
- [ ] Started reindex in `dev`                              <sub>or this PR does not require reindexing `dev`</sub>
- [ ] Deleted BQ slot committment in `dev`                  <sub>or this PR does not require reindexing `dev`</sub>
- [ ] Checked for failures in `dev`                         <sub>or this PR does not require reindexing `dev`</sub>
- [ ] Purchased BQ slot committment in `prod`               <sub>or this PR does not require reindexing `prod`</sub>
- [ ] Started reindex in `prod`                             <sub>or this PR does not require reindexing `prod`</sub>
- [ ] Deleted BQ slot committment in `prod`                 <sub>or this PR does not require reindexing `prod`</sub>
- [ ] Checked for failures in `prod`                        <sub>or this PR does not require reindexing `prod`</sub>

Operator

- [ ] Unassigned PR

### CODE REVIEW

**Comment by danielsotirhos** [comment]
[proof_1.txt](https://github.com/DataBiosphere/azul/files/6039276/proof_1.txt): Contains the terminal log attempting to replicate the steps as described in ticket https://github.com/databiosphere/azul/issues/2833 description. This uses a curl manifest containing 1 file with a bad URL. Worth noting that even though the file was not saved locally due to the  bad URL, curl did create the local directories where the file would have been placed. This appears to be unavoidable.

[proof_2.txt](https://github.com/DataBiosphere/azul/files/6039287/proof_2.txt): Contains the terminal log attempting to replicate the issue with a manifest containing 3 files to download, with the second file having a bad URL. The first file is downloaded and then upon error downloading the second file curl exits without attempting the 3rd file.

Note: in both attempts `prod` was used to generate the curl manifest, so the new `--fail` and `--fail-early` curl options were manually added to the curl manifest before the manifest was used with curl to download files.

**Review by amarjandu — APPROVED** [review]
Thanks for providing the proofs in the discussion thread. I was able to replicate that the files did not download when hitting a 404, and that subsequent files were not downloaded.

One thing to note is that it might be difficult for end-users (and us) to figure out which file is causing a problem, perhaps there is a way for us to provide them with more information of what has been downloaded. From the [curl man page ](https://curl.se/docs/manpage.html) we might be able to use `--write-output %{url}` to see which file is causing problems. (%{url} was released on curl 7.75, so it might not work for some users)

It might be worth raising a discussion about.

**Comment by danielsotirhos** [comment]
Note: The `--continue-at -` curl option to resume partially downloaded files had to be removed due to a conflict with `--fail`. If both options are specified and the user had previously completed the download of one or more files from the manifest, when the manifest is used a 2nd time the `--continue at -` option would cause a `416 (Range Not Satisfiable)` HTTP response and the `--fail` option would cause curl see this as a fatal error.

**Comment by danielsotirhos** [comment]
The current combinations of curl options has been tested on Windows ([terminal-windows.txt](https://github.com/DataBiosphere/azul/files/6046849/terminal-windows.txt)) and Mac ([terminal-macos.txt](https://github.com/DataBiosphere/azul/files/6046850/terminal-macos.txt)). In this test the manifest consists of 3 files, and the 2nd file's URL has been modified to produce an error. In both cases (windows & mac) curl completed the download of the first file, got an error attempting to download the 2nd file and exited having not attempted the 3rd file.

**Review by hannes-ucsc — APPROVED** [review]

**Comment by hannes-ucsc** [comment]
For demo, attempt to reproduce issue.

**Pull request merged**
