### PR TITLE
[u r R] Merge branch `promotions/2021-11-10` into `prod`

### PR DESCRIPTION
**Pull request by amarjandu**
### Author

~- [ ] PR title references issue~
~- [ ] PR title matches issue title (preceded by `Fix: ` for bugs)   <sub>or there is a good reason why they're different</sub>~
~- [ ] Title of main commit references issue~
~- [ ] PR is connected to Zenhub issue and description links to issue~

### Author (reindex)

- [x] Added `r` tag to commit title                         <sub>or this PR does not require reindexing</sub>
- [x] Added `reindex` label to PR                           <sub>or this PR does not require reindexing</sub>

### Author (freebies & chains)

- [x] Freebies are blocked on this PR                       <sub>or there are no freebies in this PR</sub>
- [x] Freebies are referenced in commit titles              <sub>or there are no freebies in this PR</sub>
- [x] This PR is blocked by previous PR in the chain        <sub>or this PR is not chained to another PR</sub>
- [x] Added `chain` label to the blocking PR                <sub>or this PR is not chained to another PR</sub>

### Author (upgrading)

- [x] Documented upgrading of deployments in UPGRADING.rst  <sub>or this PR does not require upgrading</sub>
- [x] Added `u` tag to commit title                         <sub>or this PR does not require upgrading</sub>
- [x] Added `upgrade` label to PR                           <sub>or this PR does not require upgrading</sub>
- [x] Added announcement to PR description                  <sub>or this PR does not require announcement</sub>
- [x] Added checklist items for additional operator tasks   <sub>or this PR does not require additional tasks</sub>

### Author (requirements, before every review)

- [x] Ran `make requirements_update`                        <sub>or this PR does not touch requirements*.txt, common.mk, Makefile and Dockerfile</sub>
- [x] Added `R` tag to commit title                         <sub>or this PR does not touch requirements*.txt</sub>
- [x] Added `reqs` label to PR                              <sub>or this PR does not touch requirements*.txt</sub>

### Author (before every review)

- [x] `make integration_test` passes in personal deployment <sub>or this PR does not touch functionality that could break the IT</sub>
- [x] Rebased branch on `develop`, squashed old fixups

### Primary reviewer (after approval)

- [x] Commented in issue about demo expectations            <sub>or labelled issue as `no demo`</sub>
- [x] Decided if PR can be labeled `no sandbox`
- [x] PR title is appropriate as title of merge commit
- [x] Moved ticket to Approved column
- [x] Assigned PR to an operator

### Operator (before pushing merge the commit)

- [ ] Checked `reindex` label and `r` commit title tag
- [ ] Checked that demo expectations are clear              <sub>or issue is labeled as `no demo`</sub>
- [ ] Rebased and squashed branch
- [ ] Sanity-checked history
- [ ] Pushed PR branch to Github
- [ ] Branch pushed to Gitlab and added `sandbox` label     <sub>or PR is labeled `no sandbox`</sub>
- [ ] Build passed in sandbox                               <sub>or PR is labeled `no sandbox`</sub>
- [ ] Started reindex in `sandbox`                          <sub>or this PR does not require reindexing `sandbox`</sub>
- [ ] Checked for failures in `sandbox`                     <sub>or this PR does not require reindexing `sandbox`</sub>
- [ ] Added PR reference to merge commit title
- [ ] Collected commit title tags in merge commit title
- [ ] Moved linked issue to Merged column
- [ ] Pushed merge commit to Github

### Operator (after pushing the merge commit)

- [ ] Made announcement requested by author                 <sub>or PR description does not contain an announcement</sub>
- [ ] Moved freebies to Merged column                       <sub>or there are no freebies in this PR</sub> 
- [ ] Shortened the PR chain                                <sub>or this PR is not the base of another PR</sub>
- [ ] Verified that `N reviews` labelling is accurate       <sub>or this PR is authored by lead</sub>
- [ ] Pushed merge commit to Gitlab                         <sub>or merge commit can be pushed later, with another PR</sub>
- [ ] Deleted PR branch from Github and Gitlab
- [ ] Build passes on Gitlab

### Operator (reindex) 

- [ ] Started reindex in target deployment                  <sub>or this PR does not require reindexing</sub>
- [ ] Checked for and triaged indexing failures             <sub>or this PR does not require reindexing</sub>
- [ ] Emptied fail queues in target deployment              <sub>or this PR does not require reindexing</sub>

### Operator

- [ ] Unassigned PR

### CODE REVIEW

**Review by danielsotirhos — APPROVED** [review]
Approved.

**Review by hannes-ucsc — APPROVED** [review]

**Comment by hannes-ucsc** [comment]
Note my title changes. Back quotes in titles, not singe quotes. And R tag was missing.

**Comment by amarjandu** [comment]
ran `python scripts/reindex.py --catalogs it10 it11 it1 it0lungmap --delete --create` to reduce sharding in ES. Note this is different from the command in the upgrading instructions that uses `--index`

**Comment by amarjandu** [comment]
6 failed notifications, 1 duplicate 5 unique. 
All expected failures https://github.com/DataBiosphere/azul/issues/3613#issuecomment-961334880
[azul-notifications_fail-prod.json.txt](https://github.com/DataBiosphere/azul/files/7558211/azul-notifications_fail-prod.json.txt)
```
{
  "bundle_uuid": "a059d535-19e5-5ba2-b794-434e0fe89195",
  "bundle_version": "2021-10-06T17:32:00.000000Z"
}

{
  "bundle_uuid": "a7882d93-786a-5929-a083-c12635d39453",
  "bundle_version": "2021-10-12T19:18:03.000000Z"
}
{
  "bundle_uuid": "10260267-ca02-5b10-9df7-37697886f1de",
  "bundle_version": "2021-10-12T18:47:27.000000Z"
}
{
  "bundle_uuid": "fe70d276-05be-5ad7-8d87-135c04cfaf54",
  "bundle_version": "2021-10-07T18:17:35.000000Z"
}
{
  "bundle_uuid": "10260267-ca02-5b10-9df7-37697886f1de",
  "bundle_version": "2021-10-12T18:47:27.000000Z"
}
{
  "bundle_uuid": "7681f23d-401e-5b77-bf1d-20a782f91965",
  "bundle_version": "2021-10-12T18:33:36.000000Z"
}
```

**Pull request merged**
