### PR TITLE
Fix #1052: Disable ES dynamic type setting for metadata fields

### PR DESCRIPTION
**Pull request by achave11**
This reverts commit 162deaba

### CODE REVIEW

**Comment by hannes-ucsc** [comment]
You haven't requested a review so you may already be aware of it: We agreed that there would be one commit that adds the test and that the build for that commit should fail in that test with the same error that we got in `prod`, as captured in the ticket.

**Comment by achave11** [comment]
Correct, notice the commit `8214d89` that introduces the test which reproduces the error seen in production. It is a rather interesting issue, remind me to explain if you are interested in the details. 
Also notice that the previously discussed solution of deactivating the mappings for all fields in metadata is not possible with out breaking the dynamic TSV generation mechanisms. Reason being dynamic mapping of those fields, in the present, allows us to generate the header row of the TSV. 
Until the update provided by #1147 we need to preserve the mapping.

**Comment by hannes-ucsc** [comment]
> notice the commit TBD that

I don't get it. Notice what commit? I also see no Travis build that fails with the same error we get in production.

I had to force push develop to fix a mistake I made on Friday.

**Comment by hannes-ucsc** [comment]
Given the confusing exchange of comments on this PR, I'm closing it. Please create another PR when you have a branch with two commits: one that reverts the hotfix and another commit that adds a test reproducing the problem exactly as it happened on prod.

**Pull request closed without merging**
