### PR TITLE
Gitlab IAM policy for Data Portal & Browser deployment (#1993)

### PR DESCRIPTION
**Pull request by hannes-ucsc**

### CODE REVIEW

**Comment by hannes-ucsc** [comment]
Despite being just a PR, these changes can already be observed on the `dev` Gitlab instance.

@NoopDog, could you see if this makes your build work?

**Comment by hannes-ucsc** [comment]
@NoopDog This has also been deployed to prod. Please check if your build works there too and approve one more time or suggest changes.

**Comment by NoopDog** [comment]
Thanks will check

**Comment by hannes-ucsc** [comment]
Note that this was merged to `hca/develop` but has already been deployed to the HCA `dev` and `prod` instances of Gitlab.

**Comment by hannes-ucsc** [comment]
For demo: show successful browser & portal builds for `dev` and `prod`

**Pull request merged**
