### PR TITLE
Promotion 2022-04-07 (#4060)

### PR DESCRIPTION
**Pull request by amarjandu**
Connected issue: #4060

### Author

- [x] Target branch is `prod`
- [x] Source branch matches `promotions/yyyy-mm-dd`
- [x] Title of connected issue matches `Promotion yyyy-mm-dd`
- [x] PR title starts with title of connected issue
- [x] PR title references the connected issue
- [x] PR is connected to issue via Zenhub 
- [x] PR description links to connected issue

### Author (reindex)

- [x] Added `reindex` label to PR                                   <sub>or this promotion does not require reindexing</sub>

### Author (upgrading)

- [x] Added `upgrade` label to PR                                   <sub>or this promotion does not require upgrading</sub>

### Primary reviewer (after approval)

- [x] Actually approved the PR
- [x] Labeled PR as `no sandbox`
- [x] Moved ticket to *Approved* column
- [x] Assigned PR to current operator

### Operator (before pushing merge the commit)

- [x] Pushed PR branch to GitHub
- [x] Added PR reference to merge commit title
- [x] Collected commit title tags in merge commit title
- [ ] Pushed merge commit to GitHub

### Operator (after pushing the merge commit)

- [ ] Made announcement requested by author                         <sub>or PR description does not contain an announcement</sub>
- [ ] Shortened the PR chain                                        <sub>or this PR is not the base of another PR</sub>
- [ ] Pushed merge commit to GitLab                                 <sub>or merge commit can be pushed later, with another PR</sub>
- [ ] Deleted PR branch from GitHub and GitLab
- [ ] Build passes on GitLab
- [ ] Moved connected issue to *Merged prod* column on ZenHub
- [ ] Moved promoted issues from *Merged* to *Merged prod* column  <sub>or this PR does not represent a promotion</sub>
- [ ] Moved promoted issues from *dev* to *prod* column            <sub>or this PR does not represent a promotion</sub>

### Operator (reindex) 

- [ ] Deleted unreferenced indices in `prod`                        <sub>or this PR does not remove catalogs or otherwise causes unreferenced indices</sub> 
- [ ] Started reindex in `prod`                                     <sub>or this PR does not require reindexing</sub>
- [ ] Checked for and triaged indexing failures                     <sub>or this PR does not require reindexing</sub>
- [ ] Emptied fail queues in target deployment                      <sub>or this PR does not require reindexing</sub>

### Operator

- [ ] Unassigned PR

## Shorthand for review comments

- `L` line is too long
- `W` line wrapping is wrong
- `Q` bad quotes
- `F` other formatting problem

### CODE REVIEW

**Review by hannes-ucsc — APPROVED** [review]

**Review by noah-aviel-dove — APPROVED** [review]
Pro-forma approval

**Comment by amarjandu** [comment]
`dcp13` catalog deleted from `prod`

**Comment by amarjandu** [comment]
started reindex of `dcp15`

**Comment by amarjandu** [comment]
`dcp15` indexed without failures.

**Pull request merged**
