### PR TITLE
Rename `repository` in service routes (#1724)

### PR DESCRIPTION
**Pull request by amarjandu**

### CODE REVIEW

**Comment by amarjandu** [comment]
> Also in service/app.py it could be worth updating the anchor links in the generated swagger doc even though their target isn't yet available. 

Changed

**Comment by hannes-ucsc** [comment]
Just change the external-facing aspects like routes and documentation and file a follow-on ticket for the internal renamings.

**Comment by amarjandu** [comment]
@hannes-ucsc i confirmed the IT this morning before requesting review :) 
The ticket has been created in the DB, but I cannot add the `blocked by` because I don't have permissions to do so. 
https://app.zenhub.com/workspaces/orange-5d680d7e3eeb5f1bbdf5668f/issues/humancellatlas/data-browser/1193

**Comment by hannes-ucsc** [comment]
I set the blocking relationship.

**Comment by amarjandu** [comment]
conflicts addressed, rebase complete.

**Pull request merged**
