### PR TITLE
Fix import warning with namespace packages (#2077)

### PR DESCRIPTION
**Pull request by jessebrennan**

### CODE REVIEW

**Comment by jessebrennan** [comment]
@danielsotirhos the PR is straight forward, but the motivation isn't exactly. See the ticket for a more detailed explanation of why.

**Review by hannes-ucsc — CHANGES_REQUESTED** [review]
https://gitlab.dev.singlecell.gi.ucsc.edu/ucsc/azul/-/jobs/5624

no bump

**Comment by jessebrennan** [comment]
@hannes-ucsc with out thinking, I force-pushed instead of making a `fixup!` commit.

**Review by hannes-ucsc — APPROVED** [review]

**Review by hannes-ucsc — CHANGES_REQUESTED** [review]
https://gitlab.dev.singlecell.gi.ucsc.edu/ucsc/azul/-/jobs/5675

Can you determine why on Gitlab cfn-lint was downgraded again?

**Comment by jessebrennan** [comment]
> Can you determine why on Gitlab cfn-lint was downgraded again?

@hannes-ucsc 

It looks like the container used to build the requirements was cached from when this PR was tested yesterday at 11:33 AM. Shortly after, at 12:37 PM, `cfn-lint 35.1` was released. Using the cached container prevented `make requirements` from being run again and catching the updated dependency.

I don't understand why [copying the updated transitive requirements files](https://gitlab.dev.singlecell.gi.ucsc.edu/ucsc/azul/-/jobs/5675#L462) didn't invalidate the layer cache. Are transitive requirements not copied here?

**Comment by jessebrennan** [comment]
@hannes-ucsc could we consider this PR passing in the sandbox a "demo" of #2261?

**Review by hannes-ucsc — APPROVED** [review]
> could we consider this PR passing in the sandbox a "demo" of #2261?

Not without an explanation. But I wouldn't bother. That ticket is closed and `no demo`.

**Comment by hannes-ucsc** [comment]
For demo, repro #2077, first without these changes, then with.

**Pull request merged**
