### PR TITLE
Fix: Various wheel/Chalice issues (#3428, #3432, #3434)

### PR DESCRIPTION
**Pull request by amarjandu**
https://github.com/DataBiosphere/azul/issues/3428
https://github.com/DataBiosphere/azul/issues/3432
https://github.com/DataBiosphere/azul/issues/3434

Author

- [x] PR title references issue
- [x] PR title matches issue title (preceded by `Fix: ` for bugs)   <sub>or there is a good reason why they're different</sub>
- [x] Title of main commit references issue
- [x] PR is connected to Zenhub issue and description links to issue

Author (reindex)

- [x] Added `r` tag to commit title                         <sub>or this PR does not require reindexing</sub>
- [x] Added `reindex` label to PR                           <sub>or this PR does not require reindexing</sub>

Author (freebies & chains)

- [x] Freebies are blocked on this PR                       <sub>or there are no freebies in this PR</sub>
- [x] Freebies are referenced in commit titles              <sub>or there are no freebies in this PR</sub>
- [x] This PR is blocked by previous PR in the chain        <sub>or this PR is not chained to another PR</sub>
- [x] Added `chain` label to the blocking PR                <sub>or this PR is not chained to another PR</sub>

Author (upgrading)

- [x] Documented upgrading of deployments in UPGRADING.rst  <sub>or this PR does not require upgrading</sub>
- [x] Added `u` tag to commit title                         <sub>or this PR does not require upgrading</sub>
- [x] Added `upgrade` label to PR                           <sub>or this PR does not require upgrading</sub>
- [x] Added announcement to PR description                  <sub>or this PR does not require announcement</sub>

Author (requirements, before every review)

- [x] Ran `make requirements_update`                        <sub>or this PR leaves requirements*.txt, common.mk and Makefile untouched</sub>
- [x] Added `R` tag to commit title                         <sub>or this PR leaves requirements*.txt untouched</sub>
- [x] Added `reqs` label to PR                              <sub>or this PR leaves requirements*.txt untouched</sub>

Author (before every review)

- [x] `make integration_test` passes in personal deployment <sub>or this PR does not touch functionality that could break the IT</sub>
- [x] Rebased branch on `develop`, squashed old fixups

Primary reviewer (after approval)

- [x] Commented in issue about demo expectations            <sub>or labelled issue as `no demo`</sub>
- [x] Decided if PR can be labeled `no sandbox`
- [x] PR title is appropriate as title of merge commit
- [x] Moved ticket to Approved column
- [x] Assigned PR to an operator

Operator (before pushing merge the commit)

- [x] Checked `reindex` label and `r` commit title tag
- [x] Checked that demo expectations are clear              <sub>or issue is labeled as `no demo`</sub>
- [x] Rebased and squashed branch
- [x] Sanity-checked history
- [x] Pushed PR branch to Github
- [x] Branch pushed to Gitlab and added `sandbox` label     <sub>or PR is labeled `no sandbox`</sub>
- [x] Build passed in sandbox                               <sub>or PR is labeled `no sandbox`</sub>
- [x] Started reindex in `sandbox`                          <sub>or this PR does not require reindexing `sandbox`</sub>
- [x] Checked for failures in `sandbox`                     <sub>or this PR does not require reindexing `sandbox`</sub>
- [x] Added PR reference to merge commit title
- [x] Collected commit title tags in merge commit title
- [x] Moved linked issue to Merged column
- [ ] Pushed merge commit to Github

Operator (after pushing the merge commit)

- [ ] Made announcement requested by author                 <sub>or PR description does not contain an announcement</sub>
- [ ] Moved freebies to Merged column                       <sub>or there are no freebies in this PR</sub> 
- [ ] Shortened the PR chain                                <sub>or this PR is not the base of another PR</sub>
- [ ] Verified that `N reviews` labelling is accurate
- [ ] Pushed merge commit to Gitlab                         <sub>or this changes can be pushed later, together with another PR</sub>
- [ ] Deleted PR branch from Github and Gitlab

Operator (reindex) 

- [ ] Started reindex in `dev`                              <sub>or this PR does not require reindexing or does not target `dev`</sub>
- [ ] Checked for failures in `dev`                         <sub>or this PR does not require reindexing or does not target `dev`</sub>
- [ ] Started reindex in `prod`                             <sub>or this PR does not require reindexing or does not target `prod`</sub>
- [ ] Checked for failures in `prod`                        <sub>or this PR does not require reindexing or does not target `prod`</sub>

Operator

- [ ] Unassigned PR

### CODE REVIEW

**Comment by amarjandu** [comment]
passes IT + reindex

**Review by danielsotirhos — APPROVED** [review]
Approved.
Tested with MacOS Big Sur 11.6, Python 3.8.12, and `hca-metadata-api` requirement updated from release/1.0b31 to 32. Successfully able to perform `make requirements` and `make deploy`.

**Review by hannes-ucsc — CHANGES_REQUESTED** [review]
Why does this update Python?

Please provide evidence that Azul docker images built from this commit have the updated `Python` and `pip` versions installed.

The 1st and 3rd commit message bodies should reference the commit where the regression was introduced.

**Comment by amarjandu** [comment]
```
(.venv) CBSEspecter:azul amar$ git status
On branch issues/amar/3428-layer-pip-wheels
nothing to commit, working tree clean

(.venv) CBSEspecter:azul amar$ git rev-parse --verify HEAD
1787a3a95e93d0c08025d0afbf0c120acff06a10

(.venv) CBSEspecter:azul amar$ make docker
docker build --build-arg make_target=requirements_runtime_no_deps --build-arg cache_seed= -t azul:latest .
[+] Building 0.2s (12/12) FINISHED
 => [internal] load build definition from Dockerfile                                                               0.0s
 => => transferring dockerfile: 37B                                                                                0.0s
 => [internal] load .dockerignore                                                                                  0.0s
 => => transferring context: 119B                                                                                  0.0s
 => [internal] load metadata for docker.io/library/python:3.8.3-buster                                             0.0s
 => [1/7] FROM docker.io/library/python:3.8.3-buster                                                               0.0s
 => [internal] load build context                                                                                  0.0s
 => => transferring context: 262B                                                                                  0.0s
 => CACHED [2/7] RUN mkdir /build                                                                                  0.0s
 => CACHED [3/7] WORKDIR /build                                                                                    0.0s
 => CACHED [4/7] RUN mkdir terraform     && (cd terraform         && wget --quiet https://releases.hashicorp.com/  0.0s
 => CACHED [5/7] RUN curl -s https://download.docker.com/linux/static/stable/x86_64/docker-18.03.1-ce.tgz     | t  0.0s
 => CACHED [6/7] COPY requirements*.txt common.mk Makefile ./                                                      0.0s
 => CACHED [7/7] RUN make virtualenv     && source .venv/bin/activate     && make requirements_runtime_no_deps     0.0s
 => exporting to image                                                                                             0.0s
 => => exporting layers                                                                                            0.0s
 => => writing image sha256:a183cd00f1a65dea09c382cb1bfe26853ec41c6c9c0dfb74384947a150e365fa                       0.0s
 => => naming to docker.io/library/azul:latest                                                                     0.0s

Use 'docker scan' to run Snyk tests against images to find vulnerabilities and learn how to fix them

(.venv) CBSEspecter:azul amar$ docker run -it azul:latest bash

root@b0af50767e7f:/build# source .venv/bin/activate

(.venv) root@b0af50767e7f:/build# pip --version
pip 19.3.1 from /build/.venv/lib/python3.8/site-packages/pip (python 3.8)

(.venv) root@b0af50767e7f:/build# python --version
Python 3.8.3

(.venv) root@b0af50767e7f:/build# exit
```

**Review by hannes-ucsc — CHANGES_REQUESTED** [review]
Just listing the commit sha in the commit message body isn't enough. It should be `Regression from <sha>`

**Comment by hannes-ucsc** [comment]
Also, I don't think the `r` title tag and `upgrade` label are justified anymore.

**Comment by amarjandu** [comment]
@hannes-ucsc  We still have to update the reqs, so commit tag [r] stays. I dropped [u].

**Review by hannes-ucsc — APPROVED** [review]

**Comment by hannes-ucsc** [comment]
@jessebrennan merge this first before anything else in Approved. Then reattempt promotion first thing tomorrow.

**Pull request merged**
