### PR TITLE
Index replica entities (#5359)

### LINKED ISSUE #5359: Index replica entities
[2/3] https://github.com/DataBiosphere/azul/issues/4942#issuecomment-1612106651

- [x] Security design review completed; the Resolution of this issue does **not** …
  - [x] … affect authentication; for example:
    - OAuth 2.0 with the application (API or Swagger UI)
    - Authentication of developers with Google Cloud APIs
    - Authentication of developers with AWS APIs
    - Authentication with a GitLab instance in the system
    - Password and 2FA authentication with GitHub
    - API access token authentication with GitHub
    - Authentication with 
  - [x] … affect the permissions of internal users like access to
    - Cloud resources on AWS and GCP
    - GitLab repositories, projects and groups, administration
    - an EC2 instance via SSH
    - GitHub issues, pull requests, commits, commit statuses, wikis, repositories, organizations
  - [x] … affect the permissions of external users like access to
    - TDR snapshots
  - [x] … affect permissions of service or bot accounts
    - Cloud resources on AWS and GCP
  - [x] … affect audit logging in the system, like
    - adding, removing or changing a log message that represents an auditable event
    - changing the routing of log messages through the system
  - [x] … affect monitoring of the system
  - [x] … introduce a new software dependency like
    - Python packages on PYPI
    - Command-line utilities
    - Docker images
    - Terraform providers
  - [x] … add an interface that exposes sensitive or confidential data at the security boundary
  - [x] … affect the encryption of data at rest
  - [ ] … ~require persistence of sensitive or confidential data that might require encryption at rest~ https://github.com/DataBiosphere/azul/issues/5359#issuecomment-1773096016
  - [x] … require unencrypted transmission of data within the security boundary
  - [x] … affect the network security layer; for example by 
    - modifying, adding or removing firewall rules
    - modifying, adding or removing security groups
    - changing or adding a port a service, proxy or load balancer listens on
- [x] Documentation on any unchecked boxes is provided in comments below

### PR DESCRIPTION
**Pull request by nadove-ucsc**
Connected issues: #5359
Supersedes PR #5468 which was merged but then reverted

### Author

- [x] PR is a draft
- [x] Target branch is `develop`
- [x] Name of PR branch matches `issues/<GitHub handle of author>/<issue#>-<slug>`
- [x] PR title references all connected issues
- [x] PR title matches<sup>1</sup> that of a connected issue <sub>or comment in PR explains why they're different</sub>
- [x] For each connected issue, there is at least one commit whose title references that issue
- [x] PR is connected to all connected issues via ZenHub
- [x] PR description links to connected issues
- [x] Added `p` tag to titles of partial commits
- [x] Added `partial` label to PR <sub>or this PR completely resolves all connected issues</sub>
- [x] All connected issues are resolved partially <sub>or this PR does not have the `partial` label</sub>

<sup>1</sup> when the issue title describes a problem, the corresponding PR
title is `Fix: ` followed by the issue title

### Author (reindex, API changes)

- [x] Added `r` tag to commit title <sub>or this PR does not require reindexing</sub>
- [x] Added `reindex` label to PR <sub>or this PR does not require reindexing</sub>
- [x] PR and connected issue are labeled `API` <sub>or this PR does not modify a REST API</sub>
- [x] Added `a` (`A`) tag to commit title for backwards (in)compatible changes <sub>or this PR does not modify a REST API</sub>
- [x] Updated REST API version number in `app.py` <sub>or this PR does not modify a REST API</sub>

### Author (chains)

- [x] This PR is blocked by previous PR in the chain <sub>or this PR is not chained to another PR</sub>
- [x] Added `base` label to the blocking PR <sub>or this PR is not chained to another PR</sub>
- [x] Added `chained` label to this PR <sub>or this PR is not chained to another PR</sub>

### Author (upgrading)

- [x] Documented upgrading of deployments in UPGRADING.rst <sub>or this PR does not require upgrading</sub>
- [x] Added `u` tag to commit title <sub>or this PR does not require upgrading</sub>
- [x] Added `upgrade` label to PR <sub>or this PR does not require upgrading</sub>

### Author (operator tasks)

- [x] Added checklist items for additional operator tasks <sub>or this PR does not require additional tasks</sub>

### Author (hotfixes)

- [x] Added `F` tag to main commit title <sub>or this PR does not include permanent fix for a temporary hotfix</sub>
- [x] Reverted the temporary hotfixes for any connected issues <sub>or the `prod` branch has no temporary hotfixes for any connected issues</sub>

### Author (before every review)

- [x] Rebased PR branch on `develop`, squashed old fixups
- [x] Ran `make requirements_update` <sub>or this PR does not touch requirements*.txt, common.mk, Makefile and Dockerfile</sub>
- [x] Added `R` tag to commit title <sub>or this PR does not touch requirements*.txt</sub>
- [x] Added `reqs` label to PR <sub>or this PR does not touch requirements*.txt</sub>
- [x] `make integration_test` passes in personal deployment <sub>or this PR does not touch functionality that could break the IT</sub>

### Peer reviewer (after requesting changes)

Uncheck the *Author (before every review)* checklists.

### Peer reviewer (after approval)

- [x] PR is not a draft
- [x] Ticket is in *Review requested* column
- [x] Requested review from primary reviewer
- [x] Assigned PR to primary reviewer

### Primary reviewer (after requesting changes)

Uncheck the *before every review* checklists. Update the `N reviews` label.

### Primary reviewer (after approval)

- [x] Actually approved the PR
- [x] Labeled connected issues as `demo` or `no demo`
- [x] Commented on connected issues about demo expectations <sub>or all connected issues are labeled `no demo`</sub>
- [x] Decided if PR can be labeled `no sandbox`
- [x] PR title is appropriate as title of merge commit
- [x] `N reviews` label is accurate
- [x] Moved ticket to *Approved* column
- [x] Assigned PR to current operator

### Operator (before pushing merge the commit)

- [x] Checked `reindex` label and `r` commit title tag
- [x] Checked that demo expectations are clear <sub>or all connected issues are labeled `no demo`</sub>
- [x] PR has checklist items for upgrading instructions <sub>or PR is not labeled `upgrade`</sub>
- [x] Squashed PR branch and rebased onto `develop`
- [x] Sanity-checked history
- [x] Pushed PR branch to GitHub
- [x] Pushed PR branch to GitLab `dev` and added `sandbox` label <sub>or PR is labeled `no sandbox`</sub>
- [x] Pushed PR branch to GitLab `anvildev` <sub>or PR is labeled `no sandbox`</sub>
- [x] Pushed PR branch to GitLab `anvilprod` <sub>or PR is labeled `no sandbox`</sub>
- [x] Build passes in `sandbox` deployment <sub>or PR is labeled `no sandbox`</sub>
- [x] Build passes in `anvilbox` deployment <sub>or PR is labeled `no sandbox`</sub>
- [x] Build passes in `hammerbox` deployment <sub>or PR is labeled `no sandbox`</sub>
- [x] Reviewed build logs for anomalies in `sandbox` deployment <sub>or PR is labeled `no sandbox`</sub>
- [x] Reviewed build logs for anomalies in `anvilbox` deployment <sub>or PR is labeled `no sandbox`</sub>
- [x] Reviewed build logs for anomalies in `hammerbox` deployment <sub>or PR is labeled `no sandbox`</sub>
- [x] Deleted unreferenced indices in `sandbox` <sub>or this PR does not remove catalogs or otherwise causes unreferenced indices </sub>
- [x] Deleted unreferenced indices in `anvilbox` <sub>or this PR does not remove catalogs or otherwise causes unreferenced indices </sub>
- [x] Deleted unreferenced indices in `hammerbox` <sub>or this PR does not remove catalogs or otherwise causes unreferenced indices </sub>
- [x] Started reindex in `sandbox` <sub>or this PR does not require reindexing `sandbox`</sub>
- [x] Started reindex in `anvilbox` <sub>or this PR does not require reindexing `sandbox`</sub>
- [x] Started reindex in `hammerbox` <sub>or this PR does not require reindexing `sandbox`</sub>
- [x] Checked for failures in `sandbox` <sub>or this PR does not require reindexing `sandbox`</sub>
- [x] Checked for failures in `anvilbox` <sub>or this PR does not require reindexing `sandbox`</sub>
- [x] Checked for failures in `hammerbox` <sub>or this PR does not require reindexing `sandbox`</sub>
- [x] Title of merge commit starts with title from this PR
- [x] Added PR reference to merge commit title
- [x] Collected commit title tags in merge commit title <sub>but only include `p` if the PR is labeled `partial`</sub>
- [x] Moved connected issues to Merged column in ZenHub
- [x] Pushed merge commit to GitHub

### Operator (chain shortening)

- [x] Changed the target branch of the blocked PR to `develop` <sub>or this PR is not labeled `base`</sub>
- [x] Removed the `chained` label from the blocked PR <sub>or this PR is not labeled `base`</sub>
- [x] Removed the blocking relationship from the blocked PR <sub>or this PR is not labeled `base`</sub>
- [x] Removed the `base` label from this PR <sub>or this PR is not labeled `base`</sub>

### Operator (after pushing the merge commit)

- [x] Pushed merge commit to GitLab `dev` <sub>or PR is labeled `no sandbox`</sub>
- [x] Pushed merge commit to GitLab `anvildev` <sub>or PR is labeled `no sandbox`</sub>
- [x] Pushed merge commit to GitLab `anvilprod` <sub>or PR is labeled `no sandbox`</sub>
- [x] Build passes on GitLab `dev`<sup>1</sup>
- [x] Reviewed build logs for anomalies on GitLab `dev`<sup>1</sup>
- [x] Build passes on GitLab `anvildev`<sup>1</sup>
- [x] Reviewed build logs for anomalies on GitLab `anvildev`<sup>1</sup>
- [x] Build passes on GitLab `anvilprod`<sup>1</sup>
- [x] Reviewed build logs for anomalies on GitLab `anvilprod`<sup>1</sup>
- [x] Deleted PR branch from GitHub
- [x] Deleted PR branch from GitLab `dev`
- [x] Deleted PR branch from GitLab `anvildev`
- [x] Deleted PR branch from GitLab `anvilprod`

<sup>1</sup> When pushing the merge commit is skipped due to the PR being
labelled `no sandbox`, the next build triggered by a PR whose merge commit *is*
pushed determines this checklist item.

### Operator (reindex)

- [x] Deleted unreferenced indices in `dev` <sub>or this PR does not remove catalogs or otherwise causes unreferenced indices </sub>
- [x] Deleted unreferenced indices in `anvildev` <sub>or this PR does not remove catalogs or otherwise causes unreferenced indices </sub>
- [x] Deleted unreferenced indices in `anvilprod` <sub>or this PR does not remove catalogs or otherwise causes unreferenced indices </sub>
- [x] Started reindex in `dev` <sub>or this PR does not require reindexing</sub>
- [x] Started reindex in `anvildev` <sub>or this PR does not require reindexing</sub>
- [x] Started reindex in `anvilprod` <sub>or this PR does not require reindexing</sub>
- [x] Checked for and triaged indexing failures in `dev` <sub>or this PR does not require reindexing</sub>
- [x] Checked for and triaged indexing failures in `anvildev` <sub>or this PR does not require reindexing</sub>
- [x] Checked for and triaged indexing failures in `anvilprod` <sub>or this PR does not require reindexing</sub>
- [x] Emptied fail queues in `dev` deployment <sub>or this PR does not require reindexing</sub>
- [x] Emptied fail queues in `anvildev` deployment <sub>or this PR does not require reindexing</sub>
- [x] Emptied fail queues in `anvilprod` deployment <sub>or this PR does not require reindexing</sub>

### Operator

- [x] Unassigned PR

## Shorthand for review comments

- `L` line is too long
- `W` line wrapping is wrong
- `Q` bad quotes
- `F` other formatting problem

### CODE REVIEW

**Comment by nadove-ucsc** [comment]
Reviewers: note that the 1st, 4th, and 5th commits were [already approved](https://github.com/DataBiosphere/azul/pull/5468)

**Review by dsotirho-ucsc — DISMISSED** [review]
Approved.

**Review by hannes-ucsc — CHANGES_REQUESTED** [review]
```diff
Subject: [PATCH] Fix: Read timeouts cause Terra client to exceed restricted timing (#5720)

The first attempt (c9af078076a8ae27e0c507e3b273b2a72e73cda5) of fixing this was ineffective. This commit adds a test, too.
---
Index: src/azul/indexer/index_controller.py
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/src/azul/indexer/index_controller.py b/src/azul/indexer/index_controller.py
--- a/src/azul/indexer/index_controller.py	(revision 9bd2334d0d0efe338b133f118db392e9f806141e)
+++ b/src/azul/indexer/index_controller.py	(date 1702425096554)
@@ -184,14 +184,17 @@
                     tallies = [DocumentTally.for_entity(catalog, entity, num_contributions)
                                for entity, num_contributions in tallies.items()]
 
-                    if config.enable_replicas:
+                    # REVIEW: The config flag should disable the generation of
+                    #         replicas further down, where they are generated.
+                    #         Let me know if I gave contradictory guidance
+                    #         earlier. I might be forgetting something.
+                    if replicas:
                         log.info('Writing %i replicas to index.', len(replicas))
-                        num_added, num_present = self.index_service.replicate(catalog, replicas)
-                        log.info('Successfully added %i replicas; %i were already present',
-                                 num_added, num_present)
-                        assert num_added + num_present == len(replicas)
+                        num_written, num_present = self.index_service.replicate(catalog, replicas)
+                        log.info('Successfully wrote %i replicas; %i were already present',
+                                 num_written, num_present)
                     else:
-                        log.info('Replicas are disabled; would write %i', len(replicas))
+                        log.info('No replicas to write.')
 
                     log.info('Queueing %i entities for aggregating a total of %i contributions.',
                              len(tallies), sum(tally.num_contributions for tally in tallies))
Index: src/azul/indexer/index_service.py
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/src/azul/indexer/index_service.py b/src/azul/indexer/index_service.py
--- a/src/azul/indexer/index_service.py	(revision 9bd2334d0d0efe338b133f118db392e9f806141e)
+++ b/src/azul/indexer/index_service.py	(date 1702424098014)
@@ -506,8 +506,7 @@
                   replicas: list[Replica]
                   ) -> tuple[int, int]:
         writer = self._create_writer(catalog)
-        num_added = 0
-        num_present = 0
+        num_written, num_present = 0, 0
         while replicas:
             writer.write(replicas)
             retry_replicas = []
@@ -524,11 +523,14 @@
                     else:
                         assert False, (conflicts, r.coordinates)
                 else:
-                    num_added += 1
+                    num_written += 1
             replicas = retry_replicas
 
         writer.raise_on_errors()
-        return num_added, num_present
+        assert num_written + num_present == len(replicas), (
+            num_written, num_present, len(replicas)
+        )
+        return num_written, num_present
 
     def _read_aggregates(self,
                          entities: CataloguedTallies
Index: src/azul/indexer/document.py
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/src/azul/indexer/document.py b/src/azul/indexer/document.py
--- a/src/azul/indexer/document.py	(revision 9bd2334d0d0efe338b133f118db392e9f806141e)
+++ b/src/azul/indexer/document.py	(date 1702424872800)
@@ -1481,6 +1481,10 @@
     A verbatim copy of a metadata document
     """
 
+    # REVIEW: Would be good to explain the relationship to entity type. IIRC,
+    #         the sets of possible values for replica and entity types overlap
+    #         but are not identical.
+
     #: The type of replica. Typically, all replicas of the same type have
     #: similar shapes, just like contributions for entities of the same type.
     #: We can't model replica types as entity types because we want to hold all
```

**Review by hannes-ucsc — CHANGES_REQUESTED** [review]
```diff
Subject: [PATCH] Fix: Read timeouts cause Terra client to exceed restricted timing (#5720)

The first attempt (c9af078076a8ae27e0c507e3b273b2a72e73cda5) of fixing this was ineffective. This commit adds a test, too.
---
Index: test/indexer/test_indexer.py
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/test/indexer/test_indexer.py b/test/indexer/test_indexer.py
--- a/test/indexer/test_indexer.py	(revision c34ea4510c4fab5d255781e52b6ce451f96bcc0f)
+++ b/test/indexer/test_indexer.py	(date 1702518640920)
@@ -110,10 +110,7 @@
     configure_test_logging(log)
 
 
-class TestHCAIndexerExplicit(DCP1TestCase, IndexerTestCase):
-
-    # These tests create and/or delete the indices explicitly, so they are not
-    # managed via setUp() or `tearDown()`
+class TestHCAIndexer(DCP1TestCase, IndexerTestCase):
 
     @cached_property
     def old_bundle(self):
@@ -312,7 +309,14 @@
                     self.index_service.delete_indices(self.catalog)
 
 
-class TestHCAIndexer(TestHCAIndexerExplicit):
+class TestHCAIndexerWithIndexesSetUp(TestHCAIndexer):
+    """
+    Conveniently sets up (tears down) indices before (after) each test.
+    """
+
+    # REVIEW: This class inherits the test methods from the base class. I think
+    #         they won't be run twice but please double-check. Either way, it
+    #         might be more clean to extract a test case class.
 
     def setUp(self) -> None:
         super().setUp()
Index: test/indexer/test_anvil.py
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/test/indexer/test_anvil.py b/test/indexer/test_anvil.py
--- a/test/indexer/test_anvil.py	(revision c34ea4510c4fab5d255781e52b6ce451f96bcc0f)
+++ b/test/indexer/test_anvil.py	(date 1702518783898)
@@ -83,10 +83,7 @@
         }
 
 
-class TestAnvilIndexerExplicit(AnvilIndexerTestCase):
-
-    # These tests explicitly create and delete the indices, instead of using
-    # setUp/tearDown
+class TestAnvilIndexer(AnvilIndexerTestCase):
     def test_indexing(self):
         self.maxDiff = None
         canned_hits = self._load_canned_result(self.bundle)
@@ -114,7 +111,10 @@
                         self.index_service.delete_indices(self.catalog)
 
 
-class TestAnvilIndexer(AnvilIndexerTestCase):
+class TestAnvilIndexerWithIndexesSetUp(AnvilIndexerTestCase):
+    """
+    Conveniently sets up (tears down) indices before (after) each test.
+    """
 
     def setUp(self) -> None:
         super().setUp()
Index: test/indexer/__init__.py
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/test/indexer/__init__.py b/test/indexer/__init__.py
--- a/test/indexer/__init__.py	(revision c34ea4510c4fab5d255781e52b6ce451f96bcc0f)
+++ b/test/indexer/__init__.py	(date 1702517844134)
@@ -156,6 +156,9 @@
                 and 'description' in one(hit['_source']['contents']['datasets'])
             ):
                 # DUOS contributions contain no lists
+                # REVIEW: I don't know how I missed this before. Can you please
+                #         rewrite this continue (separate commit) and then also
+                #         not add the `continue` above?
                 continue
             self._verify_sorted_lists(hit['_source'])
         return hits
Index: src/azul/indexer/document_service.py
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/src/azul/indexer/document_service.py b/src/azul/indexer/document_service.py
--- a/src/azul/indexer/document_service.py	(revision c34ea4510c4fab5d255781e52b6ce451f96bcc0f)
+++ b/src/azul/indexer/document_service.py	(date 1702514989594)
@@ -96,7 +96,7 @@
             Contribution.field_types(field_types),
             aggregate_cls.field_types(field_types)
             # Replicas are intentionally omitted here because their contents
-            # should not undergo translation
+            # does not undergo translation
         )
 
     def catalogued_field_types(self) -> CataloguedFieldTypes:
Index: src/azul/indexer/document.py
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/src/azul/indexer/document.py b/src/azul/indexer/document.py
--- a/src/azul/indexer/document.py	(revision c34ea4510c4fab5d255781e52b6ce451f96bcc0f)
+++ b/src/azul/indexer/document.py	(date 1702514785290)
@@ -376,7 +376,7 @@
         if index_name[-1] == 'aggregate':
             *index_name, _ = index_name
             doc_type = DocumentType.aggregate
-        elif index_name == ['replica']:
+        elif one(index_name) == 'replica':
             doc_type = DocumentType.replica
         else:
             doc_type = DocumentType.contribution
@@ -621,8 +621,14 @@
 
 @attr.s(frozen=True, auto_attribs=True, kw_only=True, slots=True)
 class ReplicaCoordinates(DocumentCoordinates[E], Generic[E]):
+    """
+    REVIEW: Provide docstring
+    """
+
+    doc_type: DocumentType = attr.ib(init=False, default=DocumentType.replica)
+
+    #: A hash of the replica's JSON document
     content_hash: str
-    doc_type: DocumentType = attr.ib(default=DocumentType.replica, init=False)
 
     @property
     def document_id(self) -> str:
@@ -1481,18 +1487,19 @@
     A verbatim copy of a metadata document
     """
 
-    #: The type of replica, i.e., what sort of metadata document in the
+    #: The type of replica, i.e., what sort of metadata document from the
     #: underlying data repository we are storing a copy of. Conceptually related
     #: to the entity type, but its value may be different from the entity type.
     #: For example, AnVIL replicas use the name of the data table that contains
-    #: the entity, e.g. "anvil_file", instead of just "file".
+    #: the entity, e.g. 'anvil_file', instead of just 'file'.
+    #:
     #: We can't model replica types as entity types because we want to hold all
-    #: replicas  in a single index per catalog to facilitate quick retrieval.
+    #: replicas in a single index per catalog to facilitate quick retrieval.
     #: Typically, all replicas of the same type have similar shapes, just like
-    #: contributions for entities of the same type. Mixing replicas of different
-    #: types results in an index containing documents of heterogeneous shapes.
-    #: Document heterogeneity is typically a problem for ES, but we deal with it
-    #: by disabling the ES index mapping, essentially disabling the reverse
+    #: contributions for entities of the same type. However, mixing replicas of
+    #: different types results in an index containing documents of heterogeneous
+    #: shapes. Document heterogeneity is a problem for ES, but we deal with it
+    #: by disabling the ES index mapping, essentially turning off the reverse
     #: index that ES normally builds from these documents and using the index
     #: only to store and retrieve the documents by their coordinates.
     replica_type: str
Index: src/azul/indexer/transform.py
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/src/azul/indexer/transform.py b/src/azul/indexer/transform.py
--- a/src/azul/indexer/transform.py	(revision c34ea4510c4fab5d255781e52b6ce451f96bcc0f)
+++ b/src/azul/indexer/transform.py	(date 1702517386929)
@@ -58,6 +58,7 @@
     def replica_type(self, entity: EntityReference) -> str:
         """
         The type of replica emitted by this transformer.
+
         See :py:attr:`Replica.replica_type`
         """
         raise NotImplementedError
```

**Comment by nadove-ucsc** [comment]
This patch

```
===================================================================
diff --git a/src/azul/indexer/document.py b/src/azul/indexer/document.py
--- a/src/azul/indexer/document.py	(revision c34ea4510c4fab5d255781e52b6ce451f96bcc0f)
+++ b/src/azul/indexer/document.py	(date 1702514785290)
@@ -376,7 +376,7 @@
         if index_name[-1] == 'aggregate':
             *index_name, _ = index_name
             doc_type = DocumentType.aggregate
-        elif index_name == ['replica']:
+        elif one(index_name) == 'replica':
             doc_type = DocumentType.replica
         else:
             doc_type = DocumentType.contribution
@@ -621,8 +621,14 @@
```
does not work because

```
Error
Traceback (most recent call last):
  File "/home/nadove/PycharmProjects/azul-sc/test/indexer/test_indexer.py", line 1657, in test_accessions_fields
    self._index_canned_bundle(bundle_fqid)
  File "/home/nadove/PycharmProjects/azul-sc/test/indexer/__init__.py", line 193, in _index_canned_bundle
    cls._index_bundle(bundle, delete=delete)
  File "/home/nadove/PycharmProjects/azul-sc/test/indexer/__init__.py", line 201, in _index_bundle
    cls.index_service.index(cls.catalog, bundle)
  File "/home/nadove/PycharmProjects/azul-sc/src/azul/indexer/index_service.py", line 206, in index
    self.aggregate(tallies)
  File "/home/nadove/PycharmProjects/azul-sc/src/azul/indexer/index_service.py", line 463, in aggregate
    contributions = self._read_contributions(total_tallies)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/nadove/PycharmProjects/azul-sc/src/azul/indexer/index_service.py", line 631, in _read_contributions
    contributions = [
                    ^
  File "/home/nadove/PycharmProjects/azul-sc/src/azul/indexer/index_service.py", line 632, in <listcomp>
    Contribution.from_index(self.catalogued_field_types(), hit)
  File "/home/nadove/PycharmProjects/azul-sc/src/azul/indexer/document.py", line 1253, in from_index
    coordinates = DocumentCoordinates.from_hit(hit)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/nadove/PycharmProjects/azul-sc/src/azul/indexer/document.py", line 492, in from_hit
    index_name = IndexName.parse(hit['_index'])
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/nadove/PycharmProjects/azul-sc/src/azul/indexer/document.py", line 379, in parse
    elif one(index_name) == 'replica':
         ^^^^^^^^^^^^^^^
  File "/home/nadove/PycharmProjects/azul-sc/.venv/lib/python3.11/site-packages/more_itertools/more.py", line 554, in one
    raise too_long or ValueError(msg)
ValueError: Expected exactly one item in iterable, but got 'cell', 'suspensions', and perhaps more.
```

**Comment by nadove-ucsc** [comment]
> REVIEW: This class inherits the test methods from the base class. I think
>                 they won't be run twice but please double-check. Either way, it
>                 might be more clean to extract a test case class.

The tests _were_ in fact being run twice.

**Review by hannes-ucsc — DISMISSED** [review]

**Comment by hannes-ucsc** [comment]
Hammerbox build failed in `test` job.

**Comment by nadove-ucsc** [comment]
I reproduced the failure by `_select`ing `hammerbox` and running the failed tests locally. They now pass.

**Review by hannes-ucsc — APPROVED** [review]

**Pull request merged**
