### PR TITLE
Upload velocity report to Gitlab wiki (#2229)

### PR DESCRIPTION
**Pull request by natanlao**
Author (before primary review)

- [x] PR title references issue
- [x] Title of main commit references issue
- [x] PR is linked to Zenhub issue
- [x] Added `HCA` label <sub>or this PR does not target an `hca/*` branch</sub>
- [x] Created issue to track porting these changes <sub>or this PR does not need porting</sub> 
- [x] Added `[r]` prefix at start of commit title <sub>or this PR does not require reindexing</sub>
- [x] Added `reindex` label <sub>or this PR does not require reindexing</sub>
- [x] Freebies are blocked on this PR <sub>or there are no freebies in this PR</sub>
- [x] Freebies are referenced in commit titles <sub>or there are no freebies in this PR</sub>
- [x] This PR is blocked by previous PR in chain <sub>or this PR is not chained to another PR</sub>
- [x] Added `chain` label to the blocking PR <sub>or this PR is not chained to another PR</sub>
- [x] Ran `make requirements_update` <sub>or this PR does not change requirements*.txt</sub>
- [x] Mentioned `make requirements` in UPGRADING.rst <sub>or this PR does not change requirements*.txt</sub>
- [x] Documented upgrade of personal deployments in UPGRADING.rst <sub>or this PR does not require upgrading</sub>

Primary reviewer (before pushing merge commit)

- [x] Checked `reindex` label and `[r]` prefix of commit title
- [x] Rebased and squashed branch
- [x] Sanity-checked history
- [x] Build passes in `sandbox` <sub>or commented that sandbox will be skipped</sub>
- [x] Reindexed `sandbox` <sub>or this PR does not require reindexing</sub>
- [x] Added PR reference to merge commit

Primary reviewer (after pushing merge commit)

- [x] Moved linked issue to Merged
- [x] Pushed merge commit to Github
- [x] Moved freebies to Merged column <sub>or there are no freebies in this PR</sub> 
- [x] Shortened chain <sub>or this PR is not the base of another PR</sub>
- [x] Verified that `N reviews` labelling is accurate
- [x] Commented on demo expectations <sub>or labeled as `no demo`</sub>
- [x] Pushed merge commit to Gitlab
- [ ] Reindexed `dev` <sub>or this PR does not require reindexing</sub>
- [ ] Deleted PR branch from Github and Gitlab
- [ ] Unassign reviewer from PR

### CODE REVIEW

**Review by hannes-ucsc — CHANGES_REQUESTED** [review]
Move to attic instead of deleting.

**Comment by natanlao** [comment]
@hannes-ucsc Changing the action to upload to Gitlab instead was more straightforward than anticipated, so I've renamed this PR and force-pushed with the revised action. (If you'd prefer, I am happy to close this PR and open a new one.)

**Review by hannes-ucsc — APPROVED** [review]

**Comment by hannes-ucsc** [comment]
Skipping sandbox.

**Comment by hannes-ucsc** [comment]
For demo, show published report on Gitlab.

**Pull request merged**
