### PR TITLE
Fix: On replacement, TF creates ES domain before deleting it (#4752, #3652, #2992)

### LINKED ISSUE #2992: Cycle error when removing AWS Lambda functions
https://github.com/DataBiosphere/azul/pull/2969/files#r614245068

which is a manifestation of 

https://github.com/hashicorp/terraform-provider-aws/issues/11344

and despite my best efforts to follow the best practices

https://github.com/hashicorp/terraform-provider-aws/issues/11344#issuecomment-820979896

I wasn't able to fix. Here's what I tried:

```diff
Index: terraform/api_gateway.tf.json.template.py
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/terraform/api_gateway.tf.json.template.py b/terraform/api_gateway.tf.json.template.py
--- a/terraform/api_gateway.tf.json.template.py	(revision d744515d69031d45c51bc2698f61b5c1e446a6d5)
+++ b/terraform/api_gateway.tf.json.template.py	(date 1618556411997)
@@ -91,16 +91,17 @@
     # Note that ${} references exist to interpolate a value AND express a dependency.
     "resource": [
         {
-            "aws_api_gateway_deployment": {
+            "aws_api_gateway_stage": {
                 lambda_.name: {
                     "rest_api_id": "${module.chalice_%s.rest_api_id}" % lambda_.name,
+                    "deployment_id": "${module.chalice_%s.rest_api_deployment_id}" % lambda_.name,
                     "stage_name": config.deployment_stage
                 }
             },
             "aws_api_gateway_base_path_mapping": {
                 f"{lambda_.name}_{i}": {
                     "api_id": "${module.chalice_%s.rest_api_id}" % lambda_.name,
-                    "stage_name": "${aws_api_gateway_deployment.%s.stage_name}" % lambda_.name,
+                    "stage_name": "${aws_api_gateway_stage.%s.stage_name}" % lambda_.name,
                     "domain_name": "${aws_api_gateway_domain_name.%s_%i.domain_name}" % (lambda_.name, i)
                 }
                 for i, domain in enumerate(lambda_.domains)
@@ -139,12 +140,12 @@
                 **{
                     f"{lambda_.name}_domain_validation_{i}": {
                         **{
-                            key: "${aws_acm_certificate.%s_%i.domain_validation_options.0.resource_record_%s}"
+                            key: "${tolist(aws_acm_certificate.%s_%i.domain_validation_options)[0].resource_record_%s}"
                                  % (lambda_.name, i, key) for key in ('name', 'type')
                         },
                         "zone_id": "${data.aws_route53_zone.%s.id}" % zones_by_domain[domain].slug,
                         "records": [
-                            "${aws_acm_certificate.%s_%i.domain_validation_options.0.resource_record_value}" % (
+                            "${tolist(aws_acm_certificate.%s_%i.domain_validation_options)[0].resource_record_value}" % (
                                 lambda_.name, i)
                         ],
                         "ttl": 60
Index: scripts/prepare_lambda_deployment.py
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/scripts/prepare_lambda_deployment.py b/scripts/prepare_lambda_deployment.py
--- a/scripts/prepare_lambda_deployment.py	(revision d744515d69031d45c51bc2698f61b5c1e446a6d5)
+++ b/scripts/prepare_lambda_deployment.py	(date 1618588893832)
@@ -35,9 +35,28 @@
         'es_instance_count': {}
     }
 
-    input_json['output']['rest_api_id'] = {
+    output = input_json['output']
+    output['rest_api_id'] = {
         'value': '${aws_api_gateway_rest_api.rest_api.id}'
     }
+    output['rest_api_deployment_id'] = {
+        'value': '${aws_api_gateway_deployment.rest_api.id}'
+    }
+
+    # The Terraform documentation recommends that we don't use the an
+    # implicitly created stage but an explicitly defined one. The explicit
+    # stage is in `api_gateway.tf.json.template.py`. To disable the implicit
+    # stage, we need to remove the `stage_name` and `stage_description`
+    # properties from the Chalice-generted TF config. Chalice hijacks the
+    # `stage_description` to trigger redeployment whenever the REST API
+    # definition changes. The more `triggers` property recently introduced by
+    # the TF AWS provider does the same without any hijacking.
+    #
+    # https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/api_gateway_deployment
+    #
+    deployment = input_json['resource']['aws_api_gateway_deployment']['rest_api']
+    assert deployment.pop('stage_name') == config.deployment_stage
+    deployment['triggers'] = {'redeployment': deployment.pop('stage_description')}
 
     for func in input_json['resource']['aws_lambda_function'].values():
         assert 'layers' not in func
Index: terraform/providers.tf.json.template.py
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/terraform/providers.tf.json.template.py b/terraform/providers.tf.json.template.py
--- a/terraform/providers.tf.json.template.py	(revision d744515d69031d45c51bc2698f61b5c1e446a6d5)
+++ b/terraform/providers.tf.json.template.py	(date 1618588241560)
@@ -24,7 +24,7 @@
         },
         *({
             "aws": {
-                'version': '2.70.0',
+                'version': '3.36.0',
                 **(
                     {
                         'region': region,
Index: terraform/Makefile
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/terraform/Makefile b/terraform/Makefile
--- a/terraform/Makefile	(revision d744515d69031d45c51bc2698f61b5c1e446a6d5)
+++ b/terraform/Makefile	(date 1618554016988)
@@ -14,9 +14,12 @@
 init: providers config
 	terraform init
 
-.PHONY: rename_resources
-rename_resources: init
+.PHONY: prepare_state
+prepare_state: init
 	python $(project_root)/scripts/rename_resources.py
+	# FIXME: Remove once it has been run on all deployments
+	#        https://github.com/DataBiosphere/azul/issues/2991
+	python $(project_root)/scripts/import_api_gateway_stage.py
 
 .PHONY: validate
 validate: init
@@ -27,14 +30,14 @@
 	terraform plan
 
 .PHONY: apply
-apply: validate rename_resources
+apply: validate prepare_state
 	$(MAKE) unlink_health_checks
 	terraform apply
 	$(MAKE) link_health_checks
 	$(MAKE) grafana
 
 .PHONY: auto_apply
-auto_apply: validate rename_resources
+auto_apply: validate prepare_state
 	$(MAKE) unlink_health_checks
 	terraform apply -auto-approve
 	$(MAKE) link_health_checks
Index: lambdas/service/Makefile
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/lambdas/service/Makefile b/lambdas/service/Makefile
--- a/lambdas/service/Makefile	(revision d744515d69031d45c51bc2698f61b5c1e446a6d5)
+++ b/lambdas/service/Makefile	(date 1618553522983)
@@ -5,7 +5,7 @@
 include ../lambdas.mk
 
 .PHONY: package
-package: check_branch check_python check_aws config compile
+package: check_branch check_python check_aws config compile $(project_root)/scripts/prepare_lambda_deployment.py
 	python -m azul.changelog vendor
 	chalice package --stage $(AZUL_DEPLOYMENT_STAGE) --pkg-format terraform .chalice/terraform
 	python $(project_root)/scripts/prepare_lambda_deployment.py service
Index: scripts/import_api_gateway_stage.py
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/scripts/import_api_gateway_stage.py b/scripts/import_api_gateway_stage.py
new file mode 100644
--- /dev/null	(date 1618553522983)
+++ b/scripts/import_api_gateway_stage.py	(date 1618553522983)
@@ -0,0 +1,46 @@
+import boto3
+from more_itertools import (
+    one,
+)
+
+from azul import (
+    config,
+)
+from azul.logging import (
+    configure_script_logging,
+)
+from azul.terraform import (
+    terraform,
+)
+
+
+def main():
+    def resource(name):
+        return 'aws_api_gateway_stage.' + name
+
+    resources = terraform.run('state', 'list').splitlines()
+    names = {
+        name
+        for name in ('service', 'indexer')
+        if resource(name) not in resources
+    }
+    if names:
+        api_gateway = boto3.client('apigateway')
+        apis = api_gateway.get_rest_apis()
+        for name in names:
+            qname = config.qualified_resource_name(name)
+            matching_apis = (
+                api['id']
+                for api in apis['items']
+                if api['name'] == qname
+            )
+            api_id = one(matching_apis, too_short=None)
+            if api_id is not None:
+                terraform.run('import',
+                              resource(name),
+                              f'{api_id}/{config.deployment_stage}')
+
+
+if __name__ == '__main__':
+    configure_script_logging()
+    main()
Index: lambdas/indexer/Makefile
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/lambdas/indexer/Makefile b/lambdas/indexer/Makefile
--- a/lambdas/indexer/Makefile	(revision d744515d69031d45c51bc2698f61b5c1e446a6d5)
+++ b/lambdas/indexer/Makefile	(date 1618553522983)
@@ -5,7 +5,7 @@
 include ../lambdas.mk
 
 .PHONY: package
-package: check_branch check_python check_aws config compile
+package: check_branch check_python check_aws config compile $(project_root)/scripts/prepare_lambda_deployment.py
 	python -m azul.changelog vendor
 	chalice package --stage $(AZUL_DEPLOYMENT_STAGE) --pkg-format terraform .chalice/terraform
 	python $(project_root)/scripts/prepare_lambda_deployment.py indexer
```

still getting

```
Plan: 2 to add, 15 to change, 11 to destroy.

Do you want to perform these actions?
  Terraform will perform the actions described above.
  Only 'yes' will be accepted to approve.

  Enter a value: yes


Error: Cycle: module.chalice_service.output.rest_api_deployment_id, module.chalice_service.output.rest_api_id, aws_api_gateway_stage.service, module.chalice_service.aws_api_gateway_deployment.rest_api (destroy deposed 8918b663), module.chalice_service.aws_lambda_function.jwt_auth (destroy), module.chalice_service.aws_api_gateway_rest_api.rest_api, module.chalice_service.aws_api_gateway_deployment.rest_api


make[1]: *** [Makefile:35: apply] Error 1
make[1]: Leaving directory '/home/hannes/workspace/hca/azul/terraform'
make: *** [Makefile:81: deploy] Error 2
```

during `terraform apply` against a deployment that's on the base commit of https://github.com/DataBiosphere/azul/pull/2969 (064f2c1b on develop) with the PR branch checked out and the above patch applied. The same happens if I apply the patch to the base commit, then deploy (which succeeds), then switch to the PR branch and try to deploy again.

There are some other changes mixed in, most prominently a fix for https://github.com/DataBiosphere/azul/issues/1951 which we may fix before this one, so expect conflicts when applying the patch above.

### LINKED ISSUE #3652: Running `make -C terraform plan` shouldn't upload layers to S3
add FIXME for `make -C terraform plan` uploads layers to s3.

```diff
Index: lambdas/Makefile
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/lambdas/Makefile b/lambdas/Makefile
--- a/lambdas/Makefile	(revision 39e1643b2804291e611017e5b82b8440aa0b2ead)
+++ b/lambdas/Makefile	(date 1637268693671)
@@ -1,5 +1,5 @@
 .PHONY: all
-all: layer indexer service
+all: indexer service
 
 include ../common.mk
 
Index: terraform/Makefile
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/terraform/Makefile b/terraform/Makefile
--- a/terraform/Makefile	(revision 39e1643b2804291e611017e5b82b8440aa0b2ead)
+++ b/terraform/Makefile	(date 1637268693679)
@@ -27,11 +27,11 @@
 	terraform plan
 
 .PHONY: apply
-apply: validate rename_resources
+apply: validate layer rename_resources
 	terraform apply
 
 .PHONY: auto_apply
-auto_apply: validate rename_resources
+auto_apply: validate layer rename_resources
 	terraform apply -auto-approve
 
 .PHONY: destroy
@@ -67,3 +67,7 @@
 .PHONY: lambdas
 lambdas:
 	$(MAKE) -C $(project_root)/lambdas
+
+.PHONY: layer
+layer:
+	$(MAKE) -C $(project_root)/lambdas/layer
\ No newline at end of file

```

### LINKED ISSUE #4752: On replacement, TF creates ES domain before deleting it
https://gitlab.dev.singlecell.gi.ucsc.edu/ucsc/azul/-/jobs/57136

Note `+/- create replacement and then destroy` and `+/- resource "aws_elasticsearch_domain" "index"` in the plan, indicating create-before-destroy semantics even though `create_before_destroy` lifecycle property is absent and should be defaulting to `False`. I even tried with `create_before_destroy` explicitly set to `False`.

When TF attempts to create the domain, the creation obviously fails with `Elasticsearch Domain (azul-index-sandbox) already exists`.

### PR DESCRIPTION
**Pull request by hannes-ucsc**
Connected issues: #4752, #3652, #2992

### Author

- [x] Target branch is `develop`
- [x] Name of PR branch matches `issues/<GitHub handle of author>/<issue#>-<slug>`
- [x] PR title references all connected issues
- [x] PR title matches<sup>1</sup> that of a connected issue        <sub>or comment in PR explains why they're different</sub>
- [x] For each connected issue, there is at least one commit whose title references that issue
- [x] PR is connected to all connected issues via Zenhub 
- [x] PR description links to connected issues
- [x] Added `partial` label to PR                                   <sub>or this PR completely resolves all connected issues</sub>

<sup>1</sup> when the issue title describes a problem, the corresponding PR title is `Fix: ` followed by the issue title   

### Author (reindex)

- [x] Added `r` tag to commit title                                 <sub>or this PR does not require reindexing</sub>
- [x] Added `reindex` label to PR                                   <sub>or this PR does not require reindexing</sub>

### Author (chains)

- [x] This PR is blocked by previous PR in the chain               <sub>or this PR is not chained to another PR</sub>
- [x] Added `base` label to the blocking PR                        <sub>or this PR is not chained to another PR</sub>
- [x] Added `chained` label to this PR                             <sub>or this PR is not chained to another PR</sub>

### Author (upgrading)

- [x] Documented upgrading of deployments in UPGRADING.rst          <sub>or this PR does not require upgrading</sub>
- [x] Added `u` tag to commit title                                 <sub>or this PR does not require upgrading</sub>
- [x] Added `upgrade` label to PR                                   <sub>or this PR does not require upgrading</sub>

### Author (operator tasks)

- [x] Added checklist items for additional operator tasks           <sub>or this PR does not require additional tasks</sub>

### Author (hotfixes)

- [x] Added `F` tag to main commit title                            <sub>or this PR does not include permanent fix for a temporary hotfix</sub>
- [x] Reverted the temporary hotfixes for any connected issues      <sub>or the `prod` branch has no temporary hotfixes for any connected issues</sub>

### Author (requirements, before every review)

- [x] Ran `make requirements_update`                                <sub>or this PR does not touch requirements*.txt, common.mk, Makefile and Dockerfile</sub>
- [x] Added `R` tag to commit title                                 <sub>or this PR does not touch requirements*.txt</sub>
- [x] Added `reqs` label to PR                                      <sub>or this PR does not touch requirements*.txt</sub>

### Author (rebasing, integration test)

- [x] `make integration_test` passes in personal deployment         <sub>or this PR does not touch functionality that could break the IT</sub>
- [x] Rebased PR branch on `develop`, squashed old fixups

### Peer reviewer (after requesting changes)

Uncheck the *Author (requirements)* and *Author (rebasing, integration test)* 
checklists.

### Peer reviewer (after approval)

- [x] Ticket is in *Review requested* column
- [x] Requested review from primary reviewer
- [x] Assigned PR to primary reviewer

### Primary reviewer (after requesting changes)

Uncheck the *Author (requirements)* and *Author (rebasing, integration test)* 
checklists. Update the `N reviews` label. 

### Primary reviewer (after approval)

- [x] Actually approved the PR
- [x] Labeled connected issues as `demo` or `no demo`
- [x] Commented on connected issues about demo expectations         <sub>or all connected issues are labeled `no demo`</sub>
- [x] Decided if PR can be labeled `no sandbox`
- [x] PR title is appropriate as title of merge commit
- [x] `N reviews` label is accurate
- [x] Moved ticket to *Approved* column
- [x] Assigned PR to current operator

### Operator (before pushing merge the commit)

- [x] Checked `reindex` label and `r` commit title tag
- [x] Checked that demo expectations are clear                      <sub>or all connected issues are labeled `no demo`</sub>
- [x] Rebased and squashed PR branch
- [x] Sanity-checked history
- [x] Pushed PR branch to GitHub
- [x] Pushed PR branch to GitLab `dev` and added `sandbox` label    <sub>or PR is labeled `no sandbox`</sub>
- [x] Build passes in `sandbox` deployment                          <sub>or PR is labeled `no sandbox`</sub>
- [x] Reviewed build log for anomalies in `sandbox` deployment      <sub>or PR is labeled `no sandbox`</sub>
- [x] Deleted unreferenced indices in `sandbox`                     <sub>or this PR does not remove catalogs or otherwise causes unreferenced indices</sub> 
- [x] Started reindex in `sandbox`                                  <sub>or this PR does not require reindexing `sandbox`</sub>
- [x] Checked for failures in `sandbox`                             <sub>or this PR does not require reindexing `sandbox`</sub>
- [x] Pushed PR branch to GitLab `anvildev`                         <sub>or PR is labeled `no sandbox`</sub>
- [x] Build passes in `anvilbox` deployment                         <sub>or PR is labeled `no sandbox`</sub>
- [x] Reviewed build log for anomalies in `anvilbox` deployment     <sub>or PR is labeled `no sandbox`</sub>
- [x] Deleted unreferenced indices in `anvilbox`                    <sub>or this PR does not remove catalogs or otherwise causes unreferenced indices</sub> 
- [x] Started reindex in `anvilbox`                                 <sub>or this PR does not require reindexing `sandbox`</sub>
- [x] Checked for failures in `anvilbox`                            <sub>or this PR does not require reindexing `sandbox`</sub>
- [x] Added PR reference to merge commit title
- [x] Collected commit title tags in merge commit title
- [x] Moved connected issues to Merged column
- [x] Pushed merge commit to GitHub

### Operator (after pushing the merge commit)

- [x] Notify team about upgrade, the fact that it's a two-step process and can't be combined with other upgrades
- [x] Shortened the PR chain                                        <sub>or this PR is not labeled `base`</sub>
- [x] Pushed merge commit to GitLab `dev`                           <sub>or PR is labeled `no sandbox`</sub>
- [x] Pushed merge commit to GitLab `anvildev`                      <sub>or PR is labeled `no sandbox`</sub>
- [x] Build passes on GitLab `dev`<sup>1</sup>
- [x] Reviewed build log for anomalies on GitLab `dev`<sup>1</sup>
- [x] Build passes on GitLab `anvildev`<sup>1</sup>
- [x] Reviewed build log for anomalies on GitLab `anvildev`<sup>1</sup>
- [x] Deleted PR branch from GitHub
- [x] Deleted PR branch from GitLab `dev`
- [x] Deleted PR branch from GitLab `anvildev`

<sup>1</sup> When pushing the merge commit is skipped due to the PR being
labelled `no sandbox`, the next build triggered by a PR whose merge commit *is* 
pushed determines this checklist item.

### Operator (reindex) 

- [x] Deleted unreferenced indices in `dev`                         <sub>or this PR does not remove catalogs or otherwise causes unreferenced indices</sub> 
- [x] Deleted unreferenced indices in `anvildev`                    <sub>or this PR does not remove catalogs or otherwise causes unreferenced indices</sub> 
- [x] Started reindex in `dev`                                      <sub>or this PR does not require reindexing</sub>
- [x] Started reindex in `anvildev`                                 <sub>or this PR does not require reindexing</sub>
- [x] Checked for and triaged indexing failures in `dev`            <sub>or this PR does not require reindexing</sub>
- [x] Checked for and triaged indexing failures in `anvildev`       <sub>or this PR does not require reindexing</sub>
- [x] Emptied fail queues in `dev` deployment                       <sub>or this PR does not require reindexing</sub>
- [x] Emptied fail queues in `anvildev` deployment                  <sub>or this PR does not require reindexing</sub>

### Operator

- [x] Unassigned PR

## Shorthand for review comments

- `L` line is too long
- `W` line wrapping is wrong
- `Q` bad quotes
- `F` other formatting problem

### CODE REVIEW

**Comment by hannes-ucsc** [comment]
The LGTM findings are for a file in the attic. Since LGTM is EOL I'd rather not worry about excluding the attic from LGTM code extraction.

**Comment by dsotirho-ucsc** [comment]
Failed `deploy` step on GitLab `anvil`.
https://gitlab.anvil.gi.ucsc.edu/ucsc/azul/-/jobs/5965

```
Traceback (most recent call last):
  File "/builds/ucsc/azul/terraform/api_gateway.tf.json.template.py", line 127, in <module>
    *[
  File "/builds/ucsc/azul/terraform/api_gateway.tf.json.template.py", line 129, in <listcomp>
    **chalice.tf_config(app.name)['data'],
  File "/builds/ucsc/azul/src/azul/terraform.py", line 615, in tf_config
    rest_api = resources['aws_api_gateway_rest_api']['rest_api']
KeyError: 'rest_api'
```

**Comment by dsotirho-ucsc** [comment]
Failed `deploy` job on GitLab `anvil`
https://gitlab.anvil.gi.ucsc.edu/ucsc/azul/-/jobs/5978

```
Creating lambda_layer.tf.json
terraform validate
╷
│ Error: Duplicate data "aws_network_interface" configuration
│ 
│   on api_gateway.tf.json line 76, in data[1].aws_network_interface:
│   76:                 "indexer": {
│ 
│ A aws_network_interface data resource named "indexer" was already declared
│ at api_gateway.tf.json:55,28-29. Resource names must be unique per type in
│ each module.
╵
╷
│ Error: Duplicate data "aws_network_interface" configuration
│ 
│   on api_gateway.tf.json line 93, in data[2].aws_network_interface:
│   93:                 "service": {
│ 
│ A aws_network_interface data resource named "service" was already declared
│ at api_gateway.tf.json:59,28-29. Resource names must be unique per type in
│ each module.
╵
make[1]: Leaving directory '/builds/ucsc/azul/terraform'
make[1]: *** [Makefile:33: validate] Error 1
make: *** [Makefile:103: auto_terraform] Error 2
```

**Review by nadove-ucsc — APPROVED** [review]
pro-forma approval

**Review by dsotirho-ucsc — APPROVED** [review]

**Comment by hannes-ucsc** [comment]
@danielsotirhos it appears you checked the box but didn't actually delete the branch.

**Pull request merged**
