### PR TITLE
Adjust reindex dynamic timeout (#2147)

### PR DESCRIPTION
**Pull request by achave11**
Author (before primary review)

- [x] PR title references issue
- [x] Title of main commit references issue
- [x] PR is linked to Zenhub issue
- [x] Added `DCP/1` label <sub>or this PR does not target an `hca/*` branch</sub>
- [x] Created issue to track porting these changes <sub>or this PR does not need porting</sub> 
- [x] Added `[r]` prefix at start of commit title <sub>or this PR does not require reindexing</sub>
- [x] Added `reindex` label <sub>or this PR does not require reindexing</sub>
- [x] Freebies are blocked on this PR <sub>or there are no freebies in this PR</sub>
- [x] Freebies are referenced in commit titles <sub>or there are no freebies in this PR</sub>
- [x] This PR is blocked by previous PR in chain <sub>or this PR is not chained to another PR</sub>
- [x] Added `chain` label to the blocking PR <sub>or this PR is not chained to another PR</sub>
- [x] Ran `make requirements_update` <sub>or this PR does not change requirements*.txt</sub>
- [x] Mentioned `make requirements` in UPGRADING.rst <sub>or this PR does not change requirements*.txt</sub>
- [x] Documented upgrade of personal deployments in UPGRADING.rst <sub>or this PR does not require upgrading</sub>

Primary reviewer (before pushing merge commit)

- [ ] Checked `reindex` label and `[r]` prefix of commit title
- [ ] Rebased and squashed branch
- [ ] Sanity-checked history
- [ ] Build passes in `sandbox` <sub>or commented that sandbox will be skipped</sub>
- [ ] Reindexed `sandbox` <sub>or this PR does not require reindexing</sub>
- [ ] Added PR reference to merge commit
- [ ] Moved linked issue to Merged
- [ ] Pushed merge commit to Github

Primary reviewer (after pushing merge commit)

- [ ] Moved freebies to Merged column <sub>or there are no freebies in this PR</sub> 
- [ ] Shortened chain <sub>or this PR is not the base of another PR</sub>
- [ ] Verified that `N reviews` labelling is accurate
- [ ] Commented on demo expectations <sub>or labeled as `no demo`</sub>
- [ ] Pushed merge commit to Gitlab
- [ ] Reindexed `dev` <sub>or this PR does not require reindexing</sub>
- [ ] Deleted PR branch from Github and Gitlab
- [ ] Unassign reviewer from PR

### CODE REVIEW

**Review by jessebrennan — APPROVED** [review]
This looks good, but I'm kind of confused because, looking at the ticket, I thought the time needed to be decreased.

**Comment by achave11** [comment]
@jessebrennan 
> This looks good, but I'm kind of confused because, looking at the ticket, I thought the time needed to be decreased.

The ticket did specify …
> [We'll probably just need to adjust the assumed bundles/minute rate of processing.](https://github.com/DataBiosphere/azul/issues/2147#issuecomment-673021902)

… for the temporary doubling of the timeouts used by Gitlab and the reindex queue waiter (I think). In this PR that temporary increase was readjusted to account for the addition of the new catalog (i.e. "doubling" of the data being indexed). So while we saw an increase from the original parameters for indexing DSS data only, there was a decrease from the temporary doubling of the same parameters.
Otherwise, I am unsure as to what time you are referring to.

**Review by hannes-ucsc — COMMENTED** [review]
Could you briefly document how you chose the adjusted timeouts?

I think this should be re=evaluated after the PR #2317 for #2189 lands and PR #2308 for #2281 land.

**Comment by achave11** [comment]
> Could you briefly document how you chose the adjusted timeouts?

The following [Gitlab job](https://gitlab.dev.singlecell.gi.ucsc.edu/ucsc/azul/-/jobs/6164) was used as reference. The notifications queue peaked at 00:54:13,753 with 287012 notifications and ended at 08:12:20,099 with 091171 notifications remaining to be processed. This indicates that in a period of 07:18:07:346 hours (26287 sec), 195841 notifications where processed. 
```
time = 26287
notifications = 195841
```
Using …
```
total_timeout = seconds_per_notification * (num_notifications / concurrent_lambdas) =>
seconds_per_notification = total_timeout * (lambda_concurrency / num_notifications)
```
… from [here](https://github.com/DataBiosphere/azul/blob/f9380c09af62259b8f5b5576183db387259dec1d/src/azul/queues.py#L280) with the previously mentioned `time` and `notifications` we get the following. 
```
seconds_per_notification = (26287s * 64lambda_concurrency) / 195841 notifications =>
8.59 sec/notification
```
Using the same formula we get …
```
total_time = 34161s, # Actual time used by the Gitlab job runner (assuming setup time is marginal) 
notifications = 287012, 
seconds_per_notification = (34161sec * 64lambda_concurrency) / 287012 notifications =>
7.62 s/notification
``` 
… for the overall run. Which is why 8 was chosen as an integer with a close average between both
8.59 and 7.62. 
The maximum timeout was determined by 
```
8.59 s/notifications * (287012notifications / 64lambda_concurrency) = 10.7 Hours
``` 
rounding up to 11. 
And the `min_timeout` was an approx. 33% increase, up to 13 min, similar in proportion to the increase in notifications/second value.

**Comment by hannes-ucsc** [comment]
I see two issues with the above approach: it only takes into account a single job, a relatively old one at that (three weeks). We did two reindex jobs on develop this week and their running time varies by around 10%. The other issue is that it only takes into account progress made until the log was truncated. I've seen really odd throughput variations during indexing:

image

I don't think we can extrapolate assuming constant throughput.

Can you rerun your calculation using the job time reported by Gitlab and using the longest reindex job?

**Review by hannes-ucsc — APPROVED** [review]
Looks good. For now, please just hold it warm until it's unblocked. We may have to readjust the formula once the blockers land.

**Comment by achave11** [comment]
The [last reindex on dev](https://gitlab.dev.singlecell.gi.ucsc.edu/ucsc/azul/-/jobs/7127) contained some bugs. Therefore it should not be used to calculate time per worker to index a notification. Wait until next reindex to proceed with this ticket.

**Comment by hannes-ucsc** [comment]
I think the constant values in this PR already obsolete. The indexing time per bundle is highly dependent on a set of factors that are ever changing. I think we should move away from using timeouts to detecting a stall.

**Comment by hannes-ucsc** [comment]
https://github.com/databiosphere/azul/issues/2147#issuecomment-742882084

**Pull request closed without merging**
