### PR TITLE
Fix: HPRC Dataset should be dropped from anvil3 (#5690)

### LINKED ISSUE #5690: HPRC Dataset should be dropped from anvil3
Earlier today I was looking at https://prod.anvil.gi.ucsc.edu/explore/datasets and noticed that [ANVIL_HPRC](https://prod.anvil.gi.ucsc.edu/explore/datasets/6a15c882-2eb5-41af-9bf6-00b9ccdfad22) was included. 

This dataset has a number of temporary files in it should not have, resulting in a large number of file formats showing up in the Data Explorer (e.g., 9583 formats).  The HPRC team is in the process of cleaning them up.

It was my understanding that we were going to drop this dataset from the index until it is cleaned up.   

This ticket is to request the dropping of the ANVIL_HPRC dataset until the file issue is resolved.

- [x] Security design review completed; the Resolution of this issue does **not** …
  - [x] … affect authentication; for example:
    - OAuth 2.0 with the application (API or Swagger UI)
    - Authentication of developers with Google Cloud APIs
    - Authentication of developers with AWS APIs
    - Authentication with a GitLab instance in the system
    - Password and 2FA authentication with GitHub
    - API access token authentication with GitHub
    - Authentication with 
  - [x] … affect the permissions of internal users like access to
    - Cloud resources on AWS and GCP
    - GitLab repositories, projects and groups, administration
    - an EC2 instance via SSH
    - GitHub issues, pull requests, commits, commit statuses, wikis, repositories, organizations
  - [x] … affect the permissions of external users like access to
    - TDR snapshots
  - [x] … affect permissions of service or bot accounts
    - Cloud resources on AWS and GCP
  - [x] … affect audit logging in the system, like
    - adding, removing or changing a log message that represents an auditable event
    - changing the routing of log messages through the system
  - [x] … affect monitoring of the system
  - [x] … introduce a new software dependency like
    - Python packages on PYPI
    - Command-line utilities
    - Docker images
    - Terraform providers
  - [x] … add an interface that exposes sensitive or confidential data at the security boundary
  - [x] … affect the encryption of data at rest
  - [x] … require persistence of sensitive or confidential data that might require encryption at rest
  - [x] … require unencrypted transmission of data within the security boundary
  - [x] … affect the network security layer; for example by 
    - modifying, adding or removing firewall rules
    - modifying, adding or removing security groups
    - changing or adding a port a service, proxy or load balancer listens on
- [x] Documentation on any unchecked boxes is provided in comments below

### PR DESCRIPTION
**Pull request by achave11-ucsc**
Connected issues: #5690

### Author

- [x] PR is a draft
- [x] Target branch is `develop`
- [x] Name of PR branch matches `issues/<GitHub handle of author>/<issue#>-<slug>`
- [x] PR title references all connected issues
- [x] PR title matches<sup>1</sup> that of a connected issue <sub>or comment in PR explains why they're different</sub>
- [x] For each connected issue, there is at least one commit whose title references that issue
- [x] PR is connected to all connected issues via ZenHub
- [x] PR description links to connected issues
- [x] Added `p` tag to titles of partial commits
- [x] Added `partial` label to PR <sub>or this PR completely resolves all connected issues</sub>
- [x] All connected issues are resolved partially <sub>or this PR does not have the `partial` label</sub>

<sup>1</sup> when the issue title describes a problem, the corresponding PR
title is `Fix: ` followed by the issue title

### Author (reindex, API changes)

- [x] Added `r` tag to commit title <sub>or this PR does not require reindexing</sub>
- [x] Added `reindex` label to PR <sub>or this PR does not require reindexing</sub>
- [x] PR and connected issue are labeled `API` <sub>or this PR does not modify a REST API</sub>
- [x] Added `a` (`A`) tag to commit title for backwards (in)compatible changes <sub>or this PR does not modify a REST API</sub>
- [x] Updated REST API version number in `app.py` <sub>or this PR does not modify a REST API</sub>

### Author (chains)

- [x] This PR is blocked by previous PR in the chain <sub>or this PR is not chained to another PR</sub>
- [x] Added `base` label to the blocking PR <sub>or this PR is not chained to another PR</sub>
- [x] Added `chained` label to this PR <sub>or this PR is not chained to another PR</sub>

### Author (upgrading)

- [x] Documented upgrading of deployments in UPGRADING.rst <sub>or this PR does not require upgrading</sub>
- [x] Added `u` tag to commit title <sub>or this PR does not require upgrading</sub>
- [x] Added `upgrade` label to PR <sub>or this PR does not require upgrading</sub>

### Author (operator tasks)

- [x] Added checklist items for additional operator tasks <sub>or this PR does not require additional tasks</sub>

### Author (hotfixes)

- [x] Added `F` tag to main commit title <sub>or this PR does not include permanent fix for a temporary hotfix</sub>
- [x] Reverted the temporary hotfixes for any connected issues <sub>or the `prod` branch has no temporary hotfixes for any connected issues</sub>

### Author (before every review)

- [x] Rebased PR branch on `develop`, squashed old fixups
- [x] Ran `make requirements_update` <sub>or this PR does not touch requirements*.txt, common.mk, Makefile and Dockerfile</sub>
- [x] Added `R` tag to commit title <sub>or this PR does not touch requirements*.txt</sub>
- [x] Added `reqs` label to PR <sub>or this PR does not touch requirements*.txt</sub>
- [x] `make integration_test` passes in personal deployment <sub>or this PR does not touch functionality that could break the IT</sub>

### Peer reviewer (after requesting changes)

Uncheck the *Author (before every review)* checklists.

### Peer reviewer (after approval)

- [x] PR is not a draft
- [x] Ticket is in *Review requested* column
- [x] Requested review from primary reviewer
- [x] Assigned PR to primary reviewer

### Primary reviewer (after requesting changes)

Uncheck the *before every review* checklists. Update the `N reviews` label.

### Primary reviewer (after approval)

- [x] Actually approved the PR
- [x] Labeled connected issues as `demo` or `no demo`
- [x] Commented on connected issues about demo expectations <sub>or all connected issues are labeled `no demo`</sub>
- [x] Decided if PR can be labeled `no sandbox`
- [x] PR title is appropriate as title of merge commit
- [x] `N reviews` label is accurate
- [x] Moved ticket to *Approved* column
- [x] Assigned PR to current operator

### Operator (before pushing merge the commit)

- [x] Checked `reindex` label and `r` commit title tag
- [x] Checked that demo expectations are clear <sub>or all connected issues are labeled `no demo`</sub>
- [x] PR has checklist items for upgrading instructions <sub>or PR is not labeled `upgrade`</sub>
- [x] Squashed PR branch and rebased onto `develop`
- [x] Sanity-checked history
- [x] Pushed PR branch to GitHub
- [x] Pushed PR branch to GitLab `dev` and added `sandbox` label <sub>or PR is labeled `no sandbox`</sub>
- [x] Pushed PR branch to GitLab `anvildev` <sub>or PR is labeled `no sandbox`</sub>
- [x] Pushed PR branch to GitLab `anvilprod` <sub>or PR is labeled `no sandbox`</sub>
- [x] Build passes in `sandbox` deployment <sub>or PR is labeled `no sandbox`</sub>
- [x] Build passes in `anvilbox` deployment <sub>or PR is labeled `no sandbox`</sub>
- [x] Build passes in `hammerbox` deployment <sub>or PR is labeled `no sandbox`</sub>
- [x] Reviewed build logs for anomalies in `sandbox` deployment <sub>or PR is labeled `no sandbox`</sub>
- [x] Reviewed build logs for anomalies in `anvilbox` deployment <sub>or PR is labeled `no sandbox`</sub>
- [x] Reviewed build logs for anomalies in `hammerbox` deployment <sub>or PR is labeled `no sandbox`</sub>
- [x] Deleted unreferenced indices in `sandbox` <sub>or this PR does not remove catalogs or otherwise causes unreferenced indices </sub>
- [x] Deleted unreferenced indices in `anvilbox` <sub>or this PR does not remove catalogs or otherwise causes unreferenced indices </sub>
- [x] Deleted unreferenced indices in `hammerbox` <sub>or this PR does not remove catalogs or otherwise causes unreferenced indices </sub>
- [x] Started reindex in `sandbox` <sub>or this PR does not require reindexing `sandbox`</sub>
- [x] Started reindex in `anvilbox` <sub>or this PR does not require reindexing `sandbox`</sub>
- [x] Started reindex in `hammerbox` <sub>or this PR does not require reindexing `sandbox`</sub>
- [x] Checked for failures in `sandbox` <sub>or this PR does not require reindexing `sandbox`</sub>
- [x] Checked for failures in `anvilbox` <sub>or this PR does not require reindexing `sandbox`</sub>
- [x] Checked for failures in `hammerbox` <sub>or this PR does not require reindexing `sandbox`</sub>
- [x] Title of merge commit starts with title from this PR
- [x] Added PR reference to merge commit title
- [x] Collected commit title tags in merge commit title <sub>but only include `p` if the PR is labeled `partial`</sub>
- [x] Moved connected issues to Merged column in ZenHub
- [x] Pushed merge commit to GitHub

### Operator (chain shortening)

- [x] Changed the target branch of the blocked PR to `develop` <sub>or this PR is not labeled `base`</sub>
- [x] Removed the `chained` label from the blocked PR <sub>or this PR is not labeled `base`</sub>
- [x] Removed the blocking relationship from the blocked PR <sub>or this PR is not labeled `base`</sub>
- [x] Removed the `base` label from this PR <sub>or this PR is not labeled `base`</sub>

### Operator (after pushing the merge commit)

- [x] Pushed merge commit to GitLab `dev` <sub>or PR is labeled `no sandbox`</sub>
- [x] Pushed merge commit to GitLab `anvildev` <sub>or PR is labeled `no sandbox`</sub>
- [x] Pushed merge commit to GitLab `anvilprod` <sub>or PR is labeled `no sandbox`</sub>
- [x] Build passes on GitLab `dev`<sup>1</sup>
- [x] Reviewed build logs for anomalies on GitLab `dev`<sup>1</sup>
- [x] Build passes on GitLab `anvildev`<sup>1</sup>
- [x] Reviewed build logs for anomalies on GitLab `anvildev`<sup>1</sup>
- [x] Build passes on GitLab `anvilprod`<sup>1</sup>
- [x] Reviewed build logs for anomalies on GitLab `anvilprod`<sup>1</sup>
- [x] Deleted PR branch from GitHub
- [x] Deleted PR branch from GitLab `dev`
- [x] Deleted PR branch from GitLab `anvildev`
- [x] Deleted PR branch from GitLab `anvilprod`

<sup>1</sup> When pushing the merge commit is skipped due to the PR being
labelled `no sandbox`, the next build triggered by a PR whose merge commit *is*
pushed determines this checklist item.

### Operator (reindex)

- [x] Deleted unreferenced indices in `dev` <sub>or this PR does not remove catalogs or otherwise causes unreferenced indices </sub>
- [x] Deleted unreferenced indices in `anvildev` <sub>or this PR does not remove catalogs or otherwise causes unreferenced indices </sub>
- [x] Deleted unreferenced indices in `anvilprod` <sub>or this PR does not remove catalogs or otherwise causes unreferenced indices </sub>
- [x] Started reindex in `dev` <sub>or this PR does not require reindexing</sub>
- [x] Started reindex in `anvildev` <sub>or this PR does not require reindexing</sub>
- [x] Started reindex in `anvilprod` <sub>or this PR does not require reindexing</sub>
- [x] Checked for and triaged indexing failures in `dev` <sub>or this PR does not require reindexing</sub>
- [x] Checked for and triaged indexing failures in `anvildev` <sub>or this PR does not require reindexing</sub>
- [x] Checked for and triaged indexing failures in `anvilprod` <sub>or this PR does not require reindexing</sub>
- [x] Emptied fail queues in `dev` deployment <sub>or this PR does not require reindexing</sub>
- [x] Emptied fail queues in `anvildev` deployment <sub>or this PR does not require reindexing</sub>
- [x] Emptied fail queues in `anvilprod` deployment <sub>or this PR does not require reindexing</sub>

### Operator

- [x] Unassigned PR

## Shorthand for review comments

- `L` line is too long
- `W` line wrapping is wrong
- `Q` bad quotes
- `F` other formatting problem

### CODE REVIEW

**Comment by achave11-ucsc** [comment]
Note, tag [r] and label `reindex` were omitted since the snapshot has already been removed.

<details><summary>Transcript of `hammerbox` deindex</summary>
<p>

```
❯ _select
lrwxr-xr-x  1 achave11  staff  9 Nov 15 15:52 .active -> hammerbox


❯ python scripts/reindex.py --catalogs anvil3 anvil3-it --sources tdr:datarepo-1525d226:snapshot/ANVIL_HPRC_20230721_ANV5_202310101603:6522/0 --deindex
2023-11-15 15:56:27,089   DEBUG MainThread __main__: Source glob 'tdr:datarepo-1525d226:snapshot/ANVIL_HPRC_20230721_ANV5_202310101603:6522/0' matched sources ['tdr:datarepo-1525d226:snapshot/ANVIL_HPRC_20230721_ANV5_202310101603:6522/0'] in catalog 'anvil3'
2023-11-15 15:56:27,090   DEBUG MainThread __main__: Source glob 'tdr:datarepo-1525d226:snapshot/ANVIL_HPRC_20230721_ANV5_202310101603:6522/0' matched sources ['tdr:datarepo-1525d226:snapshot/ANVIL_HPRC_20230721_ANV5_202310101603:6522/0'] in catalog 'anvil3-it'
2023-11-15 15:56:27,091   DEBUG MainThread azul.terra: _request('GET', https://data.terra.bio/api/repository/v1/snapshots?filter=ANVIL_HPRC_20230721_ANV5_202310101603&limit=2, headers=None, timeout=20.0, body=None)
2023-11-15 15:56:27,097    INFO MainThread botocore.credentials: Found credentials in environment variables.
2023-11-15 15:56:28,695   DEBUG MainThread azul.terra: _request(…) -> 1.604s 200 b'{"total":1377,"filteredTotal":1,"items":[{"id":"fdf50f4e-1d27-4771-b8e0-9c5be62aa170","name":"ANVIL_HPRC_20230721_ANV5_202310101603","description":"Full view snapshot of ANVIL_HPRC_20230721","createdDate":"2023-10-10T16:03:28.843286Z","profileId":"e0e03...'
2023-11-15 15:56:28,696   DEBUG MainThread azul.terra: _request('GET', https://data.terra.bio/api/repository/v1/snapshots/fdf50f4e-1d27-4771-b8e0-9c5be62aa170, headers=None, timeout=20.0, body=None)
2023-11-15 15:56:31,770   DEBUG MainThread azul.terra: _request(…) -> 3.074s 200 b'{"id":"fdf50f4e-1d27-4771-b8e0-9c5be62aa170","name":"ANVIL_HPRC_20230721_ANV5_202310101603","description":"Full view snapshot of ANVIL_HPRC_20230721","createdDate":"2023-10-10T16:03:28.843286Z","consentCode":"NRES","source":[{"dataset":{"id":"8b2b1c92-6...'
2023-11-15 15:56:32,311   DEBUG MainThread azul.es: Creating ES client [vpc-azul-index-hammerbox-srwikb4z42wnpzxq2f56y36icu.us-east-1.es.amazonaws.com:443]
2023-11-15 15:56:32,349    INFO MainThread botocore.credentials: Found credentials in environment variables.
2023-11-15 15:56:32,349    INFO MainThread azul.azulclient: Deindexing sources {'tdr:datarepo-1525d226:snapshot/ANVIL_HPRC_20230721_ANV5_202310101603:6522/0'} from catalog 'anvil3'
2023-11-15 15:56:32,349   DEBUG MainThread azul.azulclient: Using query: {'query': {'bool': {'should': [{'terms': {'sources.id.keyword': ['fdf50f4e-1d27-4771-b8e0-9c5be62aa170']}}, {'terms': {'source.id.keyword': ['fdf50f4e-1d27-4771-b8e0-9c5be62aa170']}}]}}}
2023-11-15 15:56:32,349    INFO MainThread elasticsearch: Making POST request to https://vpc-azul-index-hammerbox-srwikb4z42wnpzxq2f56y36icu.us-east-1.es.amazonaws.com:443/azul_v2_hammerbox_anvil3_activities,azul_v2_hammerbox_anvil3_activities_aggregate,azul_v2_hammerbox_anvil3_biosamples,azul_v2_hammerbox_anvil3_biosamples_aggregate,azul_v2_hammerbox_anvil3_datasets,azul_v2_hammerbox_anvil3_datasets_aggregate,azul_v2_hammerbox_anvil3_donors,azul_v2_hammerbox_anvil3_donors_aggregate,azul_v2_hammerbox_anvil3_files,azul_v2_hammerbox_anvil3_files_aggregate/_delete_by_query?slices=auto
2023-11-15 15:56:32,350    INFO MainThread elasticsearch: … with request body b'{"query":{"bool":{"should":[{"terms":{"sources.id.keyword":["fdf50f4e-1d27-4771-b8e0-9c5be62aa170"]}},{"terms":{"source.id.ke...'
2023-11-15 15:56:32,786    INFO MainThread elasticsearch: Got 200 response after 0.436s from POST to https://vpc-azul-index-hammerbox-srwikb4z42wnpzxq2f56y36icu.us-east-1.es.amazonaws.com:443/azul_v2_hammerbox_anvil3_activities,azul_v2_hammerbox_anvil3_activities_aggregate,azul_v2_hammerbox_anvil3_biosamples,azul_v2_hammerbox_anvil3_biosamples_aggregate,azul_v2_hammerbox_anvil3_datasets,azul_v2_hammerbox_anvil3_datasets_aggregate,azul_v2_hammerbox_anvil3_donors,azul_v2_hammerbox_anvil3_donors_aggregate,azul_v2_hammerbox_anvil3_files,azul_v2_hammerbox_anvil3_files_aggregate/_delete_by_query?slices=auto
2023-11-15 15:56:32,786    INFO MainThread elasticsearch: … with response body '{"took":22,"timed_out":false,"total":7,"deleted":7,"batches":1,"version_conflicts":0,"noops":0,"retries":{"bulk":0,"search":0},…'
2023-11-15 15:56:32,787    INFO MainThread azul.azulclient: Deindexing sources {'tdr:datarepo-1525d226:snapshot/ANVIL_HPRC_20230721_ANV5_202310101603:6522/0'} from catalog 'anvil3-it'
2023-11-15 15:56:32,788   DEBUG MainThread azul.azulclient: Using query: {'query': {'bool': {'should': [{'terms': {'sources.id.keyword': ['fdf50f4e-1d27-4771-b8e0-9c5be62aa170']}}, {'terms': {'source.id.keyword': ['fdf50f4e-1d27-4771-b8e0-9c5be62aa170']}}]}}}
2023-11-15 15:56:32,788    INFO MainThread elasticsearch: Making POST request to https://vpc-azul-index-hammerbox-srwikb4z42wnpzxq2f56y36icu.us-east-1.es.amazonaws.com:443/azul_v2_hammerbox_anvil3-it_activities,azul_v2_hammerbox_anvil3-it_activities_aggregate,azul_v2_hammerbox_anvil3-it_biosamples,azul_v2_hammerbox_anvil3-it_biosamples_aggregate,azul_v2_hammerbox_anvil3-it_datasets,azul_v2_hammerbox_anvil3-it_datasets_aggregate,azul_v2_hammerbox_anvil3-it_donors,azul_v2_hammerbox_anvil3-it_donors_aggregate,azul_v2_hammerbox_anvil3-it_files,azul_v2_hammerbox_anvil3-it_files_aggregate/_delete_by_query?slices=auto
2023-11-15 15:56:32,788    INFO MainThread elasticsearch: … with request body b'{"query":{"bool":{"should":[{"terms":{"sources.id.keyword":["fdf50f4e-1d27-4771-b8e0-9c5be62aa170"]}},{"terms":{"source.id.ke...'
2023-11-15 15:56:32,919    INFO MainThread elasticsearch: Got 200 response after 0.131s from POST to https://vpc-azul-index-hammerbox-srwikb4z42wnpzxq2f56y36icu.us-east-1.es.amazonaws.com:443/azul_v2_hammerbox_anvil3-it_activities,azul_v2_hammerbox_anvil3-it_activities_aggregate,azul_v2_hammerbox_anvil3-it_biosamples,azul_v2_hammerbox_anvil3-it_biosamples_aggregate,azul_v2_hammerbox_anvil3-it_datasets,azul_v2_hammerbox_anvil3-it_datasets_aggregate,azul_v2_hammerbox_anvil3-it_donors,azul_v2_hammerbox_anvil3-it_donors_aggregate,azul_v2_hammerbox_anvil3-it_files,azul_v2_hammerbox_anvil3-it_files_aggregate/_delete_by_query?slices=auto
2023-11-15 15:56:32,919    INFO MainThread elasticsearch: … with response body '{"took":20,"timed_out":false,"total":7,"deleted":7,"batches":1,"version_conflicts":0,"noops":0,"retries":{"bulk":0,"search":0},…'


```

</p>
</details> 

<details><summary>Transcript of `anvilprod` deindex</summary>
<p>

```
❯ _select anvilprod
…
❯ python scripts/reindex.py --catalogs anvil3 anvil3-it --sources tdr:datarepo-1525d226:snapshot/ANVIL_HPRC_20230721_ANV5_202310101603:/3 --deindex
2023-11-15 15:57:20,178   DEBUG MainThread __main__: Source glob 'tdr:datarepo-1525d226:snapshot/ANVIL_HPRC_20230721_ANV5_202310101603:/3' matched sources ['tdr:datarepo-1525d226:snapshot/ANVIL_HPRC_20230721_ANV5_202310101603:/3'] in catalog 'anvil3'
2023-11-15 15:57:20,179   DEBUG MainThread __main__: Source glob 'tdr:datarepo-1525d226:snapshot/ANVIL_HPRC_20230721_ANV5_202310101603:/3' matched sources ['tdr:datarepo-1525d226:snapshot/ANVIL_HPRC_20230721_ANV5_202310101603:/3'] in catalog 'anvil3-it'
2023-11-15 15:57:20,179   DEBUG MainThread azul.terra: _request('GET', https://data.terra.bio/api/repository/v1/snapshots?filter=ANVIL_HPRC_20230721_ANV5_202310101603&limit=2, headers=None, timeout=20.0, body=None)
2023-11-15 15:57:20,186    INFO MainThread botocore.credentials: Found credentials in environment variables.
2023-11-15 15:57:21,454   DEBUG MainThread azul.terra: _request(…) -> 1.274s 200 b'{"total":1377,"filteredTotal":1,"items":[{"id":"fdf50f4e-1d27-4771-b8e0-9c5be62aa170","name":"ANVIL_HPRC_20230721_ANV5_202310101603","description":"Full view snapshot of ANVIL_HPRC_20230721","createdDate":"2023-10-10T16:03:28.843286Z","profileId":"e0e03...'
2023-11-15 15:57:21,455   DEBUG MainThread azul.terra: _request('GET', https://data.terra.bio/api/repository/v1/snapshots/fdf50f4e-1d27-4771-b8e0-9c5be62aa170, headers=None, timeout=20.0, body=None)
2023-11-15 15:57:24,342   DEBUG MainThread azul.terra: _request(…) -> 2.887s 200 b'{"id":"fdf50f4e-1d27-4771-b8e0-9c5be62aa170","name":"ANVIL_HPRC_20230721_ANV5_202310101603","description":"Full view snapshot of ANVIL_HPRC_20230721","createdDate":"2023-10-10T16:03:28.843286Z","consentCode":"NRES","source":[{"dataset":{"id":"8b2b1c92-6...'
2023-11-15 15:57:24,817   DEBUG MainThread azul.es: Creating ES client [vpc-azul-index-anvilprod-ggipah4skn2ftt47u4xgvydzqm.us-east-1.es.amazonaws.com:443]
2023-11-15 15:57:24,848    INFO MainThread botocore.credentials: Found credentials in environment variables.
2023-11-15 15:57:24,849    INFO MainThread azul.azulclient: Deindexing sources {'tdr:datarepo-1525d226:snapshot/ANVIL_HPRC_20230721_ANV5_202310101603:/3'} from catalog 'anvil3'
2023-11-15 15:57:24,849   DEBUG MainThread azul.azulclient: Using query: {'query': {'bool': {'should': [{'terms': {'sources.id.keyword': ['fdf50f4e-1d27-4771-b8e0-9c5be62aa170']}}, {'terms': {'source.id.keyword': ['fdf50f4e-1d27-4771-b8e0-9c5be62aa170']}}]}}}
2023-11-15 15:57:24,849    INFO MainThread elasticsearch: Making POST request to https://vpc-azul-index-anvilprod-ggipah4skn2ftt47u4xgvydzqm.us-east-1.es.amazonaws.com:443/azul_v2_anvilprod_anvil3_activities,azul_v2_anvilprod_anvil3_activities_aggregate,azul_v2_anvilprod_anvil3_biosamples,azul_v2_anvilprod_anvil3_biosamples_aggregate,azul_v2_anvilprod_anvil3_datasets,azul_v2_anvilprod_anvil3_datasets_aggregate,azul_v2_anvilprod_anvil3_donors,azul_v2_anvilprod_anvil3_donors_aggregate,azul_v2_anvilprod_anvil3_files,azul_v2_anvilprod_anvil3_files_aggregate/_delete_by_query?slices=auto
2023-11-15 15:57:24,849    INFO MainThread elasticsearch: … with request body b'{"query":{"bool":{"should":[{"terms":{"sources.id.keyword":["fdf50f4e-1d27-4771-b8e0-9c5be62aa170"]}},{"terms":{"source.id.ke...'
2023-11-15 15:58:12,870    INFO MainThread elasticsearch: Got 200 response after 48.021s from POST to https://vpc-azul-index-anvilprod-ggipah4skn2ftt47u4xgvydzqm.us-east-1.es.amazonaws.com:443/azul_v2_anvilprod_anvil3_activities,azul_v2_anvilprod_anvil3_activities_aggregate,azul_v2_anvilprod_anvil3_biosamples,azul_v2_anvilprod_anvil3_biosamples_aggregate,azul_v2_anvilprod_anvil3_datasets,azul_v2_anvilprod_anvil3_datasets_aggregate,azul_v2_anvilprod_anvil3_donors,azul_v2_anvilprod_anvil3_donors_aggregate,azul_v2_anvilprod_anvil3_files,azul_v2_anvilprod_anvil3_files_aggregate/_delete_by_query?slices=auto
2023-11-15 15:58:12,871    INFO MainThread elasticsearch: … with response body '{"took":47598,"timed_out":false,"total":429935,"deleted":429935,"batches":430,"version_conflicts":0,"noops":0,"retries":{"bulk"…'
2023-11-15 15:58:12,871    INFO MainThread azul.azulclient: Deindexing sources {'tdr:datarepo-1525d226:snapshot/ANVIL_HPRC_20230721_ANV5_202310101603:/3'} from catalog 'anvil3-it'
2023-11-15 15:58:12,871   DEBUG MainThread azul.azulclient: Using query: {'query': {'bool': {'should': [{'terms': {'sources.id.keyword': ['fdf50f4e-1d27-4771-b8e0-9c5be62aa170']}}, {'terms': {'source.id.keyword': ['fdf50f4e-1d27-4771-b8e0-9c5be62aa170']}}]}}}
2023-11-15 15:58:12,872    INFO MainThread elasticsearch: Making POST request to https://vpc-azul-index-anvilprod-ggipah4skn2ftt47u4xgvydzqm.us-east-1.es.amazonaws.com:443/azul_v2_anvilprod_anvil3-it_activities,azul_v2_anvilprod_anvil3-it_activities_aggregate,azul_v2_anvilprod_anvil3-it_biosamples,azul_v2_anvilprod_anvil3-it_biosamples_aggregate,azul_v2_anvilprod_anvil3-it_datasets,azul_v2_anvilprod_anvil3-it_datasets_aggregate,azul_v2_anvilprod_anvil3-it_donors,azul_v2_anvilprod_anvil3-it_donors_aggregate,azul_v2_anvilprod_anvil3-it_files,azul_v2_anvilprod_anvil3-it_files_aggregate/_delete_by_query?slices=auto
2023-11-15 15:58:12,872    INFO MainThread elasticsearch: … with request body b'{"query":{"bool":{"should":[{"terms":{"sources.id.keyword":["fdf50f4e-1d27-4771-b8e0-9c5be62aa170"]}},{"terms":{"source.id.ke...'
2023-11-15 15:58:12,981    INFO MainThread elasticsearch: Got 200 response after 0.109s from POST to https://vpc-azul-index-anvilprod-ggipah4skn2ftt47u4xgvydzqm.us-east-1.es.amazonaws.com:443/azul_v2_anvilprod_anvil3-it_activities,azul_v2_anvilprod_anvil3-it_activities_aggregate,azul_v2_anvilprod_anvil3-it_biosamples,azul_v2_anvilprod_anvil3-it_biosamples_aggregate,azul_v2_anvilprod_anvil3-it_datasets,azul_v2_anvilprod_anvil3-it_datasets_aggregate,azul_v2_anvilprod_anvil3-it_donors,azul_v2_anvilprod_anvil3-it_donors_aggregate,azul_v2_anvilprod_anvil3-it_files,azul_v2_anvilprod_anvil3-it_files_aggregate/_delete_by_query?slices=auto
2023-11-15 15:58:12,982    INFO MainThread elasticsearch: … with response body '{"took":3,"timed_out":false,"total":0,"deleted":0,"batches":0,"version_conflicts":0,"noops":0,"retries":{"bulk":0,"search":0},"…'

```

</p>
</details>

**Review by dsotirho-ucsc — APPROVED** [review]
Approved.

**Review by hannes-ucsc — APPROVED** [review]

**Comment by hannes-ucsc** [comment]
I mistakenly marked this as `no sandbox`. @achave11-ucsc, before you delete the PR branch, could you please push it to GitLab `anvilprod` so that we get the hammerbox build for it? You may also need to manually deindex the snapshot there. Lastly, the `r` commit title tag should have been present and checklist items for the deindexing should have been created.

**Comment by achave11-ucsc** [comment]
The `hammerbox` pipeline succeeded https://gitlab.prod.anvil.gi.ucsc.edu/ucsc/azul/-/pipelines/6648.

**Pull request merged**
