### PR TITLE
Fix: Stitching trips over mixed `links` schema versions (#3203)

### PR DESCRIPTION
**Pull request by noah-aviel-dove**
Author

- [x] PR title references issue
- [x] Title of main commit references issue
- [x] PR is linked to Zenhub issue

Author (reindex)

- [x] Added `r` tag to commit title                         <sub>or this PR does not require reindexing</sub>
- [x] Added `reindex` label to PR                           <sub>or this PR does not require reindexing</sub>

Author (freebies & chains)

- [x] Freebies are blocked on this PR                       <sub>or there are no freebies in this PR</sub>
- [x] Freebies are referenced in commit titles              <sub>or there are no freebies in this PR</sub>
- [x] This PR is blocked by previous PR in the chain        <sub>or this PR is not chained to another PR</sub>
- [x] Added `chain` label to the blocking PR                <sub>or this PR is not chained to another PR</sub>

Author (upgrading)

- [x] Documented upgrading of deployments in UPGRADING.rst  <sub>or this PR does not require upgrading</sub>
- [x] Added `u` tag to commit title                         <sub>or this PR does not require upgrading</sub>
- [x] Added `upgrade` label to PR                           <sub>or this PR does not require upgrading</sub>

Author (requirements, before every review)

- [x] Ran `make requirements_update`                        <sub>or this PR leaves requirements*.txt, common.mk and Makefile untouched</sub>
- [x] Added `R` tag to commit title                         <sub>or this PR leaves requirements*.txt untouched</sub>
- [x] Added `reqs` label to PR                              <sub>or this PR leaves requirements*.txt untouched</sub>

Author (before every review)

- [x] `make integration_test` passes in personal deployment <sub>or this PR does not touch functionality that could break the IT</sub>
- [x] Rebased branch on `develop`, squashed old fixups

Primary reviewer (after approval)

- [x] Commented in issue about demo expectations            <sub>or labelled issue as `no demo`</sub>
- [x] Decided if PR can be labeled `no sandbox`
- [x] PR title is appropriate as title of merge commit
- [x] Moved ticket to Approved column
- [x] Assigned PR to an operator

Operator (before pushing merge the commit)

- [x] Checked `reindex` label and `r` commit title tag
- [x] Checked that demo expectations are clear              <sub>or issue is labeled as `no demo`</sub>
- [x] Rebased and squashed branch
- [x] Sanity-checked history
- [x] Pushed PR branch to Github
- [x] Branch pushed to Gitlab                               <sub>or PR is labeled `no sandbox`</sub>
- [x] Build passes in sandbox and added `sandbox` label     <sub>or PR is labeled `no sandbox`</sub>
- [x] Started reindex in `sandbox`                          <sub>or this PR does not require reindexing `sandbox`</sub>
- [x] Checked for failures in `sandbox`                     <sub>or this PR does not require reindexing `sandbox`</sub>
- [x] Added PR reference to merge commit title
- [x] Collected commit title tags in merge commit title
- [x] Moved linked issue to Merged column
- [ ] Pushed merge commit to Github

Operator (after pushing the merge commit)

- [ ] Moved freebies to Merged column                       <sub>or there are no freebies in this PR</sub> 
- [ ] Shortened the PR chain                                <sub>or this PR is not the base of another PR</sub>
- [ ] Verified that `N reviews` labelling is accurate
- [ ] Pushed merge commit to Gitlab                         <sub>or this changes can be pushed later, together with another PR</sub>
- [ ] Deleted PR branch from Github and Gitlab

Operator (reindex) 

- [ ] Started reindex in `dev`                              <sub>or this PR does not require reindexing or does not target `dev`</sub>
- [ ] Checked for failures in `dev`                         <sub>or this PR does not require reindexing or does not target `dev`</sub>
- [ ] Started reindex in `prod`                             <sub>or this PR does not require reindexing or does not target `prod`</sub>
- [ ] Checked for failures in `prod`                        <sub>or this PR does not require reindexing or does not target `prod`</sub>

Operator

- [ ] Unassigned PR

### CODE REVIEW

**Review by amarjandu — APPROVED** [review]
Looks consistent with the `quick-fix` mentioned here https://github.com/databiosphere/azul/issues/3203#issuecomment-874894241

**Comment by amarjandu** [comment]
@noah-aviel-dove hey just wondering if an IT was ran w/ the changes, i saw that you checked the box, but just wanted to confirm. 😬

**Comment by noah-aviel-dove** [comment]
> @noah-aviel-dove hey just wondering if an IT was ran w/ the changes

Yes, I ran the IT before checking the box. However I did not reconfigure my PR to use the snapshot where we encountered this issue, which I probably should. So I'll do that now.

**Comment by noah-aviel-dove** [comment]
I was held up by an intermittent IT failure when testing the DRS endpoints but IT has passed with source `tdr:broad-datarepo-terra-prod-hca2:snapshot/hca_prod_20201120_dcp2__20210701_dcp7:98`

**Review by hannes-ucsc — CHANGES_REQUESTED** [review]
Replaced successive dict entries with literal and used furl for interpolation.

Prefer local variables over attributes unless value is used in more than one function or is freely configurable.

```diff
Index: src/azul/plugins/repository/tdr/__init__.py
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/src/azul/plugins/repository/tdr/__init__.py b/src/azul/plugins/repository/tdr/__init__.py
--- a/src/azul/plugins/repository/tdr/__init__.py	(revision b1c8cad1bc0f749948e7aed13e47921fe0b98897)
+++ b/src/azul/plugins/repository/tdr/__init__.py	(date 1625810746666)
@@ -461,9 +461,6 @@
                 f'Dangling inputs not found in any bundle: {missing}')
         return bundles
 
-    _schema_type = 'links'
-    _schema_version = '3.0.0'
-
     def _merge_links(self, links_jsons: JSONs) -> JSON:
         """
         Merge the links.json documents from multiple stitched bundles into a
@@ -471,20 +468,24 @@
         """
         root, *stitched = links_jsons
         if stitched:
-            merged = {'links_id': root['links_id'],
-                      'version': root['version']}
+            merged = {
+                'links_id': root['links_id'],
+                'version': root['version']
+            }
             for common_key in ('project_id', 'schema_type'):
                 merged[common_key] = one({row[common_key] for row in links_jsons})
-            merged_content = {}
             source_contents = [row['content'] for row in links_jsons]
+            schema_url = furl('https://schema.humancellatlas.org')
             # FIXME: Explicitly verify compatible schema versions for stitched subgraphs
             #        https://github.com/DataBiosphere/azul/issues/3215
-            merged_content['schema_type'] = self._schema_type
-            merged_content['schema_version'] = self._schema_version
-            merged_content['describedBy'] = (f'https://schema.humancellatlas.org/system/'
-                                             f'{self._schema_version}/{self._schema_type}')
-            merged_content['links'] = sum((sc['links'] for sc in source_contents),
-                                          start=[])
+            schema_type = 'links'
+            schema_version = '3.0.0'
+            merged_content = {
+                'schema_type': schema_type,
+                'schema_version': schema_version,
+                'describedBy': schema_url.set(path=('system', schema_version, schema_type)),
+                'links': sum((sc['links'] for sc in source_contents), start=[])
+            }
             merged['content'] = merged_content  # Keep result of parsed JSON for reuse
             merged['content_size'] = len(json.dumps(merged_content))
             assert merged.keys() == one({
```

**Review by hannes-ucsc — APPROVED** [review]

**Comment by hannes-ucsc** [comment]
@noah-aviel-dove, please prefer "Fix:" plus issue title in titles of PRs that fix bugs.

**Comment by hannes-ucsc** [comment]
I'm moving this along. We'll find out in sandbox if the IT passes.

**Pull request merged**
