### PR TITLE
Prevent failure due to `write` AWS lambda memory exhaustion (#2013)

### PR DESCRIPTION
**Pull request by achave11**
* Fix obtained from contribution related to ticket (#1693, PR #1716).

### CODE REVIEW

**Comment by achave11** [comment]
> I had trouble understanding the body of the commit message. I found the bullet at the beginning confusing because generally commit bodies are paragraph-like text. Also the commit body is not a complete sentence.
> 
> I think it would read more cleanly if rewritten something like "The fix was copied from PR #1716 which resolved #1693."

Thank @jessebrennan, I took your suggestion!

**Comment by achave11** [comment]
@hannes-ucsc Perhaps it was my mistake for trying to create a PR against the `hca/prod` branch, which seems to be the only one presenting this problem. Should this be promoted through the deployments starting with `hca/dev`? That way we can get the consequent Gitlab builds. I am unsure as to how to proceed.

**Comment by hannes-ucsc** [comment]
I'm not sure either but this is a problem you need to solve. The base branch should be `hca/dev`.

**Comment by achave11** [comment]
Invalid PR base, closing.

**Pull request closed without merging**
