### PR TITLE
Add support for DCP/1 matrices (#2483)

### PR DESCRIPTION
**Pull request by danielsotirhos**
Author (check before every review)

- [x] PR title references issue
- [x] Title of main commit references issue
- [x] PR is linked to Zenhub issue
- [x] Added `DCP/1` label                                   <sub>or this PR does not target an `hca/*` branch</sub>
- [x] Created issue to track porting these changes          <sub>or this PR does not need porting</sub> 
- [x] Added `r` tag to commit title                         <sub>or this PR does not require reindexing</sub>
- [x] Added `reindex` label to PR                           <sub>or this PR does not require reindexing</sub>
- [x] Freebies are blocked on this PR                       <sub>or there are no freebies in this PR</sub>
- [x] Freebies are referenced in commit titles              <sub>or there are no freebies in this PR</sub>
- [x] This PR is blocked by previous PR in chain            <sub>or this PR is not chained to another PR</sub>
- [x] Added `chain` label to the blocking PR                <sub>or this PR is not chained to another PR</sub>
- [x] Ran `make requirements_update`                        <sub>or this PR leaves requirements*.txt, common.mk and Makefile untouched</sub>
- [x] Added `R` tag to commit title                         <sub>or this PR leaves requirements*.txt untouched</sub>
- [x] Added `reqs` label to PR                              <sub>or this PR leaves requirements*.txt untouched</sub>
- [x] Documented upgrading of deployments in UPGRADING.rst  <sub>or this PR does not require upgrading</sub>
- [x] Added `u` tag to commit title                         <sub>or this PR does not require upgrading</sub>
- [x] Added `upgrade` label to PR                           <sub>or this PR does not require upgrading</sub>
- [x] `make integration_test` passes in personal deployment <sub>or this PR does not touch functionality that could break the IT</sub>
- [x] Rebased branch on `develop`

Primary reviewer (before pushing merge commit)

- [x] Checked `reindex` label and `r` commit title tag
- [x] Rebased and squashed branch
- [x] Sanity-checked history
- [x] Build passes in `sandbox`                             <sub>or added `no sandbox` label</sub>
- [x] Reindexed `sandbox`                                   <sub>or this PR does not require reindexing</sub>
- [x] Added PR reference to merge commit
- [x] Moved linked issue to Merged
- [ ] Pushed merge commit to Github

Primary reviewer (after pushing merge commit)

- [ ] Moved freebies to Merged column                       <sub>or there are no freebies in this PR</sub> 
- [ ] Shortened chain                                       <sub>or this PR is not the base of another PR</sub>
- [ ] Verified that `N reviews` labelling is accurate
- [ ] Commented on demo expectations                        <sub>or labeled as `no demo`</sub>
- [ ] Pushed merge commit to Gitlab                         <sub>or this changes can be pushed later, together with another PR</sub>
- [ ] Reindexed `dev`                                       <sub>or this PR does not require reindexing</sub>
- [ ] Deleted PR branch from Github and Gitlab
- [ ] Unassign reviewer from PR

### CODE REVIEW

**Comment by hannes-ucsc** [comment]
For demo, show staging area with matrices, the tree in `/index/projects` and the files in `/index/files`.

**Comment by hannes-ucsc** [comment]
@danielsotirhos could you verify that these matrices show up in `prod` as outlined in my previous comment and post evidence here? That will count as the demo.

**Comment by danielsotirhos** [comment]
Staging Area: `gs://broad-dsp-monster-hca-prod-ucsc-storage/cgm_dcp1`

(Results below for project: `A single-cell transcriptome atlas of the adult human retina`)

Project Tab: https://dcp2.data.humancellatlas.org/explore/projects?catalog=dcp1&filter=%5B%7B%22facetName%22:%22projectTitle%22,%22terms%22:%5B%22A%20single-cell%20transcriptome%20atlas%20of%20the%20adult%20human%20retina%22%5D%7D,%7B%22facetName%22:%22projectId%22,%22terms%22:%5B%228185730f-4113-40d3-9cc3-929271784c2b%22%5D%7D%5D

Files tab: https://dcp2.data.humancellatlas.org/explore/files?catalog=dcp1&filter=%5B%7B%22facetName%22:%22projectTitle%22,%22terms%22:%5B%22A%20single-cell%20transcriptome%20atlas%20of%20the%20adult%20human%20retina%22%5D%7D,%7B%22facetName%22:%22projectId%22,%22terms%22:%5B%228185730f-4113-40d3-9cc3-929271784c2b%22%5D%7D%5D

Projects response:
```
daniel@Crispin ~ $ http 'https://service.azul.data.humancellatlas.org/index/projects?filters=%7B%22projectTitle%22%3A%7B%22is%22%3A%5B%22A%20single-cell%20transcriptome%20atlas%20of%20the%20adult%20human%20retina%22%5D%7D%7D&size=15&catalog=dcp1' | jq '.hits[].projects[].matrices'
{
  "genusSpecies": {
    "Homo sapiens": {
      "organ": {
        "eye": {
          "libraryConstructionApproach": {
            "10X v2 sequencing": [
              {
                "name": "8185730f-4113-40d3-9cc3-929271784c2b.homo_sapiens.csv.zip",
                "url": "https://service.azul.data.humancellatlas.org/fetch/dss/files/538faa28-3235-5e4b-a998-5672e2d964e8?version=2020-11-23T21%3A01%3A12.275120Z&catalog=dcp1"
              },
              {
                "name": "8185730f-4113-40d3-9cc3-929271784c2b.homo_sapiens.mtx.zip",
                "url": "https://service.azul.data.humancellatlas.org/fetch/dss/files/6c142250-567c-5b63-bd4f-0d78499863f8?version=2020-11-23T21%3A01%3A12.275120Z&catalog=dcp1"
              },
              {
                "name": "8185730f-4113-40d3-9cc3-929271784c2b.homo_sapiens.loom",
                "url": "https://service.azul.data.humancellatlas.org/fetch/dss/files/8d2ba1c1-bc9f-5c2a-a74d-fe5e09bdfb18?version=2020-11-23T21%3A01%3A12.275120Z&catalog=dcp1"
              }
            ]
          }
        }
      }
    }
  }
}
```

Files response:
```
daniel@Crispin ~ $ http 'https://service.azul.data.humancellatlas.org/index/files?filters=%7B%22projectTitle%22%3A%7B%22is%22%3A%5B%22A%20single-cell%20transcriptome%20atlas%20of%20the%20adult%20human%20retina%22%5D%7D%2C%22projectId%22%3A%7B%22is%22%3A%5B%228185730f-4113-40d3-9cc3-929271784c2b%22%5D%7D%7D&size=100&catalog=dcp1' | jq '.hits[].files[].name' | grep '8185730f'
"8185730f-4113-40d3-9cc3-929271784c2b.homo_sapiens.csv.zip"
"8185730f-4113-40d3-9cc3-929271784c2b.homo_sapiens.loom"
"8185730f-4113-40d3-9cc3-929271784c2b.homo_sapiens.mtx.zip"
```

**Comment by danielsotirhos** [comment]
AssertionError encountered when trying to download a DCP/1 matrix file:

```
daniel@Crispin ~ $ curl 'https://service.azul.data.humancellatlas.org/fetch/dss/files/538faa28-3235-5e4b-a998-5672e2d964e8?version=2020-11-23T21%3A01%3A12.275120Z&catalog=dcp1'
Traceback (most recent call last):
  File "/var/task/chalice/app.py", line 1135, in _get_view_function_response
    response = view_function(**function_args)
  File "/var/task/app.py", line 1573, in fetch_dss_files
    return fetch_repository_files(file_uuid)
  File "/var/task/app.py", line 1719, in fetch_repository_files
    body = _repository_files(file_uuid, fetch=True)
  File "/var/task/app.py", line 1750, in _repository_files
    return app.repository_controller.download_file(catalog=app.catalog,
  File "/var/task/azul/service/repository_controller.py", line 78, in download_file
    download.update(plugin)
  File "/var/task/azul/plugins/repository/tdr/__init__.py", line 417, in update
    assert self.drs_path is not None
AssertionError
```

**Comment by danielsotirhos** [comment]
Created ticket https://github.com/DataBiosphere/azul/issues/2553

**Pull request merged**
