### PR TITLE
Hotfix prod: Snapshot 2ef3655a in dcp40 catalog failed to index due to dangling inputs (#6431)

### LINKED ISSUE #6431: Snapshot `2ef3655a` in dcp40 catalog failed to index due to dangling inputs
[Failed queues snipped in GL.](https://gitlab.azul.data.humancellatlas.org/ucsc/azul/-/snippets/9)
**CloudWatch Logs Insights**    
region: us-east-1    
log-group-names: /aws/lambda/azul-indexer-prod-contribute    
start-time: -345600s    
end-time: 0s    
query-string:
  ```
  fields @timestamp, @message, @logStream, @log
| filter @requestId like /292e4bdd|bffd7c43|ee19ed19|2b62ad82/
| filter @message like 'tdr:datarepo-f9579ac6:snapshot/hca_prod_2ef3655a973d4d699b4121fa4041eed7__20220111_dcp2_20240711_dcp40'
| sort @timestamp desc
| limit 10000
  ```
---
| @timestamp | @message | @logStream | @log |
| --- | --- | --- | --- |
| 2024-07-19 23:21:06.686 | [WARNING] 2024-07-19T23:21:06.684Z 292e4bdd-cb54-5daa-bfdb-14c93dcf2ec9 azul.indexer.index_controller Worker failed to handle message {'action': 'add', 'notification': {'transaction_id': 'dd661ecf-c156-46b8-8dcb-1886a60cd587', 'bundle_fqid': {'uuid': '2d9430d0-9d18-55d6-9ff0-089e2d981f0c', 'version': '2021-02-08T09:30:00.000000Z', 'source': {'id': 'baf133cf-37e4-413f-a034-4d3edbf4a11c', 'spec': 'tdr:datarepo-f9579ac6:snapshot/hca_prod_2ef3655a973d4d699b4121fa4041eed7__20220111_dcp2_20240711_dcp40:/0'}}}, 'catalog': 'dcp40'}. Traceback (most recent call last):   File "/var/task/azul/indexer/index_controller.py", line 180, in contribute     contributions, replicas = self.transform(catalog, notification, delete)                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^   File "/var/task/azul/indexer/index_controller.py", line 232, in transform     bundle = service.fetch_bundle(catalog, bundle_fqid)              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^   File "/var/task/azul/indexer/index_service.py", line 196, in fetch_bundle     return plugin.fetch_bundle(bundle_fqid)            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^   File "/var/task/azul/plugins/repository/tdr.py", line 212, in fetch_bundle     bundle = self._emulate_bundle(bundle_fqid)              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^   File "/var/task/azul/plugins/repository/tdr_hca/__init__.py", line 392, in _emulate_bundle     raise e   File "/var/lang/lib/python3.11/concurrent/futures/thread.py", line 58, in run     result = self.fn(*self.args, **self.kwargs)              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^   File "/var/task/azul/plugins/repository/tdr_hca/__init__.py", line 520, in _retrieve_entities     require(not missing,   File "/var/task/azul/__init__.py", line 1612, in require     reject(not condition, *args, exception=exception)   File "/var/task/azul/__init__.py", line 1631, in reject     raise exception(*args) azul.RequirementError: Required entities not found in `datarepo-f9579ac6.hca_prod_2ef3655a973d4d699b4121fa4041eed7__20220111_dcp2_20240711_dcp40.sequence_file`: {'3f7d6a00-1fd0-4e36-b4bb-b8cfc2aad40c', 'c3b6828d-585d-44f8-96c3-30974f33dad0'} | 2024/07/19/[$LATEST]474489c1c2c4481788f8762014b8d83d | 542754589326:/aws/lambda/azul-indexer-prod-contribute |
| 2024-07-19 23:15:47.943 | [WARNING] 2024-07-19T23:15:47.940Z bffd7c43-b422-56fb-89ee-235741968c16 azul.indexer.index_controller Worker failed to handle message {'action': 'add', 'notification': {'transaction_id': '9c1d6df3-1411-46f8-9917-cd3a441764dc', 'bundle_fqid': {'uuid': '51b7ad62-9f03-5ee1-99a3-e6eb4d54c713', 'version': '2021-02-08T09:30:00.000000Z', 'source': {'id': 'baf133cf-37e4-413f-a034-4d3edbf4a11c', 'spec': 'tdr:datarepo-f9579ac6:snapshot/hca_prod_2ef3655a973d4d699b4121fa4041eed7__20220111_dcp2_20240711_dcp40:/0'}}}, 'catalog': 'dcp40'}. Traceback (most recent call last):   File "/var/task/azul/indexer/index_controller.py", line 180, in contribute     contributions, replicas = self.transform(catalog, notification, delete)                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^   File "/var/task/azul/indexer/index_controller.py", line 232, in transform     bundle = service.fetch_bundle(catalog, bundle_fqid)              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^   File "/var/task/azul/indexer/index_service.py", line 196, in fetch_bundle     return plugin.fetch_bundle(bundle_fqid)            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^   File "/var/task/azul/plugins/repository/tdr.py", line 212, in fetch_bundle     bundle = self._emulate_bundle(bundle_fqid)              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^   File "/var/task/azul/plugins/repository/tdr_hca/__init__.py", line 362, in _emulate_bundle     entities, root_entities, links_jsons = self._stitch_bundles(bundle)                                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^   File "/var/task/azul/plugins/repository/tdr_hca/__init__.py", line 438, in _stitch_bundles     upstream = self._find_upstream_bundles(source, all_dangling_inputs)                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^   File "/var/task/azul/plugins/repository/tdr_hca/__init__.py", line 564, in _find_upstream_bundles     require(not missing,   File "/var/task/azul/__init__.py", line 1612, in require     reject(not condition, *args, exception=exception)   File "/var/task/azul/__init__.py", line 1631, in reject     raise exception(*args) azul.RequirementError: Dangling inputs not found in any bundle: {'b3e4c7ac-262a-416b-ab60-8f950f52e015', 'b5a78d96-efc1-4af8-8877-bbdafab852e6', '6593375f-8c8a-48d5-9246-0dcfeabd5d97', '4f49933e-88d5-49df-a065-a192de2e39e5', '77644f23-10f8-4378-b94b-3431ae3496f7', '27639c1d-bcd9-4c65-9a72-9177b410f357', '58ac64da-8016-4296-8054-23206291b2d4', 'a1c4b2d2-e667-49cf-894e-913bc166f8c3', 'a6152467-f0ee-4be3-90c0-7635450a58ae', '23d95038-a805-432b-ac0d-9a59bbebf45b', '786f53cd-3f93-4224-b2e2-a45e21b02934', '6722de63-59a2-4974-a242-7c243a71a140', 'd0749e50-a04e-45af-9b01-05209e6429de', 'bfc735fc-ea3e-4e0b-b8e7-785edc4fd42e', 'd877e389-dfb9-4534-b1fa-9ebc80b8f8ef', '475741a1-c7f5-44c6-94e3-39f79529fb9e', 'b543a57b-7cbc-4b95-a457-9adbd2c2fcf8'} | 2024/07/19/[$LATEST]bc6dab21e9484acd94f5d656a1ebb195 | 542754589326:/aws/lambda/azul-indexer-prod-contribute |
| 2024-07-19 23:11:00.571 | [WARNING] 2024-07-19T23:11:00.569Z ee19ed19-8933-5a68-9733-b20d7d801a7d azul.indexer.index_controller Worker failed to handle message {'action': 'add', 'notification': {'transaction_id': 'e5ccc122-5a7a-4bf5-b4b3-7b5beebf661e', 'bundle_fqid': {'uuid': '8911c4d5-ddbd-5d9b-8543-c773356386f3', 'version': '2021-02-08T09:30:00.000000Z', 'source': {'id': 'baf133cf-37e4-413f-a034-4d3edbf4a11c', 'spec': 'tdr:datarepo-f9579ac6:snapshot/hca_prod_2ef3655a973d4d699b4121fa4041eed7__20220111_dcp2_20240711_dcp40:/0'}}}, 'catalog': 'dcp40'}. Traceback (most recent call last):   File "/var/task/azul/indexer/index_controller.py", line 180, in contribute     contributions, replicas = self.transform(catalog, notification, delete)                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^   File "/var/task/azul/indexer/index_controller.py", line 232, in transform     bundle = service.fetch_bundle(catalog, bundle_fqid)              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^   File "/var/task/azul/indexer/index_service.py", line 196, in fetch_bundle     return plugin.fetch_bundle(bundle_fqid)            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^   File "/var/task/azul/plugins/repository/tdr.py", line 212, in fetch_bundle     bundle = self._emulate_bundle(bundle_fqid)              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^   File "/var/task/azul/plugins/repository/tdr_hca/__init__.py", line 362, in _emulate_bundle     entities, root_entities, links_jsons = self._stitch_bundles(bundle)                                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^   File "/var/task/azul/plugins/repository/tdr_hca/__init__.py", line 438, in _stitch_bundles     upstream = self._find_upstream_bundles(source, all_dangling_inputs)                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^   File "/var/task/azul/plugins/repository/tdr_hca/__init__.py", line 564, in _find_upstream_bundles     require(not missing,   File "/var/task/azul/__init__.py", line 1612, in require     reject(not condition, *args, exception=exception)   File "/var/task/azul/__init__.py", line 1631, in reject     raise exception(*args) azul.RequirementError: Dangling inputs not found in any bundle: {'6593375f-8c8a-48d5-9246-0dcfeabd5d97', 'd0749e50-a04e-45af-9b01-05209e6429de', '27639c1d-bcd9-4c65-9a72-9177b410f357', '786f53cd-3f93-4224-b2e2-a45e21b02934', '58ac64da-8016-4296-8054-23206291b2d4', '6722de63-59a2-4974-a242-7c243a71a140', 'a6152467-f0ee-4be3-90c0-7635450a58ae', 'b5a78d96-efc1-4af8-8877-bbdafab852e6', 'b543a57b-7cbc-4b95-a457-9adbd2c2fcf8', 'd877e389-dfb9-4534-b1fa-9ebc80b8f8ef', 'a1c4b2d2-e667-49cf-894e-913bc166f8c3', 'b3e4c7ac-262a-416b-ab60-8f950f52e015', '77644f23-10f8-4378-b94b-3431ae3496f7', '23d95038-a805-432b-ac0d-9a59bbebf45b', '4f49933e-88d5-49df-a065-a192de2e39e5', 'bfc735fc-ea3e-4e0b-b8e7-785edc4fd42e'} | 2024/07/19/[$LATEST]8026c1fd27be4c069d78805b9f654309 | 542754589326:/aws/lambda/azul-indexer-prod-contribute |
| 2024-07-19 23:07:46.771 | [WARNING] 2024-07-19T23:07:46.769Z 2b62ad82-100f-501f-9f26-f296e3ef7bec azul.indexer.index_controller Worker failed to handle message {'action': 'add', 'notification': {'transaction_id': 'a73efe37-93f5-4180-93a5-69ce179e86db', 'bundle_fqid': {'uuid': 'ee80d2e9-76e9-53eb-9d5d-d76b527ddc47', 'version': '2021-02-08T09:30:00.000000Z', 'source': {'id': 'baf133cf-37e4-413f-a034-4d3edbf4a11c', 'spec': 'tdr:datarepo-f9579ac6:snapshot/hca_prod_2ef3655a973d4d699b4121fa4041eed7__20220111_dcp2_20240711_dcp40:/0'}}}, 'catalog': 'dcp40'}. Traceback (most recent call last):   File "/var/task/azul/indexer/index_controller.py", line 180, in contribute     contributions, replicas = self.transform(catalog, notification, delete)                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^   File "/var/task/azul/indexer/index_controller.py", line 232, in transform     bundle = service.fetch_bundle(catalog, bundle_fqid)              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^   File "/var/task/azul/indexer/index_service.py", line 196, in fetch_bundle     return plugin.fetch_bundle(bundle_fqid)            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^   File "/var/task/azul/plugins/repository/tdr.py", line 212, in fetch_bundle     bundle = self._emulate_bundle(bundle_fqid)              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^   File "/var/task/azul/plugins/repository/tdr_hca/__init__.py", line 362, in _emulate_bundle     entities, root_entities, links_jsons = self._stitch_bundles(bundle)                                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^   File "/var/task/azul/plugins/repository/tdr_hca/__init__.py", line 438, in _stitch_bundles     upstream = self._find_upstream_bundles(source, all_dangling_inputs)                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^   File "/var/task/azul/plugins/repository/tdr_hca/__init__.py", line 564, in _find_upstream_bundles     require(not missing,   File "/var/task/azul/__init__.py", line 1612, in require     reject(not condition, *args, exception=exception)   File "/var/task/azul/__init__.py", line 1631, in reject     raise exception(*args) azul.RequirementError: Dangling inputs not found in any bundle: {'475741a1-c7f5-44c6-94e3-39f79529fb9e'} | 2024/07/19/[$LATEST]740d52299350489abbc0b08be6fea81c | 542754589326:/aws/lambda/azul-indexer-prod-contribute |
---

### PR DESCRIPTION
**Pull request by achave11-ucsc**
Connected issue: #6431

- Manually index the `2ef3655a` project from the `dcp12` catalog

### Author

- [x] Target branch is `prod`
- [x] Name of PR branch matches `hotfixes/<GitHub handle of author>/<issue#>-<slug>-prod`
- [x] On ZenHub, PR is connected to the issue it hotfixes
- [x] PR description links to connected issue
- [x] PR title is `Hotfix prod: ` followed by title of connected issue
- [x] PR title references the connected issue

### Author (hotfixes)

- [x] Added `h` tag to commit title <sub>or this PR does not include a temporary hotfix</sub>
- [x] Added `H` tag to commit title <sub>or this PR does not include a permanent hotfix</sub>
- [x] Added `hotfix` label to PR
- [x] This PR is labeled `partial` <sub>or represents a permanent hotfix</sub>

### Author (before every review)

- [x] Rebased PR branch on `prod`, squashed old fixups
- [x] Ran `make requirements_update` <sub>or this PR does not modify `requirements*.txt`, `common.mk`, `Makefile` and `Dockerfile`</sub>
- [x] Added `R` tag to commit title <sub>or this PR does not modify `requirements*.txt`</sub>
- [x] This PR is labeled `reqs` <sub>or does not modify `requirements*.txt`</sub>

### System administrator (after approval)

- [x] Actually approved the PR
- [x] Labeled PR as `no sandbox`
- [x] A comment to this PR details the completed security design review
- [x] PR title is appropriate as title of merge commit
- [x] Moved ticket to *Approved* column
- [x] PR is assigned to only the operator

### Operator (before pushing merge the commit)

- [x] Squashed PR branch and rebased onto `prod`
- [x] Sanity-checked history
- [x] Pushed PR branch to GitHub
- [x] The title of the merge commit starts with the title of this PR
- [x] Added PR # reference to merge commit title
- [x] Collected commit title tags in merge commit title <sub>but excluded any `p` tags</sub>
- [x] Moved connected issue to *Merged stable* column in ZenHub
- [x] Pushed merge commit to GitHub

### Operator (after pushing the merge commit)

- [x] Pushed merge commit to GitLab `prod`
- [x] Build passes on GitLab `prod`
- [x] Reviewed build logs for anomalies on GitLab `prod`
- [x] Deleted PR branch from GitHub

### Operator (reindex)

- [x] Deindexed all unreferenced catalogs in `prod` <sub>or this PR is neither labeled `reindex:partial` nor `reindex:prod`</sub>
- [x] Deindexed specific sources in `prod` <sub>or this PR is neither labeled `reindex:partial` nor `reindex:prod`</sub>
- [x] Indexed specific sources in `prod` <sub>or this PR is neither labeled `reindex:partial` nor `reindex:prod`</sub>
- [x] Started reindex in `prod` <sub>or neither this PR nor a failed, prior promotion requires it</sub>
- [x] Checked for, triaged and possibly requeued messages in both fail queues in `prod` <sub>or neither this PR nor a failed, prior promotion requires it</sub>
- [x] Emptied fail queues in `prod` <sub>or neither this PR nor a failed, prior promotion requires it</sub>
- [x] Created backport PR and linked to it [in a comment](https://github.com/DataBiosphere/azul/pull/6434#issuecomment-2246896709) on this PR

### Operator

- [x] PR is assigned to no one

## Shorthand for review comments

- `L` line is too long
- `W` line wrapping is wrong
- `Q` bad quotes
- `F` other formatting problem

### CODE REVIEW

**Comment by achave11-ucsc** [comment]
Project count was not changed since the snapshot removed was an update.

**Review by hannes-ucsc — CHANGES_REQUESTED** [review]
Don't you need to update the count?

**Review by hannes-ucsc — APPROVED** [review]
Never mind. I just remembered that this is an updated snapshot.

**Comment by achave11-ucsc** [comment]
Backported as part of PR #6425

**Pull request merged**
