### PR TITLE
Resolve vulnerabilities in azul-pycharm image (DataBiosphere/azul-private#94)

### PR DESCRIPTION
**Pull request by dsotirho-ucsc**
Connected issues: DataBiosphere/azul-private#94

### Author

- [x] PR is a draft
- [x] Target branch is `develop`
- [x] Name of PR branch matches `issues/<GitHub handle of author>/<issue#>-<slug>`
- [x] PR title references all connected issues
- [x] PR title matches<sup>1</sup> that of a connected issue <sub>or comment in PR explains why they're different</sub>
- [x] For each connected issue, there is at least one commit whose title references that issue
- [x] PR is connected to all connected issues via ZenHub
- [x] PR description links to connected issues
- [x] Added `partial` label to PR <sub>or this PR completely resolves all connected issues</sub>

<sup>1</sup> when the issue title describes a problem, the corresponding PR
title is `Fix: ` followed by the issue title

### Author (reindex, API changes)

- [x] Added `r` tag to commit title <sub>or this PR does not require reindexing</sub>
- [x] Added `reindex` label to PR <sub>or this PR does not require reindexing</sub>
- [x] PR and connected issue are labeled `API` <sub>or this PR does not modify a REST API</sub>
- [x] Added `a` (`A`) tag to commit title for backwards (in)compatible changes <sub>or this PR does not modify a REST API</sub>
- [x] Updated REST API version number in `app.py` <sub>or this PR does not modify a REST API</sub>

### Author (chains)

- [x] This PR is blocked by previous PR in the chain <sub>or this PR is not chained to another PR</sub>
- [x] Added `base` label to the blocking PR <sub>or this PR is not chained to another PR</sub>
- [x] Added `chained` label to this PR <sub>or this PR is not chained to another PR</sub>

### Author (upgrading)

- [x] Documented upgrading of deployments in UPGRADING.rst <sub>or this PR does not require upgrading</sub>
- [x] Added `u` tag to commit title <sub>or this PR does not require upgrading</sub>
- [x] Added `upgrade` label to PR <sub>or this PR does not require upgrading</sub>

### Author (operator tasks)

- [x] Added checklist items for additional operator tasks <sub>or this PR does not require additional tasks</sub>

### Author (hotfixes)

- [x] Added `F` tag to main commit title <sub>or this PR does not include permanent fix for a temporary hotfix</sub>
- [x] Reverted the temporary hotfixes for any connected issues <sub>or the `prod` branch has no temporary hotfixes for any connected issues</sub>

### Author (before every review)

- [x] Rebased PR branch on `develop`, squashed old fixups
- [x] Ran `make requirements_update` <sub>or this PR does not touch requirements*.txt, common.mk, Makefile and Dockerfile</sub>
- [x] Added `R` tag to commit title <sub>or this PR does not touch requirements*.txt</sub>
- [x] Added `reqs` label to PR <sub>or this PR does not touch requirements*.txt</sub>
- [x] `make integration_test` passes in personal deployment <sub>or this PR does not touch functionality that could break the IT</sub>

### Peer reviewer (after requesting changes)

Uncheck the *Author (before every review)* checklists.

### Peer reviewer (after approval)

- [x] PR is not a draft
- [x] Ticket is in *Review requested* column
- [x] Requested review from primary reviewer
- [x] Assigned PR to primary reviewer

### Primary reviewer (after requesting changes)

Uncheck the *before every review* checklists. Update the `N reviews` label.

### Primary reviewer (after approval)

- [x] Actually approved the PR
- [x] Labeled connected issues as `demo` or `no demo`
- [x] Commented on connected issues about demo expectations <sub>or all connected issues are labeled `no demo`</sub>
- [x] Decided if PR can be labeled `no sandbox`
- [x] PR title is appropriate as title of merge commit
- [x] `N reviews` label is accurate
- [x] Moved ticket to *Approved* column
- [x] Assigned PR to current operator

### Operator (before pushing merge the commit)

- [x] Checked `reindex` label and `r` commit title tag
- [x] Checked that demo expectations are clear <sub>or all connected issues are labeled `no demo`</sub>
- [x] PR has checklist items for upgrading instructions <sub>or PR is not labeled `upgrade`</sub>
- [x] Squashed PR branch and rebased onto `develop`
- [x] Sanity-checked history
- [x] Pushed PR branch to GitHub
- [x] Manually deployed `dev.shared`
- [x] Pushed PR branch to GitLab `dev` and added `sandbox` label <sub>or PR is labeled `no sandbox`</sub>
- [x] Manually deployed `anvildev.shared`
- [x] Pushed PR branch to GitLab `anvildev` <sub>or PR is labeled `no sandbox`</sub>
- [x] Manually deployed `anvilprod.shared`
- [x] Pushed PR branch to GitLab `anvilprod` <sub>or PR is labeled `no sandbox`</sub>
- [x] Build passes in `sandbox` deployment <sub>or PR is labeled `no sandbox`</sub>
- [x] Build passes in `anvilbox` deployment <sub>or PR is labeled `no sandbox`</sub>
- [x] Build passes in `hammerbox` deployment <sub>or PR is labeled `no sandbox`</sub>
- [x] Reviewed build logs for anomalies in `sandbox` deployment <sub>or PR is labeled `no sandbox`</sub>
- [x] Reviewed build logs for anomalies in `anvilbox` deployment <sub>or PR is labeled `no sandbox`</sub>
- [x] Reviewed build logs for anomalies in `hammerbox` deployment <sub>or PR is labeled `no sandbox`</sub>
- [x] Deleted unreferenced indices in `sandbox` <sub>or this PR does not remove catalogs or otherwise causes unreferenced indices </sub>
- [x] Deleted unreferenced indices in `anvilbox` <sub>or this PR does not remove catalogs or otherwise causes unreferenced indices </sub>
- [x] Deleted unreferenced indices in `hammerbox` <sub>or this PR does not remove catalogs or otherwise causes unreferenced indices </sub>
- [x] Started reindex in `sandbox` <sub>or this PR does not require reindexing `sandbox`</sub>
- [x] Started reindex in `anvilbox` <sub>or this PR does not require reindexing `sandbox`</sub>
- [x] Started reindex in `hammerbox` <sub>or this PR does not require reindexing `sandbox`</sub>
- [x] Checked for failures in `sandbox` <sub>or this PR does not require reindexing `sandbox`</sub>
- [x] Checked for failures in `anvilbox` <sub>or this PR does not require reindexing `sandbox`</sub>
- [x] Checked for failures in `hammerbox` <sub>or this PR does not require reindexing `sandbox`</sub>
- [x] Title of merge commit starts with title from this PR
- [x] Added PR reference to merge commit title
- [x] Added commit title tags to merge commit title
- [x] Moved connected issues to Merged column in ZenHub
- [x] Pushed merge commit to GitHub

### Operator (chain shortening)

- [x] Changed the target branch of the blocked PR to `develop` <sub>or this PR is not labeled `base`</sub>
- [x] Removed the `chained` label from the blocked PR <sub>or this PR is not labeled `base`</sub>
- [x] Removed the blocking relationship from the blocked PR <sub>or this PR is not labeled `base`</sub>
- [x] Removed the `base` label from this PR <sub>or this PR is not labeled `base`</sub>

### Operator (after pushing the merge commit)

- [x] Pushed merge commit to GitLab `dev` <sub>or PR is labeled `no sandbox`</sub>
- [x] Pushed merge commit to GitLab `anvildev` <sub>or PR is labeled `no sandbox`</sub>
- [x] Pushed merge commit to GitLab `anvilprod` <sub>or PR is labeled `no sandbox`</sub>
- [x] Build passes on GitLab `dev`<sup>1</sup>
- [x] Reviewed build logs for anomalies on GitLab `dev`<sup>1</sup>
- [x] Build passes on GitLab `anvildev`<sup>1</sup>
- [x] Reviewed build logs for anomalies on GitLab `anvildev`<sup>1</sup>
- [x] Build passes on GitLab `anvilprod`<sup>1</sup>
- [x] Reviewed build logs for anomalies on GitLab `anvilprod`<sup>1</sup>
- [x] Deleted PR branch from GitHub
- [x] Deleted PR branch from GitLab `dev`
- [x] Deleted PR branch from GitLab `anvildev`
- [x] Deleted PR branch from GitLab `anvilprod`

<sup>1</sup> When pushing the merge commit is skipped due to the PR being
labelled `no sandbox`, the next build triggered by a PR whose merge commit *is*
pushed determines this checklist item.

### Operator (reindex)

- [x] Deleted unreferenced indices in `dev` <sub>or this PR does not remove catalogs or otherwise causes unreferenced indices </sub>
- [x] Deleted unreferenced indices in `anvildev` <sub>or this PR does not remove catalogs or otherwise causes unreferenced indices </sub>
- [x] Deleted unreferenced indices in `anvilprod` <sub>or this PR does not remove catalogs or otherwise causes unreferenced indices </sub>
- [x] Started reindex in `dev` <sub>or this PR does not require reindexing</sub>
- [x] Started reindex in `anvildev` <sub>or this PR does not require reindexing</sub>
- [x] Started reindex in `anvilprod` <sub>or this PR does not require reindexing</sub>
- [x] Checked for and triaged indexing failures in `dev` <sub>or this PR does not require reindexing</sub>
- [x] Checked for and triaged indexing failures in `anvildev` <sub>or this PR does not require reindexing</sub>
- [x] Checked for and triaged indexing failures in `anvilprod` <sub>or this PR does not require reindexing</sub>
- [x] Emptied fail queues in `dev` deployment <sub>or this PR does not require reindexing</sub>
- [x] Emptied fail queues in `anvildev` deployment <sub>or this PR does not require reindexing</sub>
- [x] Emptied fail queues in `anvilprod` deployment <sub>or this PR does not require reindexing</sub>

### Operator

- [x] Added CL item to `prod` promotion PR:
> - [ ] Manually deployed `prod.shared`
- [x] Unassigned PR

## Shorthand for review comments

- `L` line is too long
- `W` line wrapping is wrong
- `Q` bad quotes
- `F` other formatting problem

### CODE REVIEW

**Comment by dsotirho-ucsc** [comment]
Tested PR by deploying pycharm image 2022.3.3-3 to `dev.shared` and running `make format`.

<details>
<summary>Terminal log running `make format`</summary>

```
(.venv) daniel@Crispin ~/repo/azul1 $ make format
docker run \
	    --rm \
	    --volume $(python scripts/resolve_container_path.py /Users/daniel/repo/azul1):/home/developer/azul \
	    --workdir /home/developer/azul \
	    122796619775.dkr.ecr.us-east-1.amazonaws.com/docker.io/ucscgi/azul-pycharm:2022.3.3-3 \
	    /opt/pycharm/bin/format.sh -r -settings .pycharm.style.xml -mask '*.py' src scripts test lambdas/layer/app.py lambdas/indexer/app.py lambdas/service/app.py .flake8/azul_flake8.py environment.py deployments/anvilbox/environment.py deployments/anvildev.browser/environment.py deployments/anvildev.gitlab/environment.py deployments/anvildev.shared/environment.py deployments/anvildev/environment.py deployments/anvilprod.browser/environment.py deployments/anvilprod.gitlab/environment.py deployments/anvilprod.shared/environment.py deployments/anvilprod/environment.py deployments/daniel.local/environment.py deployments/daniel2.local/environment.py deployments/dev.gitlab/environment.py deployments/dev.shared/environment.py deployments/dev/environment.py deployments/hammerbox/environment.py deployments/prod.gitlab/environment.py deployments/prod.shared/environment.py deployments/prod/environment.py deployments/sandbox/environment.py terraform/backend.tf.json.template.py terraform/common.tf.json.template.py terraform/step_function.tf.json.template.py terraform/lambda_layer.tf.json.template.py terraform/dynamo.tf.json.template.py terraform/cloudwatch.tf.json.template.py terraform/elasticsearch.tf.json.template.py terraform/api_gateway.tf.json.template.py terraform/providers.tf.json.template.py terraform/authentication.tf.json.template.py terraform/sqs.tf.json.template.py terraform/s3.tf.json.template.py terraform/gitlab/gitlab.tf.json.template.py terraform/shared/shared.tf.json.template.py terraform/browser/browser.tf.json.template.py lambdas/indexer/.chalice/config.json.template.py lambdas/service/.chalice/config.json.template.py .github/pull_request_template.md.template.py
Unable to find image '122796619775.dkr.ecr.us-east-1.amazonaws.com/docker.io/ucscgi/azul-pycharm:2022.3.3-3' locally
2022.3.3-3: Pulling from ucscgi/azul-pycharm
Digest: sha256:18f7f2771604a1f57a471fa8ccdfc64dfd70ac6e80d1d9a0101dd6eb94465b17
Status: Downloaded newer image for 122796619775.dkr.ecr.us-east-1.amazonaws.com/docker.io/ucscgi/azul-pycharm:2022.3.3-3
CompileCommand: exclude com/intellij/openapi/vfs/impl/FilePartNodeRoot.trieDescend bool exclude = true
PyCharm 2022.3.3, build PC-223.8836.43 Formatter
2023-10-05 15:39:28,411 [   2003]   WARN - #c.i.e.RunManager - Must be not called before project components initialized
Info  | RdCoroutineScope          | 40:DefaultDispatcher-worker-21 | RdCoroutineHost overridden
Formatting /home/developer/azul/src/humancellatlas/data/metadata/lookup.py...OK
Formatting /home/developer/azul/src/humancellatlas/data/metadata/api.py...OK
Formatting /home/developer/azul/src/humancellatlas/data/metadata/age_range.py...OK
Formatting /home/developer/azul/src/humancellatlas/data/metadata/datetime.py...OK
Formatting /home/developer/azul/src/humancellatlas/data/metadata/helpers/exception.py...OK
Formatting /home/developer/azul/src/humancellatlas/data/metadata/helpers/staging_area.py...OK
Formatting /home/developer/azul/src/humancellatlas/data/metadata/helpers/json.py...OK
Formatting /home/developer/azul/src/humancellatlas/data/metadata/helpers/schema_validation.py...OK
Formatting /home/developer/azul/src/azul/doctests.py...OK
Formatting /home/developer/azul/src/azul/uuids.py...OK
Formatting /home/developer/azul/src/azul/remote_debug.py...OK
Formatting /home/developer/azul/src/azul/auth.py...OK
Formatting /home/developer/azul/src/azul/time.py...OK
Formatting /home/developer/azul/src/azul/azulclient.py...OK
Formatting /home/developer/azul/src/azul/logging.py...OK
Formatting /home/developer/azul/src/azul/files.py...OK
Formatting /home/developer/azul/src/azul/enums.py...OK
Formatting /home/developer/azul/src/azul/queues.py...OK
Formatting /home/developer/azul/src/azul/terraform.py...OK
Formatting /home/developer/azul/src/azul/deployment.py...OK
Formatting /home/developer/azul/src/azul/oauth2.py...OK
Formatting /home/developer/azul/src/azul/plugins/repository/tdr_anvil/__init__.py...OK
Formatting /home/developer/azul/src/azul/plugins/repository/tdr_hca/__init__.py...OK
Formatting /home/developer/azul/src/azul/plugins/repository/canned/__init__.py...OK
Formatting /home/developer/azul/src/azul/plugins/repository/__init__.py...OK
Formatting /home/developer/azul/src/azul/plugins/repository/dss/__init__.py...OK
Formatting /home/developer/azul/src/azul/plugins/repository/tdr.py...OK
Formatting /home/developer/azul/src/azul/plugins/__init__.py...OK
Formatting /home/developer/azul/src/azul/plugins/metadata/hca/bundle.py...OK
Formatting /home/developer/azul/src/azul/plugins/metadata/hca/__init__.py...OK
Formatting /home/developer/azul/src/azul/plugins/metadata/hca/service/aggregation.py...OK
Formatting /home/developer/azul/src/azul/plugins/metadata/hca/service/__init__.py...OK
Formatting /home/developer/azul/src/azul/plugins/metadata/hca/service/response.py...OK
Formatting /home/developer/azul/src/azul/plugins/metadata/hca/service/contributor_matrices.py...OK
Formatting /home/developer/azul/src/azul/plugins/metadata/hca/service/filter.py...OK
Formatting /home/developer/azul/src/azul/plugins/metadata/hca/indexer/aggregate.py...OK
Formatting /home/developer/azul/src/azul/plugins/metadata/hca/indexer/__init__.py...OK
Formatting /home/developer/azul/src/azul/plugins/metadata/hca/indexer/transform.py...OK
Formatting /home/developer/azul/src/azul/plugins/metadata/__init__.py...OK
Formatting /home/developer/azul/src/azul/plugins/metadata/anvil/bundle.py...OK
Formatting /home/developer/azul/src/azul/plugins/metadata/anvil/__init__.py...OK
Formatting /home/developer/azul/src/azul/plugins/metadata/anvil/service/aggregation.py...OK
Formatting /home/developer/azul/src/azul/plugins/metadata/anvil/service/__init__.py...OK
Formatting /home/developer/azul/src/azul/plugins/metadata/anvil/service/response.py...OK
Formatting /home/developer/azul/src/azul/plugins/metadata/anvil/service/filter.py...OK
Formatting /home/developer/azul/src/azul/plugins/metadata/anvil/indexer/aggregate.py...OK
Formatting /home/developer/azul/src/azul/plugins/metadata/anvil/indexer/__init__.py...OK
Formatting /home/developer/azul/src/azul/plugins/metadata/anvil/indexer/transform.py...OK
Formatting /home/developer/azul/src/azul/health.py...OK
Formatting /home/developer/azul/src/azul/bigquery.py...OK
Formatting /home/developer/azul/src/azul/__init__.py...OK
Formatting /home/developer/azul/src/azul/types.py...OK
Formatting /home/developer/azul/src/azul/lambda_layer.py...OK
Formatting /home/developer/azul/src/azul/openapi/params.py...OK
Formatting /home/developer/azul/src/azul/openapi/responses.py...OK
Formatting /home/developer/azul/src/azul/openapi/__init__.py...OK
Formatting /home/developer/azul/src/azul/openapi/spec.py...OK
Formatting /home/developer/azul/src/azul/openapi/schema.py...OK
Formatting /home/developer/azul/src/azul/compliance/fedramp_inventory_service.py...OK
Formatting /home/developer/azul/src/azul/compliance/__init__.py...OK
Formatting /home/developer/azul/src/azul/docker.py...OK
Formatting /home/developer/azul/src/azul/terra.py...OK
Formatting /home/developer/azul/src/azul/threads.py...OK
Formatting /home/developer/azul/src/azul/changelog.py...OK
Formatting /home/developer/azul/src/azul/caching.py...OK
Formatting /home/developer/azul/src/azul/collections.py...OK
Formatting /home/developer/azul/src/azul/aws_service_model.py...OK
Formatting /home/developer/azul/src/azul/http.py...OK
Formatting /home/developer/azul/src/azul/chalice.py...OK
Formatting /home/developer/azul/src/azul/iterators.py...OK
Formatting /home/developer/azul/src/azul/es.py...OK
Formatting /home/developer/azul/src/azul/template.py...OK
Formatting /home/developer/azul/src/azul/args.py...OK
Formatting /home/developer/azul/src/azul/vendored/frozendict/__init__.py...OK
Formatting /home/developer/azul/src/azul/vendored/__init__.py...OK
Formatting /home/developer/azul/src/azul/exceptions.py...OK
Formatting /home/developer/azul/src/azul/bigquery_reservation.py...OK
Formatting /home/developer/azul/src/azul/modules.py...OK
Formatting /home/developer/azul/src/azul/json_freeze.py...OK
Formatting /home/developer/azul/src/azul/service/elasticsearch_service.py...OK
Formatting /home/developer/azul/src/azul/service/catalog_controller.py...OK
Formatting /home/developer/azul/src/azul/service/source_service.py...OK
Formatting /home/developer/azul/src/azul/service/repository_controller.py...OK
Formatting /home/developer/azul/src/azul/service/repository_service.py...OK
Formatting /home/developer/azul/src/azul/service/async_manifest_service.py...OK
Formatting /home/developer/azul/src/azul/service/__init__.py...OK
Formatting /home/developer/azul/src/azul/service/drs_controller.py...OK
Formatting /home/developer/azul/src/azul/service/source_controller.py...OK
Formatting /home/developer/azul/src/azul/service/buffer.py...OK
Formatting /home/developer/azul/src/azul/service/lambda_iam_policy.py...OK
Formatting /home/developer/azul/src/azul/service/manifest_service.py...OK
Formatting /home/developer/azul/src/azul/service/storage_service.py...OK
Formatting /home/developer/azul/src/azul/service/avro_pfb.py...OK
Formatting /home/developer/azul/src/azul/service/manifest_controller.py...OK
Formatting /home/developer/azul/src/azul/hmac.py...OK
Formatting /home/developer/azul/src/azul/objects.py...OK
Formatting /home/developer/azul/src/azul/version_service.py...OK
Formatting /home/developer/azul/src/azul/portal_service.py...OK
Formatting /home/developer/azul/src/azul/dss.py...OK
Formatting /home/developer/azul/src/azul/json.py...OK
Formatting /home/developer/azul/src/azul/indexer/aggregate.py...OK
Formatting /home/developer/azul/src/azul/indexer/document_service.py...OK
Formatting /home/developer/azul/src/azul/indexer/index_service.py...OK
Formatting /home/developer/azul/src/azul/indexer/__init__.py...OK
Formatting /home/developer/azul/src/azul/indexer/log_forwarding_service.py...OK
Formatting /home/developer/azul/src/azul/indexer/transform.py...OK
Formatting /home/developer/azul/src/azul/indexer/document.py...OK
Formatting /home/developer/azul/src/azul/indexer/log_forwarding_controller.py...OK
Formatting /home/developer/azul/src/azul/indexer/lambda_iam_policy.py...OK
Formatting /home/developer/azul/src/azul/indexer/index_controller.py...OK
Formatting /home/developer/azul/src/azul/drs.py...OK
Formatting /home/developer/azul/src/azul/strings.py...OK
Formatting /home/developer/azul/src/azul/lambdas.py...OK
Formatting /home/developer/azul/scripts/check_branch.py...OK
Formatting /home/developer/azul/scripts/envhook.py...OK
Formatting /home/developer/azul/scripts/delete_bundle.py...OK
Formatting /home/developer/azul/scripts/confirm_sns_subscription.py...OK
Formatting /home/developer/azul/scripts/list_unit_tests.py...OK
Formatting /home/developer/azul/scripts/post_deploy_tdr.py...OK
Formatting /home/developer/azul/scripts/provision_credentials.py...OK
Formatting /home/developer/azul/scripts/reset_lambda_role.py...OK
Formatting /home/developer/azul/scripts/manage_queues.py...OK
Formatting /home/developer/azul/scripts/locust/service.py...OK
Formatting /home/developer/azul/scripts/manifest_404.py...OK
Formatting /home/developer/azul/scripts/import_default_vpc.py...OK
Formatting /home/developer/azul/scripts/reset_portal_db.py...OK
Formatting /home/developer/azul/scripts/convert_environment.py...OK
Formatting /home/developer/azul/scripts/sell_unused_slots.py...OK
Formatting /home/developer/azul/scripts/generate_openapi_document.py...OK
Formatting /home/developer/azul/scripts/export_environment.py...OK
Formatting /home/developer/azul/scripts/compliance/fedramp_inventory.py...OK
Formatting /home/developer/azul/scripts/securityhub2csv.py...OK
Formatting /home/developer/azul/scripts/github_status_check.py...OK
Formatting /home/developer/azul/scripts/can_bundle.py...OK
Formatting /home/developer/azul/scripts/fetch_requirement_licences.py...OK
Formatting /home/developer/azul/scripts/stage_layer.py...OK
Formatting /home/developer/azul/scripts/copy_images_to_ecr.py...OK
Formatting /home/developer/azul/scripts/cgm_adapter.py...OK
Formatting /home/developer/azul/scripts/import_api_gateway_stage.py...OK
Formatting /home/developer/azul/scripts/recan_bundle_tdr.py...OK
Formatting /home/developer/azul/scripts/update_subgraph_counts.py...OK
Formatting /home/developer/azul/scripts/manage_lambdas.py...OK
Formatting /home/developer/azul/scripts/rename_resources.py...OK
Formatting /home/developer/azul/scripts/scrape_aws_service_model.py...OK
Formatting /home/developer/azul/scripts/reindex.py...OK
Formatting /home/developer/azul/scripts/resolve_container_path.py...OK
Formatting /home/developer/azul/scripts/kibana_proxy.py...OK
Formatting /home/developer/azul/scripts/elasticsearch_nodes.py...OK
Formatting /home/developer/azul/scripts/manage_requirements.py...OK
Formatting /home/developer/azul/scripts/terraform_schema.py...OK
Formatting /home/developer/azul/scripts/create_gitlab_snapshot.py...OK
Formatting /home/developer/azul/scripts/manage_portals.py...OK
Formatting /home/developer/azul/test/hca_metadata_api/__init__.py...OK
Formatting /home/developer/azul/test/hca_metadata_api/test.py...OK
Formatting /home/developer/azul/test/test_changelog.py...OK
Formatting /home/developer/azul/test/es_test_case.py...OK
Formatting /home/developer/azul/test/test_app_logging.py...OK
Formatting /home/developer/azul/test/dynamodb_test_case.py...OK
Formatting /home/developer/azul/test/azul_test_case.py...OK
Formatting /home/developer/azul/test/test_doctests.py...OK
Formatting /home/developer/azul/test/test_openapi.py...OK
Formatting /home/developer/azul/test/sqs_test_case.py...OK
Formatting /home/developer/azul/test/docker_container_test_case.py...OK
Formatting /home/developer/azul/test/app_test_case.py...OK
Formatting /home/developer/azul/test/health_check_test_case.py...OK
Formatting /home/developer/azul/test/version_table_test_case.py...OK
Formatting /home/developer/azul/test/service/test_portal_service.py...OK
Formatting /home/developer/azul/test/service/test_repository_proxy.py...OK
Formatting /home/developer/azul/test/service/test_pagination.py...OK
Formatting /home/developer/azul/test/service/test_repository_projects.py...OK
Formatting /home/developer/azul/test/service/test_source_cache.py...OK
Formatting /home/developer/azul/test/service/test_response.py...OK
Formatting /home/developer/azul/test/service/test_pfb.py...OK
Formatting /home/developer/azul/test/service/test_buffer.py...OK
Formatting /home/developer/azul/test/service/test_app_logging.py...OK
Formatting /home/developer/azul/test/service/test_storage_service.py...OK
Formatting /home/developer/azul/test/service/test_manifest_async.py...OK
Formatting /home/developer/azul/test/service/test_health_check.py...OK
Formatting /home/developer/azul/test/service/__init__.py...OK
Formatting /home/developer/azul/test/service/test_version_service.py...OK
Formatting /home/developer/azul/test/service/test_manifest.py...OK
Formatting /home/developer/azul/test/service/test_drs.py...OK
Formatting /home/developer/azul/test/service/test_request_validation.py...OK
Formatting /home/developer/azul/test/service/test_response_anvil.py...OK
Formatting /home/developer/azul/test/service/test_cache_poisoning.py...OK
Formatting /home/developer/azul/test/service/test_request_builder.py...OK
Formatting /home/developer/azul/test/service/test_repository_specimen.py...OK
Formatting /home/developer/azul/test/test_check_branch.py...OK
Formatting /home/developer/azul/test/test_log_forwarding.py...OK
Formatting /home/developer/azul/test/test_deployment.py...OK
Formatting /home/developer/azul/test/indexer/test_tdr.py...OK
Formatting /home/developer/azul/test/indexer/test_health_check.py...OK
Formatting /home/developer/azul/test/indexer/__init__.py...OK
Formatting /home/developer/azul/test/indexer/test_notifications.py...OK
Formatting /home/developer/azul/test/indexer/test_indexer.py...OK
Formatting /home/developer/azul/test/indexer/test_projects.py...OK
Formatting /home/developer/azul/test/indexer/test_indexer_controller.py...OK
Formatting /home/developer/azul/test/indexer/test_anvil.py...OK
Formatting /home/developer/azul/test/test_azul_flake8.py...OK
Formatting /home/developer/azul/test/integration_test.py...OK
Formatting /home/developer/azul/test/test_tagging.py...OK
Formatting /home/developer/azul/lambdas/layer/app.py...OK
Formatting /home/developer/azul/lambdas/indexer/app.py...OK
Formatting /home/developer/azul/lambdas/service/app.py...OK
Formatting /home/developer/azul/.flake8/azul_flake8.py...OK
Formatting /home/developer/azul/environment.py...OK
Formatting /home/developer/azul/deployments/anvilbox/environment.py...OK
Formatting /home/developer/azul/deployments/anvildev.browser/environment.py...OK
Formatting /home/developer/azul/deployments/anvildev.gitlab/environment.py...OK
Formatting /home/developer/azul/deployments/dev.shared/environment.py...OK
Formatting /home/developer/azul/deployments/anvildev/environment.py...OK
Formatting /home/developer/azul/deployments/anvilprod.browser/environment.py...OK
Formatting /home/developer/azul/deployments/anvilprod.gitlab/environment.py...OK
Formatting /home/developer/azul/deployments/anvilprod.shared/environment.py...OK
Formatting /home/developer/azul/deployments/anvilprod/environment.py...OK
Formatting /home/developer/azul/deployments/daniel.local/environment.py...OK
Formatting /home/developer/azul/deployments/daniel2.local/environment.py...OK
Formatting /home/developer/azul/deployments/dev.gitlab/environment.py...OK
Formatting /home/developer/azul/deployments/dev.shared/environment.py...OK
Formatting /home/developer/azul/deployments/dev/environment.py...OK
Formatting /home/developer/azul/deployments/hammerbox/environment.py...OK
Formatting /home/developer/azul/deployments/dev.gitlab/environment.py...OK
Formatting /home/developer/azul/deployments/dev.shared/environment.py...OK
Formatting /home/developer/azul/deployments/prod/environment.py...OK
Formatting /home/developer/azul/deployments/sandbox/environment.py...OK
Formatting /home/developer/azul/terraform/backend.tf.json.template.py...OK
Formatting /home/developer/azul/terraform/common.tf.json.template.py...OK
Formatting /home/developer/azul/terraform/step_function.tf.json.template.py...OK
Formatting /home/developer/azul/terraform/lambda_layer.tf.json.template.py...OK
Formatting /home/developer/azul/terraform/dynamo.tf.json.template.py...OK
Formatting /home/developer/azul/terraform/cloudwatch.tf.json.template.py...OK
Formatting /home/developer/azul/terraform/elasticsearch.tf.json.template.py...OK
Formatting /home/developer/azul/terraform/api_gateway.tf.json.template.py...OK
Formatting /home/developer/azul/terraform/providers.tf.json.template.py...OK
Formatting /home/developer/azul/terraform/authentication.tf.json.template.py...OK
Formatting /home/developer/azul/terraform/sqs.tf.json.template.py...OK
Formatting /home/developer/azul/terraform/s3.tf.json.template.py...OK
Formatting /home/developer/azul/terraform/gitlab/gitlab.tf.json.template.py...OK
Formatting /home/developer/azul/terraform/shared/shared.tf.json.template.py...OK
Formatting /home/developer/azul/terraform/browser/browser.tf.json.template.py...OK
Formatting /home/developer/azul/lambdas/indexer/.chalice/config.json.template.py...OK
Formatting /home/developer/azul/lambdas/service/.chalice/config.json.template.py...OK
Formatting /home/developer/azul/.github/pull_request_template.md.template.py...OK

243 file(s) scanned.
243 file(s) formatted.
2023-10-05 15:39:44,304 [  17896] SEVERE - #c.i.o.v.n.RefreshQueueImpl - null
org.jetbrains.concurrency.AsyncPromise$Companion$CANCELED$1
2023-10-05 15:39:44,306 [  17898] SEVERE - #c.i.o.v.n.RefreshQueueImpl - PyCharm 2022.3.3  Build #PC-223.8836.43
2023-10-05 15:39:44,306 [  17898] SEVERE - #c.i.o.v.n.RefreshQueueImpl - JDK: 17.0.6; VM: OpenJDK 64-Bit Server VM; Vendor: JetBrains s.r.o.
2023-10-05 15:39:44,306 [  17898] SEVERE - #c.i.o.v.n.RefreshQueueImpl - OS: Linux
(.venv) daniel@Crispin ~/repo/azul1 $
```

</details>

**Review by nadove-ucsc — DISMISSED** [review]
Looks good

**Review by hannes-ucsc — DISMISSED** [review]

**Comment by dsotirho-ucsc** [comment]
[Failed sandbox](https://gitlab.dev.singlecell.gi.ucsc.edu/ucsc/azul/-/jobs/77563) due to stale transitive dependencies

**Review by hannes-ucsc — CHANGES_REQUESTED** [review]
Conflicts.

**Review by hannes-ucsc — DISMISSED** [review]

**Review by hannes-ucsc — APPROVED** [review]

**Comment by hannes-ucsc** [comment]
https://ucsc-gi.slack.com/archives/C705Y6G9Z/p1696872366203919

**Pull request merged**
